#ifndef _classIMAGE_DATA_H
#define _classIMAGE_DATA_H

#include "cNEMO.H"
#include "cJOB.H"
#include "CImageDataDefine.H"
#include "CGuildDefine.H"

#define	dJOB_IMAGE_DATA_COUNT					300
#define	dEQUIPMENT_SHAPE_VARIATION				14

#define	dPALETTE_VARITION_COUNT					10
#define	dGUILD_MARK_ICON_SHAPE_PATTERN_COUNT	10
#define	dGUILD_MARK_COLOR_PATTERN_COUNT			30
#define	dGUILD_MARK_BASE_SHAPE_COLOR_COUNT		256
#define	dMAX_MAGIC_CARPET_SHAPE_COUNT			32
#define	dMONSTER_VARIATION_COUNT				4

class	CImagePalette
{
public:
	WORD	m_wCount;
	WORD	*m_apPalette[dPALETTE_VARITION_COUNT];

			CImagePalette()
			{
				m_wCount	=	0;

				for (int i=0;i<dPALETTE_VARITION_COUNT;i++)	m_apPalette[i]	=	NULL;
			}

			~CImagePalette()
			{
				m_wCount	=	0;

				for (int i=0;i<dPALETTE_VARITION_COUNT;i++)	pKILL(m_apPalette[i]);
			}
};

class	CGuildMarkPalette
{
public:
	WORD			m_awPalette[512];
	WORD			m_awBaseColor[256],m_awBaseColorPalette[256];	//	베이스 컬러와 베이스 컬러를 위한 팔레트

	BOOL			init();	//	초기화
	inline	WORD*	getGradiationPalette(int _iPattern)
	{
		if (_iPattern	>=	dGUILD_MARK_COLOR_PATTERN_COUNT)
			return	NULL;

		return	m_awPalette+_iPattern*8;
	}

	inline	WORD*	getBaseColorPalette(int _iColor1,int _iColor2)
	{
		if (_iColor1	>=	dGUILD_MARK_BASE_SHAPE_COLOR_COUNT || 
			_iColor2	>=	dGUILD_MARK_BASE_SHAPE_COLOR_COUNT ||
			_iColor1	<	0	||	_iColor2	<	0)
			return	NULL;
		
		m_awBaseColorPalette[1]	=	m_awBaseColor[_iColor1];
		m_awBaseColorPalette[2]	=	m_awBaseColor[_iColor2];

		return	m_awBaseColorPalette;
	}
};

class	cMonsterBodyLoadInfo
{
public:
	WORD	m_wLoadMethodValue,m_wTameResistance;
};


class	CGuildMarkImage
{
public:
	void	putIcon(int _iX,int _iY,int _iIndex,int _iColorPattern,int _iScale=100,BOOL _bIsTwinkle=FALSE);
	void	putBase(int _iX,int _iY,int _iIndex,int _iColorPartition,int _iColor1,int _iColor2,int _iScale=100,BOOL _bIsTwinkle=FALSE);
	void	putBaseOutLine(int _iX,int _iY,int _iIndex,int _iColorPattern,int _iScale=100,BOOL _bIsTwinkle=FALSE);
	void	putMark(int _iX,int _iY,int _iIcon,int _iIconColorPattern,int _iBase,int _iBaseColorPartition,int _iBaseColor1,int _iBaseColor2,int _iBaseOutLineColor,	//	길드 마크 출력
					int _iGuildLevel,int _iHallLevel,int _iScale=100,BOOL _bIsTwinkle=FALSE);
};

extern	CGuildMarkImage		g_guildMark;
extern	CGuildMarkPalette	g_guildMarkPalette;
extern	CImagePalette		g_aPalette[dJOB_IMAGE_DATA_COUNT];

extern	cANM_BASE			*g_apBody[dJOB_IMAGE_DATA_COUNT];
extern	cANM_BASE			*g_apMonsterVariation[dJOB_IMAGE_DATA_COUNT][dMONSTER_VARIATION_COUNT];
extern	cANM_BASE			*g_apWeapon[dPLAYER_JOB_COUNT][dEQUIPMENT_SHAPE_VARIATION];
extern	cANM				g_aShield[dPLAYER_JOB_COUNT][dEQUIPMENT_SHAPE_VARIATION];
extern	cANM				g_anmEtc,g_anmGate,g_anmNpcType,g_anmJewel,g_anmGuildBattlePortal,g_anmGameManager,g_anmQuestNpcMark;
extern	cANM				g_aAnmMagicCarpet[dMAX_MAGIC_CARPET_SHAPE_COUNT];
extern	cANM				g_aJobIcon[dPLAYER_JOB_COUNT];	//	즉사 효과
extern	cANM				g_anmHelp,g_anmItemType;
extern	cANM				g_aGuildPet[dGUILD_PET_TYPE_COUNT];
extern	cANM				g_aMiniPetBody[nsMiniPetType::Count];
extern	cANM				g_aDuelBuff[4];
extern	cANM				g_aGGGBuff[4];
extern	cANM				g_anmLongRain, g_anmShortRain, g_anmBombRain;			// 10.02.10 추가

extern	cANM_BASE			*g_apEffect[dEFFECT_IMAGE_DATA_COUNT];
extern	cSPRITE				g_sprBook;
extern	cSPRITE				g_sprFieldItem,g_sprLoading,g_sprLoading2,g_sprArca,g_sprBanner;
extern	cSPRITE				g_sprGameBottomInterface,g_sprNameBar,g_sprInterface,g_sprInterface2,g_sprHitText,g_sprWorldMap, g_sprTitle;		// 10.02.18 g_sprTitle 추가
extern	cSPRITE				g_sprRegionInterface;
extern	cSMI				g_smiIconItem,g_smiIconSkill,g_smiIconGuildSkill,g_smiLoading,g_smiIconGGG;
extern	cSPRITE				g_sprGuildIconShape[dGUILD_MARK_ICON_SHAPE_PATTERN_COUNT],g_sprGuildHallLevel,g_sprGuildIconOutLine,g_sprGuildIconBaseShape;
extern	cSPRITE				g_sprMonsterDiscerner,g_sprMainQuestInterface,g_sprMiniPetIcon;

const	int					c_iPitchmanShopShapeCount	=	6;
extern	cSPRITE				g_asprPitchmanShop[c_iPitchmanShopShapeCount];

extern	cSPRITEQ			g_sprLoadingPannel,g_sprMainQuestEnding;
extern	cSMI				g_smiGuildIconBaseColorPartition;
extern	cANMQ				g_anmMainQuestImage;
extern	cANM				g_anmSageStone,g_anmMagicalShield;
extern	cANM				g_anmGuildFlag;

class	CClientSaveImageData	:	public CSaveImageIndexData
{
public:
	WORD			m_wSmellOfDeathImage,m_wMiniPetSummon;
	WORD			m_wRebirthImage,m_awRebirthMarkImage[5];
	WORD			m_wSoundOfLeadersBellImage,m_wSoundOfLeadersBellMarkImage;
};

class	CImageManager : public CClientSaveImageData
{
public:
	CEffectDataInfo	*m_pEfectInfo;
	WORD			*m_pPalette,m_wPaletteCount;
	BOOL			m_bIsSlimMemoryMode,m_bIsSuperSlimMemoryMode;

	int				m_iLoadedBodyCount;	//	현재 맵에서 불러온  몬스터 수
	int				m_aLoadedBody[dMAX_LOAD_BODY][2];

					CImageManager();
					~CImageManager();

	void			resetIMonsterBody();	//	임시 몬스터 이미지 초기화

	inline	BOOL	isSlimMemoryMode()		{return	m_bIsSlimMemoryMode+m_bIsSuperSlimMemoryMode;}
	inline	BOOL	isSuperSlimMemoryMode()	{return	m_bIsSuperSlimMemoryMode;}
	inline	void	setSlimMemoryMode()		{	m_bIsSlimMemoryMode		=	TRUE;}
	inline	void	setSuperSlimMemoryMode(){	m_bIsSuperSlimMemoryMode=	TRUE;}
	
	BOOL			init(cNUX *_lpNux,cMCU *_lpMcu);
	BOOL			loadEffectByFile(char *_lpstrFileName,cNUX *_lpNux,cMCU *_lpMcu);
	void			close();

	BOOL			convertImageData051116();

	
	BOOL			loadIMonsterBody(int _iBody,int _iVariation);
	BOOL			loadPalette(char *_strFn,cNUX *_lpNux,cMCU *_lpMcu);
	BOOL			loadEffect(char *_strFn,cNUX *_lpNux,cMCU *_lpMcu);
	BOOL			loadHeroImageData(cNUX *_lpNux,cMCU *_lpMcu);
	BOOL			loadStaticMonsterImageData(cNUX *_lpNux,cMCU *_lpMcu);
	BOOL			loadEquipmentImageData(cNUX *_lpNux,cMCU *_lpMcu);
	int				getEffectIndex(char *_strName);//이펙트 인덱스 구하기

	BOOL			loadLocalBody(cNUX *_lpNux=NULL,cMCU *_lpMcu=NULL);//몸뚱아리들 로딩
	BOOL			loadPalette(cNUX *_lpNux=NULL,cMCU *_lpMcu=NULL);

	void			put(int _iImage,int _iX,int _iY,int _iAnm=0,int _iDirect=0,int _iFrame=0,int _iHorzScale=100,int _iVertScale=100);
	void			putShadow(int _iImage,int _iX,int _iY,int _iAnm=0,int _iDirect=0,int _iFrame=0,int _iHorzScale=100,int _iVertScale=100);
	void			putEffect(int _iImage,int _iX,int _iY,int _iFrameCounter,int _iAnm=0,int _iDirect=0,int _iHorzScale=100,int _iVertScale=100);
	void			putWhichUsePalette(int _iImage,int _iX,int _iY,int _iPaletteIndex,int _iAnm,int _iDirect,int _iFrame,int _iHorzScale=100,int _iVertScale=100,int _iOutputEffect=0xffff);
	void			putWhichUsePalette(int _iImage,int _iX,int _iY,WORD *_lpPalette,int _iAnm,int _iDirect,int _iFrame,int _iHorzScale=100,int _iVertScale=100,int _iOutputEffect=0xffff);

	inline	BOOL	isLoadedBody(int _iBody,int _iVariation)
	{
		for (int i=0;i<m_iLoadedBodyCount;i++)
			if	(m_aLoadedBody[i][0]	==	_iBody	&&	m_aLoadedBody[i][1]	==	_iVariation)
				return	TRUE;

		return	FALSE;
	}

	BOOL			isExistBody(int _iBody);

	inline	void	addLoadedBody(int _iBody,int _iVariation)
	{
		m_aLoadedBody[m_iLoadedBodyCount][0]	=	_iBody;
		m_aLoadedBody[m_iLoadedBodyCount][1]	=	_iVariation;

		m_iLoadedBodyCount++;
	}
	cANM*			getEffect(int _iIndex);
	inline	cANM*	getDancingBlockerEffect(){return (cANM *)g_apEffect[m_wDancingBlocker];}
};

extern	CImageManager	g_im;	//	이미지 데이터 메니져

enum
{
	eEANM_FIELD_ITEM_SHINING	,
	eEANM_MINIMAP_HERO_SHINING	,
	eEANM_MINIMAP_GATE			,
	eEANM_MINIMAP_MERCHANT		,
	eEANM_MINIMAP_HOUSE_GATE	,

	eEANM_MINIMAP_BANK_GATE		,
	eEANM_MINIMAP_WEAPON_GATE	,
	eEANM_MINIMAP_ARMOR_GATE	,
	eEANM_MINIMAP_INNER_PORTAL	,
	eEANM_MINIMAP_INNER_DUNGEON	,
	eEANM_MINIMAP_INNER_TOWER	,
	eEANM_MINIMAP_INNER_BUILDING,
	eEANM_MINIMAP_HUNTING_AREA,
	eEANM_MINIMAP_ARROW_DOWN,
	eEANM_MINIMAP_ARROW_UP,
};	//	기타 에니메이션

enum
{// interface_korea

eIK_RANK_12AGE	=	9,
eIK_VIOLENCE		,


};


enum
{
	eGATE_ANM_FOOTPRINT_NORMAL,
	eGATE_ANM_FOOTPRINT_ACTIVE,
	eGATE_ANM_ARROW_NORMAL,
	eGATE_ANM_ARROW_ACTIVE,
};	//	문 에니메이션

enum
{
	eNPC_TYPE_WEAPON_SHOP					,
	eNPC_TYPE_ARMOR_SHOP					,
	eNPC_TYPE_TOOL_SHOP						,
	eNPC_TYPE_QUEST_PROVIDER				,
	eNPC_TYPE_PITCHMAN						,

	eNPC_TYPE_BANK				=	10		,
	eNPC_TYPE_DOUMI				=	12		,
	eNPC_TYPE_SKILL_MASTER		=	14		,
	eNPC_TYPE_TELEPORTER		=	16		,
	eNPC_TYPE_ETC_ITEM_MERCHANT	=	18		,
	eNPC_TYPE_FIRST_HELPER		=	20		,
	eNPC_TYPE_BEGINNER			=	21		,
	eNPC_TYPE_HEALER			=	23		,
	eNPC_TYPE_QUEST_MANAGER		=	25		,
	eNPC_TYPE_SMITH				=	27		,
	eNPC_TYPE_GUILD_HALL_TELEPORTER = 29	,
	eNPC_TYPE_EVENT_HELPER			= 31	,
	eNPC_TYPE_EVENT_ADVENTURER_SOCIETY	= 33	,
};

//	data/interface/game/interface.sd
enum
{
eBUTTON_NORMAL,
eBUTTON_ACTIVE,
eBUTTON_DISABLE,

eBMBI_NORMAL,
eBMBI_ACTIVE,
eBMBI_PRESSED,
eBMBI_DISABLE,

eWINDOW,
eSKILL_WINDOW,

eWINDOW_SEPERATE_BAR,
eWINDOW_THIN_SEPERATE_BAR,
eWINDOW_DOT_SEPERATE_BAR,

eWINDOW_TITLE_STATUS,
eWINDOW_TITLE_INVENTORY,
eWINDOW_TITLE_PARTY,
eWINDOW_TITLE_FRIEND,
eWINDOW_TITLE_GUILD,
eWINDOW_TITLE_QUEST_OLD,
eWINDOW_TITLE_SHOP,
eWINDOW_TITLE_PITCHMAN_SHOP,
eWINDOW_TITLE_TRADE,
eWINDOW_TITLE_SYSTEM,
eWINDOW_TITLE_BANK,
eWINDOW_TITLE_SHOPPING_CART,
eWINDOW_TITLE_REPAIR_ITEM,
eWINDOW_TITLE_PET,
eWINDOW_TITLE_SKILL_TREE,

eWINDOW_CLOSE_ACTIVE,
eWINDOW_CLOSE_PRESSED,

eSW_CHANGE_ICON_SIZE_NORMAL,
eSW_CHANGE_ICON_SIZE_ACTIVE,
eSW_CHANGE_ICON_SIZE_PRESSED,

eWINDOW_INVENTORY_PANNEL,
eWINDOW_INVENTORY_FRAME,
eIWI_TRADE_ACTIVE_,			//인터페이스2의 이미지를 로드하면서 사용하지 않게 되었습니다.여기부터
eIWI_TRADE_PRESSED_,
eIWI_TRADE_DISABLE_,
eIWI_CART_ACTIVE_,
eIWI_CART_PRESSED_,
eIWI_CART_DISABLE_,
eIWI_PITCHMAN_SHOP_ACTIVE_	,
eIWI_PITCHMAN_SHOP_PRESSED_	,
eIWI_PITCHMAN_SHOP_DISABLE_	,
eIWI_CALL_MAGIC_CARPET_ACTIVE_	,
eIWI_CALL_MAGIC_CARPET_PRESSED_	,
eIWI_CALL_MAGIC_CARPET_DISABLE_	,		//여기까지... ㅠ.ㅠ;

eIWI_ITEM_VALID_SLOT	,
eIWI_WEAPON_JOB1_1		,
eIWI_WEAPON_JOB1_2		,
eIWI_WEAPON_JOB2_1		,
eIWI_WEAPON_JOB2_2		,
eIWI_WEAPON_JOB3_1		,
eIWI_WEAPON_JOB3_2		,
eIWI_WEAPON_JOB4_1		,
eIWI_WEAPON_JOB4_2		,
eIWI_WEAPON_JOB5_1		,
eIWI_WEAPON_JOB5_2		,
eIWI_WEAPON_JOB6_1		,
eIWI_WEAPON_JOB6_2		,
eIWI_WEAPON_JOB7_1		,
eIWI_WEAPON_JOB7_2		,
eIWI_WEAPON_JOB8_1		,
eIWI_WEAPON_JOB8_2		,
eIWI_SHIELD				,
eIWI_BULLET				,
eIWI_EAR				,
eIWI_CAPE				,

eIWI_BROOCH				,
eIWI_SHOULDER_TATOO		,
eIWI_CROSS				,

eIWI_BROKEN_ITEM		,

eIWI_ITEM_SLOT_FRAME	,
eIWI_ITEM_SLOT_ANM_1	,
eIWI_ITEM_SLOT_ANM_2	,
eIWI_ITEM_SLOT_ANM_3	,
eIWI_ITEM_SLOT_ANM_4	,
eIWI_ITEM_SLOT_ANM_5	,

eIWI_BLOCKED_ITEM_SLOT	,

eWINDOW_SELECT_SKILL_SLOT,
eWINDOW_SKILL_SLOT_RED,
eWINDOW_SKILL_SLOT_GREEN,
eWINDOW_SKILL_SLOT_BLUE,
eWINDOW_SKILL_SLOT_PURPLE,
eWINDOW_ITEM_SLOT,
eWINDOW_NAME_OPENER,
eWINDOW_NAME_CLOSER,
eWINDOW_SKILL_SEPERATE,

eSCROLLBAR_VERTICAL_NORMAL_UP_BUTTON,
eSCROLLBAR_VERTICAL_PRESSED_UP_BUTTON,
eSCROLLBAR_VERTICAL_ACTIVE_UP_BUTTON,
eSCROLLBAR_VERTICAL_NORMAL_DOWN_BUTTON,
eSCROLLBAR_VERTICAL_PRESSED_DOWN_BUTTON,
eSCROLLBAR_VERTICAL_ACTIVE_DOWN_BUTTON,
eSCROLLBAR_VERTICAL_NORMAL_BODY_TOP,
eSCROLLBAR_VERTICAL_NORMAL_BODY,
eSCROLLBAR_VERTICAL_NORMAL_BODY_BOTTOM,
eSCROLLBAR_VERTICAL_ACTIVE_BODY_TOP,
eSCROLLBAR_VERTICAL_ACTIVE_BODY,
eSCROLLBAR_VERTICAL_ACTIVE_BODY_BOTTOM,

eSCROLLBAR_HORIZON_NORMAL_LEFT_BUTTON,
eSCROLLBAR_HORIZON_PRESSED_LEFT_BUTTON,
eSCROLLBAR_HORIZON_ACTIVE_LEFT_BUTTON,
eSCROLLBAR_HORIZON_NORMAL_RIGHT_BUTTON,
eSCROLLBAR_HORIZON_PRESSED_RIGHT_BUTTON,
eSCROLLBAR_HORIZON_ACTIVE_RIGHT_BUTTON,
eSCROLLBAR_HORIZON_NORMAL_BODY_TOP,
eSCROLLBAR_HORIZON_NORMAL_BODY,
eSCROLLBAR_HORIZON_NORMAL_BODY_BOTTOM,
eSCROLLBAR_HORIZON_ACTIVE_BODY_TOP,
eSCROLLBAR_HORIZON_ACTIVE_BODY,
eSCROLLBAR_HORIZON_ACTIVE_BODY_BOTTOM,

eTOOLTIP_LEFT_TOP,
eTOOLTIP_RIGHT_TOP,
eTOOLTIP_LEFT_BOTTOM,
eTOOLTIP_RIGHT_BOTTOM,
eTOOLTIP_TOP_BORDER,
eTOOLTIP_BOTTOM_BORDER,
eTOOLTIP_VERTICAL_BORDER,

eROUND_BOX_FRAME_LEFT_TOP,
eROUND_BOX_FRAME_RIGHT_TOP,
eROUND_BOX_FRAME_LEFT_BOTTOM,
eROUND_BOX_FRAME_RIGHT_BOTTOM,
eROUND_BOX_FRAME_TOP_BORDER,
eROUND_BOX_FRAME_BOTTOM_BORDER,
eROUND_BOX_FRAME_LEFT_BORDER,
eROUND_BOX_FRAME_RIGHT_BORDER,

eDIALOG_FRAME_LEFT_TOP,
eDIALOG_FRAME_RIGHT_TOP,
eDIALOG_FRAME_LEFT_BOTTOM,
eDIALOG_FRAME_RIGHT_BOTTOM,
eDIALOG_FRAME_TOP_BORDER,
eDIALOG_FRAME_BOTTOM_BORDER,
eDIALOG_FRAME_LEFT_BORDER,
eDIALOG_FRAME_RIGHT_BORDER,
eDIALOG_FRAME_ARROW,

eSTATE_UP_NORMAL,
eSTATE_UP_ACTIVE,
eSTATE_UP_PRESSED,
eSTATE_UP_DISABLE,
eSTATE_DOWN_NORMAL,
eSTATE_DOWN_ACTIVE,
eSTATE_DOWN_PRESSED,
eSTATE_DOWN_DISABLE,

eITEM_DROP_FRAME,
eITEM_SELL_FRAME,
eITEM_DROP_1_NORMAL,
eITEM_DROP_5_NORMAL,
eITEM_DROP_10_NORMAL,
eITEM_DROP_HALF_NORMAL,
eITEM_DROP_ALL_NORMAL,
eITEM_DROP_1_ACTIVE,
eITEM_DROP_5_ACTIVE,
eITEM_DROP_10_ACTIVE,
eITEM_DROP_HALF_ACTIVE,
eITEM_DROP_ALL_ACTIVE,
eITEM_PRICE_FRAME,
eITEM_COUNT_FRAME,

eACTIVE_SKILL_TAB,
eNORMAL_SKILL_TAB_NORMAL,
eNORMAL_SKILL_TAB_LIGHT,

eREACTION_SKILL_ON,
eREACTION_SKILL_OFF,
eREACTION_SKILL_OFF_LIGHT,
eREACTION_SKILL_ON_S,
eREACTION_SKILL_OFF_S,

//	Mini Map Image
eMMI_CLOSE_NORMAL,
eMMI_CLOSE_PRESSED,
eMMI_CLOSE_LIGHT,
eMMI_RESIZE_WINDOW_NORMAL,
eMMI_RESIZE_WINDOW_PRESSED,
eMMI_RESIZE_WINDOW_LIGHT,
eMMI_ZOOM_PLUS_NORMAL,
eMMI_ZOOM_PLUS_PRESSED,
eMMI_ZOOM_PLUS_LIGHT,
eMMI_ZOOM_MINUS_NORMAL,
eMMI_ZOOM_MINUS_PRESSED,
eMMI_ZOOM_MINUS_LIGHT,
eMMI_QUESTION_MARK_NORMAL,
eMMI_QUESTION_MARK_PRESSED,
eMMI_QUESTION_MARK_LIGHT,
eMMI_WORLD_MAP_NORMAL,
eMMI_WORLD_MAP_PRESSED,
eMMI_WORLD_MAP_LIGHT,

//	System Menu Window Image
eSMWI_BAR_DISABLE,
eSMWI_BAR_NORMAL,
eSMWI_BAR_ACTIVE,
eSMWI_BAR_PRESSED,

eSMWI_CHECK_BOX,
eSMWI_CHECK_BOX_CHECKED,
eSMWI_RADIO_BOX,
eSMWI_RADIO_BOX_CHECKED,

eSMWI_GAUGE,
eSMWI_FILLED_GAUGE,
eSMWI_MENU_FRAME,
eSMWI_OPTION_FRAME,

//	Trade Window Image
eTWI_FRAME,
eTWI_PERMIT_NORMAL,
eTWI_PERMIT_PRESSED,
eTWI_PERMIT_ACTIVE,
eTWI_PERMIT_DISABLE,

eTWI_CANCEL_NORMAL,
eTWI_CANCEL_PRESSED,
eTWI_CANCEL_ACTIVE,

eTWI_READY_NORMAL,
eTWI_READY_PRESSED,
eTWI_READY_ACTIVE,

eTWI_LOCKED_FRAME1,
eTWI_LOCKED_FRAME2,
eTWI_LOCKED_FRAME3,
eTWI_LOCKED_FRAME4,
eTWI_LOCKED_FRAME5,
eTWI_LOCKED_FRAME6,
eTWI_LOCKED_FRAME7,

//	Chatting Filter

eCF_NORMAL_CHATTING_DEFAULT,
eCF_PARTY_CHATTING_DEFAULT,
eCF_GUILD_CHATTING_DEFAULT,
eCF_WHISPER_CHATTING_DEFAULT,

eCF_NORMAL_CHATTING_FOCUS,
eCF_PARTY_CHATTING_FOCUS,
eCF_GUILD_CHATTING_FOCUS,
eCF_WHISPER_CHATTING_FOCUS,

eCF_NORMAL_CHATTING_SELECT,
eCF_PARTY_CHATTING_SELECT,
eCF_GUILD_CHATTING_SELECT,
eCF_WHISPER_CHATTING_SELECT,

eCF_LEFT_BORDER,
eCF_RIGHT_BORDER,

//	Bank Window
eBW_GOLD_SLOT,

//	Status Window
eSW_PERSONAL_FRAME,
eSW_ALLIGNMENT_FRAME,
eSW_ALLIGNMENT_GAUGE_ABSOLUTE_GOOD,
eSW_ALLIGNMENT_GAUGE_20,
eSW_ALLIGNMENT_GAUGE_19,
eSW_ALLIGNMENT_GAUGE_18,
eSW_ALLIGNMENT_GAUGE_17,
eSW_ALLIGNMENT_GAUGE_16,
eSW_ALLIGNMENT_GAUGE_15,
eSW_ALLIGNMENT_GAUGE_14,
eSW_ALLIGNMENT_GAUGE_13,
eSW_ALLIGNMENT_GAUGE_12,
eSW_ALLIGNMENT_GAUGE_11,
eSW_ALLIGNMENT_GAUGE_NEUTRAL,	//	중립
eSW_ALLIGNMENT_GAUGE_09,
eSW_ALLIGNMENT_GAUGE_08,
eSW_ALLIGNMENT_GAUGE_07,
eSW_ALLIGNMENT_GAUGE_06,
eSW_ALLIGNMENT_GAUGE_05,
eSW_ALLIGNMENT_GAUGE_04,
eSW_ALLIGNMENT_GAUGE_03,
eSW_ALLIGNMENT_GAUGE_02,
eSW_ALLIGNMENT_GAUGE_ABSOLUTE_EVIL,

//	Quest Window
eQW_FRAME_OLD,
eQW_LEFT_HAND,
eQW_RIGHT_HAND,
eQW_QUEST_LINE,

//	Guild Window
eGW_FRAME,

eGW_INFO_NORMAL,
eGW_SKILL_NORMAL,
eGW_ITEM_NORMAL,
eGW_MEMBER_NORMAL,
eGW_TOOL_NORMAL,
eGW_TAB_NORMAL,

eGW_INFO_ACTIVE,
eGW_SKILL_ACTIVE,
eGW_ITEM_ACTIVE,
eGW_MEMBER_ACTIVE,
eGW_TOOL_ACTIVE,
eGW_TAB_ACTIVE,

eGW_INFO_FOCUS,
eGW_SKILL_FOCUS,
eGW_ITEM_FOCUS,
eGW_MEMBER_FOCUS,
eGW_TOOL_FOCUS,

//	ETC
eETC_TEST_SERVER,
eETC_TEST_SERVER_FRAME,

//	Messge Box
eMB_TITLE_PATTERN,
eMB_TITLE_BAR_LEFT_PATTERN,
eMB_TITLE_BAR_RIGHT_PATTERN,
eMB_IMPORTANT_ICON,
eMB_WARNING_ICON,

//	Guild Battle Schedule Window
eGBSW_ACTIVE_TIME_BAR,
eGBSW_NORMAL_TIME_BAR,
eGBSW_SELECT_TIME_BAR,
eGBSW_1,
eGBSW_2,
eGBSW_3,
eGBSW_4,
eGBSW_5,
eGBSW_6,
eGBSW_7,
eGBSW_8,
eGBSW_9,
eGBSW_10,

//	Small Number
eSN_0,
eSN_1,
eSN_2,
eSN_3,
eSN_4,
eSN_5,
eSN_6,
eSN_7,
eSN_8,
eSN_9,
//	Small Number Out Line
eSNOL_0,
eSNOL_1,
eSNOL_2,
eSNOL_3,
eSNOL_4,
eSNOL_5,
eSNOL_6,
eSNOL_7,
eSNOL_8,
eSNOL_9,

//	Guild Mark Composer Window
eGMCW_DIVISION_BLOCK,
eGMCW_BASE_BLOCK,
eGMCW_SYMBOL_BLOCK,

//	Party Window Image
ePWI_HP_GAUGE1,
ePWI_HP_GAUGE2,
ePWI_HP_GAUGE3,
ePWI_HP_GAUGE4,
ePWI_HP_GAUGE5,
ePWI_HP_GAUGE6,
ePWI_HP_GAUGE7,
ePWI_HP_GAUGE_EMPTY,
ePWI_HP_GAUGE_DISABLE,
ePWI_BORDER,
ePWI_SELECT_PANNEL,
ePWI_JOB_ICON_FRAME,

//	Pitchman Shop Image
ePSI_SIGNBOARD_SHAPE_NORMAL,
ePSI_SIGNBOARD_SHAPE_ACTIVE,
ePSI_SIGNBOARD_SHAPE_PRESSED,
ePSI_SIGNBOARD_SHAPE_DISABLE,
ePSI_TEXT_COLOR_NORMAL,
ePSI_TEXT_COLOR_ACTIVE,
ePSI_TEXT_COLOR_PRESSED,
ePSI_TEXT_COLOR_DISABLE,
ePSI_BOLD_NORMAL,
ePSI_BOLD_ACTIVE,
ePSI_BOLD_PRESSED,
ePSI_BOLD_DISABLE,
ePSI_EFFECT_NORMAL,
ePSI_EFFECT_ACTIVE,
ePSI_EFFECT_PRESSED,
ePSI_EFFECT_DISABLE,
ePSI_SIGNBOARD_SHAPE,
ePSI_TEXT_COLOR,

//	
eCII_CHATTING_INPUT,

//	Tamed Monster Image
eTMWI_PET_PANNEL_VALID,
eTMWI_PET_PANNEL_UNDEAD,
eTMWI_PET_PANNEL_HUMAN,
eTMWI_PET_PANNEL_DEMON,
eTMWI_PET_PANNEL_ANIMAL,
eTMWI_PET_PANNEL_HOLY_BEAST,
eTMWI_PET_ICON_UNDEAD,
eTMWI_PET_ICON_HUMAN,
eTMWI_PET_ICON_DEMON,
eTMWI_PET_ICON_ANIMAL,
eTMWI_PET_ICON_HOLY_BEAST,

eTMWI_SUMMON_BEAST_PANNEL_FIRE,
eTMWI_SUMMON_BEAST_PANNEL_WATER,
eTMWI_SUMMON_BEAST_PANNEL_WIND,
eTMWI_SUMMON_BEAST_PANNEL_EARTH,
eTMWI_SUMMON_BEAST_ICON_FIRE,
eTMWI_SUMMON_BEAST_ICON_WATER,
eTMWI_SUMMON_BEAST_ICON_WIND,
eTMWI_SUMMON_BEAST_ICON_EARTH,

eTMWI_RED_GAGUGE,
eTMWI_GRAY_GAGUGE,

eCII_CHATTING_INPUT_UNLOCK_ACTIVE,
eCII_CHATTING_INPUT_UNLOCK_NORMAL,
eCII_CHATTING_INPUT_LOCK_ACTIVE,
eCII_CHATTING_INPUT_LOCK_NORMAL,

eIWI_WEAPON_JOB9_1,			// 영술사 무기..

// PetWindow Icon			// 10.02.19
ePWI_PET_ICON_LEVEL,
ePWI_PET_ICON_EXP,
ePWI_PET_ICON_ATTACK_POWER,
ePWI_PET_ICON_DEFENSE_POWER,
ePWI_PET_ICON_LOYALTY,
ePWI_PET_ICON_FEEDING_RED_PEPPER,
ePWI_PET_ICON_BREEDING_TIME,
ePWI_PET_ICON_RANK,

// Tamed Monster Icon Edit Version
eTMWI_PET_ICON_UNDEAD2,
eTMWI_PET_ICON_HUMAN2,
eTMWI_PET_ICON_DEMON2,
eTMWI_PET_ICON_ANIMAL2,
eTMWI_PET_ICON_HOLY_BEAST2,
};

enum
{	//	interface2
eSHORT_GREEN_Q = 2,
eSHORT_GREEN_W,
eSHORT_GREEN_E,
eSHORT_GREEN_R,
eSHORT_GREEN_T,
eSHORT_GREEN_A,
eSHORT_GREEN_S,
eSHORT_GREEN_D,
eSHORT_GREEN_F,
eSHORT_GREEN_G,

eSHORT_RED_Q,
eSHORT_RED_W,
eSHORT_RED_E,
eSHORT_RED_R,
eSHORT_RED_T,
eSHORT_RED_A,
eSHORT_RED_S,
eSHORT_RED_D,
eSHORT_RED_F,
eSHORT_RED_G,

eFWI_PLUS				=	116,
eFWI_MINUS,
eJOB_SMALL_ICON_KNIGHT,	
eJOB_SMALL_ICON_WARRIOR,
eJOB_SMALL_ICON_WIZARD,
eJOB_SMALL_ICON_WEREWOLF,
eJOB_SMALL_ICON_FALLEN_ANGEL,
eJOB_SMALL_ICON_ROGUE,
eJOB_SMALL_ICON_FIGHTER,
eJOB_SMALL_ICON_MAGIC_LANCER,
eJOB_SMALL_ICON_MAGIC_ARCHER,
eJOB_SMALL_ICON_BEAST_TAMER,
eJOB_SMALL_ICON_SUMMONER,
eJOB_SMALL_ICON_PRINCESS,
eJOB_SMALL_ICON_MAGICAL_GIRL,
eJOB_SMALL_ICON_NECROMANCER,
eJOB_SMALL_ICON_DEVIL,

eJOB_SMALL_ICON_SOUL_BRINGER = 205,
eJOB_SMALL_ICON_CHAMPION	,

eIWI_WEAPON_JOB9_2,

eI2_SMALL_OVAL		=	243,
eCARROT_MAINWND_TITLE ,
eCARROT_MAINWND_BORDER,
eCARROT_MAINWND_DIVIDELINE,

eCARROT_MAGNIFIER,
eCARROT_SEARCHBOX,
eCARROT_SEARCHBOX_RESULT,
eCARROT_SEARCHBOX_SELECT,

eCARROT_TOPBTN_NORMAL,
eCARROT_TOPBTN_UP,
eCARROT_TOPBTN_CLICK,
eCARROT_TOPBTN_NOTUSE,

eCARROT_SECLBTN1NORMAL,
eCARROT_SECLBTN_UP,
eCARROT_SECLBTN_CLICK,
eCARROT_SECLBTN_NOTUSE,

eCARROT_SECSBTN1NORMAL,
eCARROT_SECSBTN_UP,
eCARROT_SECSBTN_CLICK,
eCARROT_SECSBTN_NOTUSE,

eCARROT_ITEMSBTN_NORMAL,
eCARROT_ITEMSBTN_UP,
eCARROT_ITEMSBTN_CLICK,
eCARROT_ITEMSBTN_NOTUSE,

eCARROT_ITEMLBTN_NORMAL,
eCARROT_ITEMLBTN_UP,
eCARROT_ITEMLBTN_CLICK,
eCARROT_ITEMLBTN_NOTUSE,

eCARROT_ITEMWND_BORDER,
eCARROT_ITEMWND_DIVIDELINE,
eCARROT_WISHLIST_DELETE,

eCARROT_HOT_ICON1,
eCARROT_HOT_ICON2,
eCARROT_HOT_ICON3,

eWINDOW_CLOSE_NORMAL,

eMINIMAP_ARROW_RIGHT_UP ,
eMINIMAP_ARROW_RIGHT_DOWN,
eMINIMAP_ARROW_LEFT_UP,
eMINIMAP_ARROW_LEFT_DOWN,
eMINIMAP_ARROW_LEFT,
eMINIMAP_ARROW_RIGHT,
eMINIMAP_ARROW_UP,
eMINIMAP_ARROW_DOWN,

eMMI_QUESTLIST_NORMAL,
eMMI_QUESTLIST_PRESSED,
eMMI_QUESTLIST_LIGHT,
eMMI_FOGMAP_NORMAL,
eMMI_FOGMAP_PRESSED,
eMMI_FOGMAP_LIGHT,
eIWI_WEAPON_JOB10_1,
eJOB_SMALL_ICON_OPTICALIST,
eMMI_MINIMAP_OPTION_NORMAL,
eMMI_MINIMAP_OPTION_PRESSED,
eMMI_MINIMAP_OPTION_LIGHT,
};


//Greate God Greace Icon
enum
{
eGGG_ICON_FIRE,
eGGG_ICON_WATER,
eGGG_ICON_WIND,
eGGG_ICON_EARTH,
eGGG_ICON_LIGHT,
eGGG_ICON_DARK,
eGGG_ICON_FIRE_LEVEL,
eGGG_ICON_FIRE_SKILL,
eGGG_ICON_FIRE_PARTY,
};
// 10.02.18
// Title Image
enum
{
	eTI_ICON_CHIVALRY,				// 기사도
	eTI_ICON_SWORDSMANSHIP,			// 검술
	eTI_ICON_WIZARDRY,				// 위저드리
	eTI_ICON_LYCANTROPHY,			// 라이칸 트로피
	eTI_ICON_FANATICISM,			// 광신
	eTI_ICON_ANGELRANK,				// 천사계급학
	eTI_ICON_KEYMANAFACTURING,		// 열쇠 제조업
	eTI_ICON_HANDICRAFTSMAN,		// 기공술
	eTI_ICON_RECPMMAOSSANCE,		// 정찰술
	eTI_ICON_TACTICS,				// 용병술
	eTI_ICON_PALEOGRAPHY,			// 고문학
	eTI_ICON_THREMMATOLOGY,			// 사육학
	eTI_ICON_COURTESY,				// 궁정예법
	eTI_ICON_ASTRONOMY,				// 천문학
	eTI_ICON_SPIRITISM,				// 강신술
	eTI_ICON_DEVIL,					// 악마술
	eTI_ICON_PSYCHIC,				// 심령술
	eTI_ICON_PIONEER,				// 선구자
	eTI_ICON_CITIZEN,				// 시민
	eTI_ICON_NOVICE,				// 초보자
	eTI_ICON_MONSTERSEXER,			// 몬스터 감별사
	eTI_ICON_BANK_CUSTOMER,			// 은행고객
	eTI_ICON_MAPMAKER,				// 맵 제작자
	eTI_ICON_PORTER,				// 짐꾼
	eTI_ICON_INSTINCTFORSURVIVAL,	// 생존 본능
	eTI_ICON_BROKER,				// 거래인
	eTI_ICON_HONORMEMBER,			// 명예의원
	eTI_ICON_PHAMRMACIST,			// 약사
	eTI_ICON_CHARMING,				// 애교
	eTI_ICON_CAMPING_MASTER,		// 캠핑마스터
	eTI_ICON_CITYWALKER,			// 시티 워커
	eTI_ICON_ALCHEMY,				// 연금술
	eTI_ICON_REDEYE_MEMBER,			// 레드아이 단원
	eTI_ICON_ORPHIC,				// 밀교
	eTI_ICON_JEWELY_MASTER,			// 보석 감정사
	eTI_ICON_REDSTONE_HUNTER,		// 붉은 보석 사냥꾼
	eTI_ICON_CAVETHEFT,				// 우수 동굴 도둑
	eTI_ICON_CHROMATIC_HONORMEMBER,	// 크로매틱 명예 대원
	eTI_ICON_RED_STONE_AGENT	,	// 붉은 보석 탐정
	eTI_ICON_BARD			,	// 영혼의 연주자
	eTI_ICON_INFIGHTER		,	//	인파이터
	eTI_ICON_OPTICAL		,	//	광학
	eTI_ICON_END,
};
//
//	Name Bar Image
enum
{
	eNBI_BLACK_LEFT,
	eNBI_BLACK_RIGHT,
	eNBI_BLACK_BODY,

	eNBI_GREEN_LEFT,
	eNBI_GREEN_RIGHT,
	eNBI_GREEN_BODY,

	eNBI_RED_LEFT,
	eNBI_RED_RIGHT,
	eNBI_RED_BODY,

	eNBI_BLUE_LEFT,
	eNBI_BLUE_RIGHT,
	eNBI_BLUE_BODY,

	eNBI_GRAY_LEFT,
	eNBI_GRAY_RIGHT,
	eNBI_GRAY_BODY,

	eNBI_ORANGE_LEFT,
	eNBI_ORANGE_RIGHT,
	eNBI_ORANGE_BODY,

	eNBI_RED_LEFT_L,
	eNBI_RED_RIGHT_L,
	eNBI_RED_BODY_L,

	eNBI_GRAY_LEFT_L,
	eNBI_GRAY_RIGHT_L,
	eNBI_GRAY_BODY_L,

	eNBI_BLACK_LEFT_L,
	eNBI_BLACK_RIGHT_L,
	eNBI_BLACK_BODY_L,

};

extern	cANM*	GetBody(int _iBody);
extern	cANM*	GetMonsterVariation(int _iBody,int _iVariation,int _iParts=0);

inline	cANM*
GetWeapon(int _iBody,int _iShape)
{
	return	(cANM *)g_apWeapon[_iBody][_iShape];
}

extern	cMonsterBodyLoadInfo	g_aMonsterBodyLoadInfo[100];
extern	BOOL		g_bIsPutSceneWhenLoading;
extern	WORD*		g_pRedDrakePalette;
extern	WORD*		g_pRebirthPalette;
extern	WORD*		g_pRebirthBallPalette;
extern	int		g_iWorldMapJobIconIndex[dPLAYER_JOB_COUNT];
#define	dETC_WND_TITLE_BAR_SPRITE_INDEX	66

#endif
