/********************************************************************
	created:	2002/04/20
	created:	20:4:2002   9:52
	filename: 	C:\Work\Project Red Stone\Red Stone\cPACKET.h
	file path:	C:\Work\Project Red Stone\Red Stone
	file base:	cPACKET
	file ext:	h
	author:		이영찬
	
	purpose:	패킷 정의.. 후.. 후후후...
*********************************************************************/

//	패킷은 워드형이다 그러니까... 0xffff가 넘는 수치로 정의 할 수 없다.
//	const WORD 로 선언했다가 바꿨는데... 그 이유는...
//	visual assist에서 #define 으로 선언된 것은 매크로로 인색해서 색칠-_-을 해주는데..
//	const 로 선언된건 색칠을 안해준다. 그래서... 그랬다. 머... 그랬다고... 그랬다고... 그랬는데... 그랬어... 랬어... 어... ;;;

#ifndef _classPACKET_H
#define _classPACKET_H

#include "cPACKET_GAMESERVER.h"
#include "cPACKET_WORLDSERVER.h"
#include "cPACKET_BCSERVER.h"

#define	dMAX_SERVER_PACKET_COUNT					0x0440
#define	dPACKET_INDEX_BEGIN							dSL_RESULT_LOGIN

#pragma pack(1)

struct SG_MAX_BUFFER
{
	char	aBuffer[4096];
};						

union	SERVER_PACKETS
{
	cMSG_BASE_TYPE							base;	//	기본 패킷
	SG_MAX_BUFFER							mSG_MAX_BUFFER;

//┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┃로그인 서버
	SL_RESULT_LOGIN							mSL_RESULT_LOGIN;		//	연결 종료
	SL_SERVER_LIST							mSL_SERVER_LIST;
	SL_AVATAR_LIST							mSL_AVATAR_LIST;
	SL_RESULT_CREATE_AVATAR					mSL_RESULT_CREATE_AVATAR;
	SL_RESULT_REMOVE_AVATAR					mSL_RESULT_REMOVE_AVATAR;
	SL_RESULT_SELECT_AVATAR					mSL_RESULT_SELECT_AVATAR;
//┃로그인 서버
//┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

//┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┃게임서버
	SG_OUT									mSG_OUT;
	SG_RESULT_CONNECT						mSG_RESULT_CONNECT;
	SG_RESULT_JOIN							mSG_RESULT_JOIN;
	SG_JOIN_PLAYER							mSG_JOIN_PLAYER;
	SG_PLAYER_OUT							mSG_PLAYER_OUT;
	SG_MINIMUM_ACTOR_INFO_LIST				mSG_MINIMUM_ACTOR_INFO_LIST;
	SG_OPERATOR_LIST						mSG_OPERATOR_LIST;
	SG_REFIT_ACTORS_POSITION				mSG_REFIT_ACTORS_POSITION;
	SG_OUTER_ACTORS_POS_UPDATE				mSG_OUTER_ACTORS_POS_UPDATE;
	SG_EVENT_NPC_LIST						mSG_EVENT_NPC_LIST;

	SG_REGEN_MONSTER						mSG_REGEN_MONSTER;

	SG_MOVE									mSG_MOVE;
	SG_MOVE_RESULT							mSG_MOVE_RESULT;
	SG_MOVE_FAILED							mSG_MOVE_FAILED;
	SG_SET_MOVE_ABILITY						mSG_SET_MOVE_ABILITY;
	SG_TRANSFORMATION						mSG_TRANSFORMATION;
	SG_TRANSFORMATION_FAILED				mSG_TRANSFORMATION_FAILED;
	SG_TOGGLE_SITDOWN						mSG_TOGGLE_SITDOWN;
	SG_SITDOWN_RESULT						mSG_SITDOWN_RESULT;//	앉기/서기 결과
	SG_CORRECT_PLAYER_POSITION				mSG_CORRECT_PLAYER_POSITION;
	SG_STOP									mSG_STOP;
	SG_ACTION_TO_ACTOR						mSG_ACTION_TO_ACTOR;
	SG_ACTION_TO_GROUND						mSG_ACTION_TO_GROUND;
	SG_BASIC_ATTACK							mSG_BASIC_ATTACK;
	SG_CONTINUOUS_HIT_BY_CHARACTER			mSG_CONTINUOUS_HIT_BY_CHARACTER;
	SG_CONTINUOUS_HIT_BY_VALUE				mSG_CONTINUOUS_HIT_BY_VALUE;
	SG_LAND_MARKER							mSG_LAND_MARKER;
	SG_STRIKE_INTERVAL_SHOOTER				mSG_STRIKE_INTERVAL_SHOOTER;
	SG_CAST_INTERVAL_SHOOTER				mSG_CAST_INTERVAL_SHOOTER;
	SG_GUARDIAN_POST						mSG_GUARDIAN_POST;
	SG_BUNSHINE_ATTACK						mSG_BUNSHINE_ATTACK;
	SG_SCIMITAR_CUTTING						mSG_SCIMITAR_CUTTING;
	SG_QUICK_ACTION							mSG_QUICK_ACTION;
	SG_WIDE_AREA_DAMAGE						mSG_WIDE_AREA_DAMAGE;
	SG_USE_SKILL_RESULT						mSG_USE_SKILL_RESULT;
	SG_KILL									mSG_KILL;
	SG_UPDATE_EXP							mSG_UPDATE_EXP;
	SG_UPDATE_BASIC_INFORMATION				mSG_UPDATE_BASIC_INFORMATION;
	SG_REMOVE_ACTOR							mSG_REMOVE_ACTOR;
	SG_LEVEL_UP								mSG_LEVEL_UP;
	SG_LEVEL_UP_OTHER						mSG_LEVEL_UP_OTHER;
	SG_CHANGE_STATE_RESULT					mSG_CHANGE_STATE_RESULT;
	SG_INCREASE_ABILITY_LEVEL				mSG_INCREASE_ABILITY_LEVEL;
	SG_SET_REACTION_STATUS					mSG_SET_REACION_STATUS;
	SG_HIT_THORN_DAMAGE						mSG_HIT_THORN_DAMAGE;
	SG_ABSORB_DAMAGE						mSG_ABSORB_DAMAGE;
	SG_CHANGE_SPECIAL_SKILL_FIELD			mSG_CHANGE_SPECIAL_SKILL_FIELD;
	SG_RELEASE_SHIMMERING_SHIELD			mSG_RELEASE_SHIMMERING_SHIELD;
	SG_ICY_STALAGMITE						mSG_ICY_STALAGMITE;
	SG_ACTOR_ENCHANTED_STATUS				mSG_ACTOR_ENCHANTED_STATUS;
	SG_TELEPORT								mSG_TELEPORT;
	SG_APPLY_SKILL_EXTRA_EFFECT				mSG_APPLY_SKILL_EXTRA_EFFECT;
	SG_ACTIVE_SKILL_EFFECT					mSG_ACTIVE_SKILL_EFFECT;
	SG_FIND_USER_RESULT						mSG_FIND_USER_RESULT;
	SG_SIMPLE_HIT							mSG_SIMPLE_HIT;
	SG_REGEN_HP_BY_AID_SKILL				mSG_REGEN_HP_BY_AID_SKILL;
	SG_EXIT_GAME_SUCCESS					mSG_EXIT_GAME_SUCCESS;
	SG_REGIST_MESSAGE						mSG_REGIST_MESSAGE;
	SG_HIT_ACTION							mSG_HIT_ACTION;
	SG_SET_SHIMMERING_SHIELD				mSG_SET_SHIMMERING_SHIELD;
	SG_CURE_ACTOR							mSG_CURE_ACTOR;
	SG_FLOAT_MACHINE						mSG_FLOAT_MACHINE;
	SG_RELEASE_MACHINE						mSG_RELEASE_MACHINE;
	SG_SHOOT_MACHINE_MISSILE				mSG_SHOOT_MACHINE_MISSILE;
	SG_FIRE_TAIL_CHASER						mSG_FIRE_TAIL_CHASER;
	SG_TURN_ON_PASSIVE_SKILL				mSG_TURN_ON_PASSIVE_SKILL;
	
	SG_MAKE_ACTION_FORM						mSG_MAKE_ACTION_FORM;
	SG_THRUST_ACTORS						mSG_THRUST_ACTORS;
	SG_USE_SKILL_TO_ACTOR					mSG_USE_SKILL_TO_ACTOR;
	SG_USE_SKILL_TO_GROUND					mSG_USE_SKILL_TO_GROUND;
	SG_CREATE_DUMMY							mSG_CREATE_DUMMY;
	SG_RELEASE_DUMMY						mSG_RELEASE_DUMMY;
	SG_RECEIVE_AID_MAGIC					mSG_RECEIVE_AID_MAGIC;
	SG_CHARGE_CP							mSG_CHARGE_CP;
	SG_HIT_AURA_SKILL						mSG_HIT_AURA_SKILL;
	SG_MESSAGE								mSG_MESSAGE;
	SG_REMAIN_HP							mSG_REMAIN_HP;
	SG_THRUST								mSG_THRUST;
	SG_RUSH									mSG_RUSH;
	SG_ACTIVE_REACTION_SKILL				mSG_ACTIVE_REACTION_SKILL;
	SG_HIDE_EQUIPMENT						mSG_HIDE_EQUIPMENT;

//━은행
	SG_OPEN_BANK							mSG_OPEN_BANK;
	SG_BANK_MESSAGE							mSG_BANK_MESSAGE;
	SG_STORE_ITEM_TO_THE_BANK				mSG_STORE_ITEM_TO_THE_BANK;
	SG_STORE_GOLD_TO_THE_BANK				mSG_STORE_GOLD_TO_THE_BANK;
	SG_WITHDRAW_ITEM_FROM_THE_BANK			mSG_WITHDRAW_ITEM_FROM_THE_BANK;
	SG_WITHDRAW_GOLD_FROM_THE_BANK			mSG_WITHDRAW_GOLD_FROM_THE_BANK;
	SG_MOVE_BANK_ITEM						mSG_MOVE_BANK_ITEM;
	SG_MOVE_INVENTORY_ITEM_WHEN_BANK_TRANSACTION	mSG_MOVE_INVENTORY_ITEM_WHEN_BANK_TRANSACTION;

//━커뮤니티
	SG_CHAT									mSG_CHAT;
	SG_CHAT_FAILED							mSG_CHAT_FAILED;
	SG_SAY_RESULT							mSG_SAY_RESULT;

	//파티 연합 관련
	SG_ASK_JOIN_UNION_PARTY					mSG_ASK_JOIN_UNION_PARTY;
	SG_UNION_PARTY_WORK						mSG_UNION_PARTY_ETC_INFO;
	SG_UNION_PARTY_MEMBER_INFO				mSG_UNION_PARTY_MEMBER_INFO;
	SG_UNION_PARTY_INFO						mSG_UNION_PARTY_INFO;

	SG_PARTY_LIST							mSG_PARTY_LIST;//	파티리스트 전송
	SG_PARTY_INFO							mSG_PARTY_INFO;//	파티멤버에게 보내는 파티 정보(파티원 리스트나 기타등등)
	SG_ASK_JOIN_PARTY						mSG_ASK_JOIN_PARTY;//	파티 참가 요청
	SG_JOIN_PARTY_MEMBER					mSG_JOIN_PARTY_MEMBER;//	파티 멤버 추가
	SG_PARTY_WORK							mSG_PARTY_WORK;//	누군가 파티에서 탈퇴 했다.(거나 쫏겨 났거나.. -_-a)
	SG_UPDATE_PARTY_MEMBER_INFO				mSG_UPDATE_PARTY_MEMBER_INFO;//	파티 멤버 정보를 업데이트(체력정도..)
	SG_CHANGE_PARTY_NAME					mSG_CHANGE_PARTY_NAME;//	파티 멤버 정보를 업데이트(체력정도..)
	SG_PARTY_MESSAGE						mSG_PARTY_MESSAGE;//	파티와 관련된 이런저런 메시지(넌 리더가 아냐!!,넌 파티에 속해 있지 않아!!,파티 풀~ 등등등..)
	SG_EVENT_NOTICE							mSG_EVENT_NOTICE;
	SG_GET_TITLE							mSG_GET_TITLE;
	SG_REMOVE_TITLE							mSG_REMOVE_TITLE;
	SG_REQUEST_ADD_FRIEND					mSG_REQUEST_ADD_FRIEND;
	SG_REPLY_FOR_ADD_FRIEND					mSG_REPLY_FOR_ADD_FRIEND;
	SG_CANCEL_QUEST							mSG_CANCEL_QUEST;

	SG_QUIZ_EVENT_QUESTION					mSG_QUIZ_EVENT_QUESTION;
	SG_OX_QUIZ_RESULT						mSG_OX_QUIZ_RESULT;
	SG_END_QUIZ_EVENT						mSG_END_QUIZ_EVENT;
	SG_START_COUNTDOWN						mSG_START_COUNTDOWN;
	SG_ANNOUNCE_QUIZ_EVENT					mSG_ANNOUNCE_QUIZ_EVENT;
	SG_QUIZ_EVENT_LOSER_LIST				mSG_QUIZ_EVENT_LOSER_LIST;
	SG_CANCEL_QUIZ_EVENT					mSG_CANCEL_QUIZ_EVENT;
	SG_OX_QUIZ_SURVIVOR_COUNT				mSG_OX_QUIZ_SURVIVOR_COUNT;
	SG_OX_QUIZ_LOSER_REVIVE_BATTLE			mSG_OX_QUIZ_LOSER_REVIVE_BATTLE;
	SG_OX_QUIZ_WINNER_LIST					mSG_OX_QUIZ_WINNER_LIST;

//━쇼핑 카트 열기
	SG_OPEN_CART							mSG_OPEN_CART;
	SG_CART_MESSAGE							mSG_CART_MESSAGE;//	서버에서 은행 데이터를 기다린다.
	SG_WITHDRAW_ITEM_FROM_THE_CART			mSG_WITHDRAW_ITEM_FROM_THE_CART;
	SG_LOAD_FAILED_CART_PREMIUM_ITEM		mSG_LOAD_FAILED_CART_PREMIUM_ITEM;
	SG_DESTROY_CART_ITEM_RESULT				mSG_DESTROY_CART_ITEM_RESULT;

//━길드 관련
	SG_OPEN_GUILD_BATTLE_SCHEDULER			mSG_OPEN_GUILD_BATTLE_SCHEDULER;
	SG_OPEN_GUILD_MARK_COMPOSER				mSG_OPEN_GUILD_MARK_COMPOSER;
	SG_GUILD_BATTLE_SCHEDULE_IN_SAME_TIME	mSG_GUILD_BATTLE_SCHEDULE_IN_SAME_TIME;
	SG_CHANGE_GUILD_BATTLE_SCHEDULE			mSG_CHANGE_GUILD_BATTLE_SCHEDULE;
	SG_UPDATE_GUILD_BATTLE_COUNT_AT_THIS_WEEK	mSG_UPDATE_GUILD_BATTLE_COUNT_AT_THIS_WEEK;
	SG_READY_TO_NEXT_GUILD_BATTLE			mSG_READY_TO_NEXT_GUILD_BATTLE;
	SG_GUILD_BATTLE_RESULT					mSG_GUILD_BATTLE_RESULT;
	
	SG_READY_TO_MAKE_GUILD					mSG_READY_TO_MAKE_GUILD;
	SG_MAKE_GUILD_RESULT					mSG_MAKE_GUILD_RESULT;
	SG_BASE_GUILD_INFO						mSG_BASE_GUILD_INFO;
	SG_DISSOLUTION_GUILD					mSG_DISSOLUTION_GUILD;
	SG_ASK_JOIN_GUILD_RESULT				mSG_ASK_JOIN_GUILD_RESULT;
	SG_ASK_JOIN_GUILD						mSG_ASK_JOIN_GUILD;
	SG_JOIN_GUILD							mSG_JOIN_GUILD;
	SG_EXIT_GUILD							mSG_EXIT_GUILD;
	SG_UPDATE_GUILD_LEVEL					mSG_UPDATE_GUILD_LEVEL;
	SG_GUILD_WORK_MESSAGE					mSG_GUILD_WORK_MESSAGE;
	SG_CHANGE_GUILD_TAX_RATE				mSG_CHANGE_GUILD_TAX_RATE;
	SG_CHANGE_GUILD_NOTICE					mSG_CHANGE_GUILD_NOTICE;
	SG_CHANGE_RANK_IN_GUILD					mSG_CHANGE_RANK_IN_GUILD;
	SG_UPDATE_GUILD_MEMBER					mSG_UPDATE_GUILD_MEMBER;
	SG_REMOVE_GUILD_MEMBER					mSG_REMOVE_GUILD_MEMBER;
	SG_UPDATE_GUILD_SKILL_LEVEL				mSG_UPDATE_GUILD_SKILL_LEVEL;
	SG_CHANGE_GUILD_MARK					mSG_CHANGE_GUILD_MARK;

//━필드 이동
	SG_MOVE_FIELD_RESULT					mSG_MOVE_FIELD_RESULT;

//━아이템 관련
	SG_DROPPING_ITEMS						mSG_DROPPING_ITEMS;
	SG_DROPPING_ITEM						mSG_DROPPING_ITEM;
	SG_STRIP_EQUIPMENT						mSG_STRIP_EQUIPMENT;
	SG_STRIP_EQUIPMENT_RESULT				mSG_STRIP_EQUIPMENT_RESULT;
	SG_REMOVE_DROPPED_ITEMS					mSG_REMOVE_DROPPED_ITEMS;
	SG_REMOVE_DROPPED_ITEM					mSG_REMOVE_DROPPED_ITEM;

	SG_CHANGE_DROPPED_ITEM_INFO				mSG_CHANGE_DROPPED_ITEM_INFO;
	SG_PICK_ITEM_RESULT						mSG_PICK_ITEM_RESULT;
	SG_PCIK_PARTY_GOLD						mSG_PCIK_PARTY_GOLD;
	SG_PCIK_PARTY_ITEM						mSG_PCIK_PARTY_ITEM;
	SG_EQUIP_ITEM_RESULT					mSG_EQUIP_ITEM_RESULT;
	SG_RELOAD_BELT_ITEM						mSG_RELOAD_BELT_ITEM;
	SG_BELT_ITEM_RELOAD_RESULT				mSG_BELT_ITEM_RELOAD_RESULT;
	SG_USE_ITEM_RESULT						mSG_USE_ITEM_RESULT;
	SG_LOTTERY_TICKET_PRIZE_WINNING			mSG_LOTTERY_TICKET_PRIZE_WINNING;
	SG_USE_BELT_ITEM_RESULT					mSG_USE_BELT_ITEM_RESULT;
	SG_USE_ITEM_TO_ITEM_RESULT				mSG_USE_ITEM_TO_ITEM_RESULT;
	SG_USE_ITEM								mSG_USE_ITEM;
	SG_ITEM_DATA							mSG_ITEM_DATA;
	SG_EQUIPMENT_DATA						mSG_EQUIPMENT_DATA;
	SG_INVENTORY_DATA						mSG_INVENTORY_DATA;
	SG_CHANGE_APPEARANCE					mSG_CHANGE_APPEARANCE;
	SG_DROP_ITEM_RESULT						mSG_DROP_ITEM_RESULT;
	SG_CHANGE_ITEM_PLACE_RESULT				mSG_CHANGE_ITEM_PLACE_RESULT;
	SG_DECREASE_ITEM_COUNT					mSG_DECREASE_ITEM_COUNT;
	SG_ADD_ITEM								mSG_ADD_ITEM;
	SG_REMOVE_ITEM							mSG_REMOVE_ITEM;
	SG_ADD_GOLD								mSG_ADD_GOLD;
	SG_SET_ITEM_UNIQUE_SERIAL				mSG_SET_ITEM_UNIQUE_SERIAL;
	SG_UPDATE_ITEM_DATA						mSG_UPDATE_ITEM_DATA;
	SG_UPDATE_WAY_POINT_INFO				mSG_UPDATE_WAY_POINT_INFO;
	SG_CURE_ACTOR_BY_POTION					mSG_CURE_ACTOR_BY_POTION;
	SG_EXPIRED_ITEM							mSG_EXPIRED_ITEM;
	SG_EXPIRED_ITEM_LIST					mSG_EXPIRED_ITEM_LIST;
	SG_USE_ORB_RESULT						mSG_USE_ORB_RESULT;
	SG_DESTROY_ITEM_RESULT					mSG_DESTROY_ITEM_RESULT;

//━트레이드 관련
	SG_REQUEST_TRADE						mSG_REQUEST_TRADE;
	SG_REQUEST_TRADE_RESULT					mSG_REQUEST_TRADE_RESULT;
	SG_BEGIN_TRADE							mSG_BEGIN_TRADE;
	SG_ADD_TRADE_ITEM_BY_ME					mSG_ADD_TRADE_ITEM_BY_ME;
	SG_ADD_TRADE_ITEM_BY_TRADE_MATE			mSG_ADD_TRADE_ITEM_BY_TRADE_MATE;
	SG_CHANGE_TRADE_ITEM_DATA_BY_ME			mSG_CHANGE_TRADE_ITEM_DATA_BY_ME;
	SG_CHANGE_TRADE_ITEM_DATA_BY_TRADE_MATE	mSG_CHANGE_TRADE_ITEM_DATA_BY_TRADE_MATE;
	SG_SET_TRADE_GOLD						mSG_SET_TRADE_GOLD;
	SG_REMOVE_TRADE_ITEM					mSG_REMOVE_TRADE_ITEM;
	SG_READY_TRADE							mSG_READY_TRADE;
	SG_PERMIT_TRADE							mSG_PERMIT_TRADE;
	SG_TRADE								mSG_TRADE;
	SG_TRADE_MESSAGE						mSG_TRADE_MESSAGE;

//━이벤트 관련
	SG_COMPLEX_SPEECH						mSG_COMPLEX_SPEECH;
	SG_EVENT_FAILED							mSG_EVENT_FAILED;
	SG_END_DIAOLG							mSG_END_DIAOLG;
	SG_OPEN_SHOP							mSG_OPEN_SHOP;
	SG_BUY_ITEM								mSG_BUY_ITEM;
	SG_FAILED_BUY_ITEM						mSG_FAILED_BUY_ITEM;
	SG_SELL_ITEM							mSG_SELL_ITEM;
	SG_FAILED_SELL_ITEM						mSG_FAILED_SELL_ITEM;
	SG_QUEST_INFO							mSG_QUEST_INFO;
	SG_CHANGE_QUEST_INFO					mSG_CHANGE_QUEST_INFO;
	SG_DAMAGE_TO_ACTOR_BY_KARMA				mSG_DAMAGE_TO_ACTOR_BY_KARMA;

//━기타 메시지
	SG_WARNING_MESSAGE						mSG_WARNING_MESSAGE;
	SG_CONTROL_MONSTER						mSG_CONTROL_MONSTER;

//┃게임서버
//┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

};	//	union	ALL_MSG

#pragma pack()

#endif