#ifndef _classWindowInterface_h
#define	_classWindowInterface_h

#include "CMakeGuildWindow.H"
#include "CGuildMarkComposer.H"
#include "CGuildWindow.H"
#include "CBankWindow.H"
#include "CCartWindow.H"
#include "CSkillWindow.H"
#include "CGuildBattleScheduler.h"
#include "CPartyWindow.h"
#include "CShopWindow.h"
#include "CPitchmanShopWindow.h"
#include "CDebugWindow.h"
#include "CQuestWindow.h"
#include "CRepairItemWindow.h"
#include "CSelectVillageWindow.h"
#include "CWorldMap.h"
#include "CPetWindow.h"
#include "helpScreen.h"
#include "easySkillTree.h"
#include "carrotShop.h"
#include "removePrefixWnd.h"
#include "mergeItemWnd.h"
#include "judgeToItemWnd.h"
#include "putBanner.h"
#include "bottomless_box_gpw.h"
#include "main_quest_event.h"
#include "book_gpw.h"
#include "cFriendWindow.h"
#include "guild_hall_list.h"
#include "guild_inventory.h"
#include "guild_feed_pet_window.h"
#include "guild_related_place_list.h"
#include "guild_honor_point_list.h"
#include "selectItemInPack.h"
#include "miniPetWindow.h"
#include "listWindow.h"
#include "CUpgradeShop.h"//09.08.27 강화 차아아앙ㅇ
#include "cCopyOrCutPrefixWnd.h"	// 복사창..
#endif