#ifndef _classKARMA_KEYWORD_H
#define	_classKARMA_KEYWORD_H

#include "cDECODER.H"

class	cKARMA_ITEM
{
public:
	char	m_strName[64];
	WORD	m_wSerial;
	char	m_strReferenceText[256];
};


extern	cKARMA_ITEM		g_aTrigger[200];
extern	cKARMA_ITEM		g_aReaction[200];
extern	cKEYWORD_ITEM	g_aKarmaText[200];


enum
{
	eKARMA_KW_SPIN			,
	eKARMA_KW_EQUAL			,		//	이상이다. 이하이다. 이다.
	eKARMA_KW_SKILL			,		//	마법 리스트
	eKARMA_KW_POWER			,		//	캐릭터의 능력치
	eKARMA_KW_ITEM			,
	eKARMA_KW_STRING		,
	eKARMA_KW_NUMBER		,
	eKARMA_KW_HERO_JOB		,
	eKARMA_KW_ALLIGNMENT	,
	eKARMA_KW_GUILD_ITEM	,	//	길드 아이템
	eKARMA_KW_TITLE			,	//	타이틀
	eKARMA_KW_GUILD_TITLE	,	//	길드내 직위
	eKARMA_KW_QUEST_OWN		,	//	퀘스트 보유 여부
	eKARMA_KW_QUEST_COMPLETE,	//	퀘스트 완료 여부
	eKARMA_KW_ITEM_OWN		,	//	아이템 소유 여부
	eKARMA_KW_GUILD_MEMBER	,	//	길드 소속 여부
	eKARMA_KW_ITEM_EQUIP	,
	eKARMA_KW_JOB_OWN		,
	eKARMA_KW_PARTY_GUILD_MEMBER_EXIST			,	//	길드에 소속한 파티원이 있냐?
	eKARMA_KW_ALL_PARTY_MEMBER_IN_SAME_GUILD	,
	eKARMA_KW_SPECIFIC_ITEM_OWN_MEMBER_EXIST	,	//	특정 아이템을 소유한 멤버가 있다.
	eKARMA_KW_EXIST								,	
	eKARMA_KW_OWN								,
	eKARMA_KW_SPEECH							,
	eKARMA_KW_SHOP								,
	eKARMA_KW_QUEST								,
	eKARMA_KW_QUEST_PROCESS_LEVEL				,
	eKARMA_KW_SPECIAL_ITEM						,
	eKARMA_KW_ADD_REMOVE						,

	eKARMA_KW_FIELD								,
	eKARMA_KW_BATTLE_INCLINATION				,
	
	eKARMA_KW_AREA								,
	eKARMA_KW_ALL_AREA							,

	eKARMA_KW_TARGET_PLAYER						,
	eKARMA_KW_TARGET							,
	
	eKARMA_KW_CHARACTER							,
	eKARMA_KW_ALL_CHARACTER						,
	eKARMA_KW_ALL_CHARACTER_TARGET_PLAYER		,
	eKARMA_KW_NOTICE_RANGE						,
	eKARMA_KW_NOTICE_TYPE						,
	eKARMA_KW_TEXT_BOX							,
	eKARMA_KW_PHYSICAL_MAGIC					,
	eKARMA_KW_EQUIPMENT							,
	eKARMA_KW_SPECIFIC_ITEM						,
	eKARMA_KW_QUEST_ARBEIT						,
	eKARMA_KW_PLUS_MINUS						,
	eKARMA_KW_QUEST_ITEM						,
	eKARMA_KW_PARTY_MEMBER_LOCATION				,
	eKARMA_KW_PLAYER_JOB						,
	eKARMA_KW_INCLUDE_TRANSFORMATION_JOB		,
	eKARMA_KW_IDA_ANIDA							,
	eKARMA_KW_IS_PARTY_LEADER					,
	eKARMA_KW_PARTY_MEMBER_EQUAL				,
	eKARMA_KW_ONLY_EQUAL						,
	eKARMA_KW_IN_OUT							,
	eKARMA_KW_CHECK_OPERATOR					,
	eKARMA_KW_QUEST_TARGET						,
	eKARMA_KW_TIME_CHECK						,
	eKARMA_KW_QUEST_COMPLETE_CHECKER			,
	eKARMA_KW_CHECK_QUEST_COMPLETE_CHECKER		,
	eKARMA_KW_DUNGEON_VALUE						,
	eKARMA_KW_AREA_IN_OUT						,
	eKARMA_KW_ADD_SET_REMOVE					,
	eKARMA_KW_MOVE_PATROL						,
	eKARMA_KW_ARCA_DOOR_TRAP_STATUS				,
	eKARMA_KW_ARCA_DOOR_TRAP					,
	eKARMA_KW_MONSTER_TARGET_SELF				,
	eKARMA_KW_INVINCIBLE_ON_OFF					,
	eKARMA_KW_TRAP_AREA							,
	eKARMA_KW_EVENT_BEGIN_END					,
	eKARMA_KW_QUEST_ABLE						,
	eKARMA_KW_QUEST_JOB							,
	eKARMA_KW_ARBEIT_JOB						,
	eKARMA_KW_SET_ELEMENT_ITEM					,
	eKARMA_KW_ITEM_PIECE						,
	eKARMA_KW_SET_CANCEL						,
	eKARMA_KW_DIRECT							,
	eKARMA_KW_COUNTDOWN_TYPE					,
	eKARMA_KW_START_END_RESET					,
	eKARMA_KW_BATTLE_STATUS						,
	eKARMA_KW_SETTING_STATUS					,
	eKARMA_KW_COUNTDOWN_STATUS					,
	eKARMA_KW_QUEST_COUNTDOWN_CHECK				,
	eKARMA_KW_TARGET_LEADER						,
	eKARMA_KW_SKILL_EFFECT_TYPE					,
	eKARMA_KW_SET_RESET							,
	eKARMA_KW_ACTION							,
	eKARMA_KW_ENABLE_DISABLE					,
	eKARMA_KW_ALL_PLAYER						,
	eKARMA_KW_SOUND_FILE						,

	eKARMA_KW_MAIN_QUEST_VALUE					,
	eKARMA_KW_MAIN_QUEST_SWITCH					,
	eKARMA_KW_CHAPTER							,
	eKARMA_KW_CHECK_ON_OFF						,
	eKARMA_KW_SET_PLUS_MINUS					,
	eKARMA_KW_BOOK								,
	eKARMA_KW_WRITE_ERASE						,
	eKARMA_KW_START_END_EXTENSION_REDUCTION		,
	eKARMA_KW_APPLY_PREMIUM_BONUS				,
	eKARMA_KW_ABLE_DISABLE						,
	eKARMA_KW_TEST_NORMAL						,
	eKARMA_KW_CURRENT_STATUS					,
	eKARMA_KW_SET_RESET_SCROLL					,
	eKARMA_KW_PATTERN							,
	eKARMA_KW_ENTRY_DEATH						,
	eKARMA_KW_BOSS_MONSTER						,
	eKARMA_KW_TARGET_OWNER						,
	eKARMA_KW_GUILD_BATTLE_TYPE					,
	eKARMA_KW_GUILD_HALL_OWN_OTHER				,
	eKARMA_KW_GUILD_STATUE_SKILL				,
	eKARMA_KW_RELATED_PLACE_OF_GUILD			,
	eKARMA_KW_METHOD_OF_GIVE_GP					,
	eKARMA_KW_MOVE_METHOD						,
	eKARMA_KW_TALK_METHOD						,
	eKARMA_KW_DAMAGE_METHOD						,
	eKARMA_KW_COMPLETE_STOP						,
	eKARMA_KW_IGNORE_INCLUDE_EQUIPMENT			,
	eKARMA_KW_RANK_IN_GUILD						,
	eKARMA_KW_SEX								,
	eKARMA_KW_EVENT_MONSTER						,
	eKARMA_KW_LOCAL								,
	eKARMA_KW_BY_LEVEL							,
	eKARMA_KW_GIVE_DROP							,
	eKARMA_KW_FIELD_VALUE						,
	eKARMA_KW_ALL_CHARACTER_TARGET_PLAYER2		,
	eKARMA_KW_HEAVEN_REWARD,//	인스턴스 던전으로 이동
	eKARMA_KW_HELL_REWARD,//	인스턴스 던전으로 이동
	eKARMA_KW_RED_DEVIL_REWARD,//	인스턴스 던전으로 이동
	eKARMA_KW_PLUSNUMBER_MINUSNUMBER,
	eKARMA_KW_HEAVEN_BONUS,
	eKARMA_KW_JANI_ANJINA,
	eKARMA_KW_BONUS_PENELTY,
	eKARMA_KW_EVENT,
	eKARMA_KW_HANDA_ANHANDA,
	eKARMA_KW_MONSTER,
	eKARMA_KW_DUEL_INTERFACE,
	//eKARMA_KW_KARMA,

	eKARMA_KW_ITEM_BOOLEAN_OPTION_LIST		,
	eKARMA_KW_SEASON_VALIABLE					,
	eKARMA_KW_GRACE								,
	eKARMA_KW_WORLD_VALUE						,
	eKARMA_KW_EFFECT_FLICKERINGLY				,
	eKARMA_KW_WEEKDAY							,
	eKARMA_KW_IS_SECRECTD_GUILDD	,
	eKARMA_STATE					,
	eKARMA_FIX_FIELD_RESISTANCE		,
	eKARMA_SCRREN_EFFECT			,
	eKARMA_BLIND_EFFECT			,
	eKARMA_QUEST_KIND	,

	eKARMA_FIELD_WEATHER,				// 기후변화 09.10.06
	eKARMA_INCLUDE_SOLO	,	

	eKARMA_KW_QUEST_CHECK_SOLO,
	eKARMA_KW_TILE_SET,	//타일셋
	eKARMA_KW_EVENT_TIME_NAME,	//이벤트 타임 시간
	eKARMA_KW_DRAWING_METHOD,	// 이미지 출력 방법
	eKARMA_KW_POPUP_INTERFACE,	//	인터페이스
	eKARMA_KW_OPEN_AND_CLOSE,	//	열기/닫기
	eKARMA_KW_ADD_GOLD_REASON,

	eKARMA_KW_BORDER_COMMENT					,//	얘는 항상 마지막에 있어야 한다.

};	//	카르마 키워드

#endif