//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mangchi.rc
//
#define IDOK2                           2
#define IDC_CHECK_ALL                   3
#define IDCANCEL2                       3
#define IDC_ADD_PREFIX                  3
#define IDC_PLAY                        3
#define IDC_DECHECK_ALL                 4
#define IDCANCEL3                       4
#define IDC_PROCESS_UNIQUE_DATA         5
#define IDC_PROCESS_ITEM_DATA           6
#define IDC_APPLY_NAME                  6
#define IDC_SET_EVENT                   7
#define IDC_COPY_ITEM_DATA              7
#define TB_BITMAP                       103
#define IDR_MAIN_ACCEL                  122
#define IDD_DIALOG1                     140
#define IDC_EDIT2                       1001
#define IDC_BEGIN_NPC                   1001
#define IDC_SELECT_CHAPTER_CONTENTS     1001
#define IDC_HUNTING_ICON_X              1001
#define IDC_X                           1001
#define IDC_SELECTED_FIRST_FILE_PATH    1001
#define IDC_REMOVE_PREFIX               1002
#define IDC_MAP_HEIGHT                  1002
#define IDC_JOB1_NAME                   1002
#define IDC_EDIT3                       1002
#define IDC_SELECT_CHAPTER_EPILOG       1002
#define IDC_HUNTING_ICON_Y              1002
#define IDC_JOB2_NAME                   1003
#define IDC_EDIT4                       1003
#define IDC_LIMIT_REGEN_MONSTER_COUNT   1003
#define IDC_MAX_PROPRIETY_LEVEL         1003
#define IDC_HUNTING_LEVEL_LOW           1003
#define IDC_Y                           1003
#define IDC_EDIT7                       1004
#define IDC_MIN_LIMIT_LEVEL             1004
#define IDC_HUNTING_LEVEL_HIGH          1004
#define IDC_DISABLE_MAGIC               1005
#define IDC_EDIT8                       1005
#define IDC_MAX_LIMIT_LEVEL             1005
#define IDC_GLOBAL_VALUE                1006
#define IDC_EDIT9                       1006
#define IDC_PART_NUMBER                 1006
#define IDC_LOCAL_VALUE                 1007
#define IDC_CHAPTER_NUMBER              1007
#define IDC_STATIC_VALUE                1008
#define IDC_QUARTER                     1008
#define IDC_CHARACTER                   1009
#define IDC_DURABILITY                  1009
#define IDC_LIST1                       1010
#define IDC_MIN_DAMAGE                  1010
#define IDC_LIST                        1010
#define IDC_LINK_LIST                   1010
#define IDC_BGM                         1010
#define IDC_KARMA_MONSTERLIST           1010
#define IDC_TEXT_LIST                   1010
#define IDC_VALUE_NAME                  1011
#define IDC_EDIT13                      1011
#define IDC_DEFENSE                     1011
#define IDC_NOT_SORT_LIST               1011
#define IDC_DOOR_DEFENSE                1011
#define IDC_DEFAULT_VALUE               1012
#define IDC_EDIT14                      1012
#define IDC_WEIGHT                      1012
#define IDC_BLOCKING_RATE               1012
#define IDC_DOOR_MAGIC_RESISTANCE       1012
#define IDC_DOOR_DEFENSE_PERCENT        1012
#define IDC_REQUIRE_LEVEL               1013
#define IDC_DESTROY_MIN_LEVEL           1013
#define IDC_ADD                         1014
#define IDC_STACK_COUNT                 1014
#define IDC_DEL                         1015
#define IDC_ADD2                        1015
#define IDC_REQUIRE_STRENGTH            1015
#define IDC_COPY                        1015
#define IDC_MODIFY_SELECT_PATTERN       1015
#define IDC_ADD3                        1016
#define IDC_REQUIRE_DEXERITY            1016
#define IDC_REQUIRE_DEXTERITY           1016
#define IDC_PASTE                       1016
#define IDC_APPLY                       1017
#define IDC_REQUIRE_CONSTITUTE          1017
#define IDC_EXPORT                      1017
#define IDC_LOAD_SCRIPT                 1017
#define IDC_PREVIOUS_ITEM               1017
#define IDC_RESET                       1017
#define IDC_REQUIRE_WISDOM              1018
#define IDC_IMPORT                      1018
#define IDC_LOAD_ITEM_SCRIPT            1018
#define IDC_LOAD_EFFECT_SCRIPT          1018
#define IDC_REQUIRE_INTELLIGENCE        1019
#define IDC_REQUIRE_CHARISMA            1020
#define IDC_REQUIRE_LUCK                1021
#define IDC_NEXT_ITEM                   1021
#define IDC_SPEED                       1022
#define IDC_REQUIRE_MAX_LEVEL           1023
#define IDC_MIN_DAMAGE2                 1024
#define IDC_MAX_DAMAGE                  1024
#define IDC_COUNT                       1026
#define IDC_LIVE_KARMA                  1027
#define IDC_OR                          1029
#define IDC_AND                         1030
#define IDC_BUTTON1                     1031
#define IDC_INSERT                      1031
#define IDC_COPY_NAME                   1031
#define IDC_HELP_SCRIPT                 1031
#define IDC_PATTERN_HELP                1031
#define IDC_VIEW_JOB_DATA               1031
#define IDC_LOAD_ITEM_DATA              1031
#define IDC_BT_CHECK_DATA_VIEW          1031
#define IDC_BUTTON_EDIT_BASEDATA        1031
#define IDC_REMOVE_ALLMONSTER           1031
#define IDC_SAVE_SPEECH                 1031
#define IDC_BUTTON_RESET_DEFUALT        1031
#define IDC_BT_CLOSE                    1031
#define IDC_SHOPCOPY                    1031
#define IDC_SELECT_MAP_FILE             1031
#define IDC_BUTTON2                     1032
#define IDC_REMOVE_TRIGGER              1032
#define IDC_APPLY_JOB2_ABILITY_DATA     1032
#define IDC_ADD_BGM                     1032
#define IDC_MAKE_CUSTOM_ITEM            1032
#define IDC_REMOVE_ALLNPC               1032
#define IDC_REMOVE_MONSTER              1032
#define IDC_BT_AREASAVE                 1032
#define IDC_SHOPPASTE                   1032
#define IDC_SELECT_ITEM_FILE            1032
#define IDC_BUTTON3                     1033
#define IDC_EDIT_TRIGGER                1033
#define IDC_SET_ABILITY1                1033
#define IDC_REMOVE_BGM                  1033
#define IDC_REMOVE_NPC                  1033
#define IDC_EDIT_BASEDATA               1033
#define IDC_BT_AREADELETE               1033
#define IDC_SELECT_RPD_FILE             1033
#define IDC_QUICK_REACTION2             1034
#define IDC_EDIT_ABILITY                1034
#define IDC_EDIT_MONSTER_EVENT          1034
#define IDC_SET_ABILITY2                1035
#define IDC_QUICK_REACTION3             1035
#define IDC_ADD_SPEECH                  1035
#define IDC_EDIT_NPCSPEECH              1035
#define IDC_MONSTER_NPC_DATA            1035
#define IDC_BUTTON4                     1036
#define IDC_NEW_REACTION                1036
#define IDC_REMOVE_SPEECH               1036
#define IDC_REMOVE_ALLSPEECH            1036
#define IDC_CANCEL_SELECT_DATA          1036
#define IDC_BUTTON5                     1037
#define IDC_REMOVE_REACTION             1037
#define IDC_EDIT_SPEECH                 1037
#define IDC_REMOVE_NPCSPEECH            1037
#define IDC_ADD_CONTENTS_SPEECH         1037
#define IDC_ADD_CONTENTS                1037
#define IDC_BUTTON6                     1038
#define IDC_EDIT_REACTION               1038
#define IDC_REMOVE_ALL_SPEECH           1038
#define IDC_COPY_SPEECH                 1038
#define IDC_CLOSE_NPCEDIT               1038
#define IDC_INSERT_REACTION             1039
#define IDC_PASTE_SPEECH                1039
#define IDC_NAME                        1040
#define IDC_REMOVE_CONTENTS             1040
#define IDC_LOOP                        1041
#define IDC_DUNGEON_FOLDER              1041
#define IDC_2ST_PREFIX                  1041
#define IDC_EQUIP_LEVEL                 1041
#define IDC_MODIFY_SPEECH               1041
#define IDC_COPY_REACTION               1042
#define IDC_MAP_WIDTH                   1043
#define IDC_PASTE_REACTION              1043
#define IDC_TILESET                     1044
#define IDC_UP_REACTION                 1044
#define IDC_DOWN_REACTION               1045
#define IDC_PREFIX2                     1045
#define IDC_MAP_LIST                    1046
#define IDC_QUICK_REACTION4             1046
#define IDC_PREFIX3                     1046
#define IDC_UP_TRIGGER                  1046
#define IDC_DOWN_TRIGGER                1047
#define IDC_QUICK_REACTION5             1047
#define IDC_PREFIX2_KIND                1047
#define IDC_QUICK_REACTION6             1048
#define IDC_PREFIX3_KIND                1048
#define IDC_QUICK_REACTION7             1049
#define IDC_TONGMAP                     1050
#define IDC_QUICK_REACTION8             1050
#define IDC_TONGMAP_NAME                1051
#define IDC_QUICK_REACTION9             1051
#define IDC_BATTLE_FIELD                1052
#define IDC_QUICK_REACTION10            1052
#define IDC_LOAD_TONGMAP                1053
#define IDC_QUICK_REACTION11            1053
#define IDC_OVERLAP_NAME                1054
#define IDC_QUICK_REACTION12            1054
#define IDC_LOAD_OVERLAP                1055
#define IDC_QUICK_REACTION13            1055
#define IDC_LOAD_OBJECT                 1056
#define IDC_QUICK_REACTION14            1056
#define IDC_VILLAGE                     1057
#define IDC_SET_QUICK_REACTION          1057
#define IDC_QUICK_TRIGGER2              1058
#define IDC_QUICK_TRIGGER3              1059
#define IDC_KARMA_GROUP_LIST            1060
#define IDC_BRIDGE                      1060
#define IDC_QUICK_TRIGGER4              1060
#define IDC_QUICK_TRIGGER5              1061
#define IDC_REMOVE                      1062
#define IDC_QUICK_TRIGGER6              1062
#define IDC_QUICK_TRIGGER7              1063
#define IDC_ADD_ITEM                    1063
#define IDC_UP                          1063
#define IDC_LOADING_TEXT                1063
#define IDC_REMOVE_SELECT_HIGH_QUEST    1063
#define IDC_KARMA_GROUP                 1064
#define IDC_CHANGE_ICON_SHAPE           1064
#define IDC_QUICK_TRIGGER8              1064
#define IDC_DOWN                        1064
#define IDC_ADD_ITEM2                   1064
#define IDC_ADD_CUSTOM_ITEM             1064
#define IDC_EDIT_ITEM                   1064
#define IDC_NEW_TRIGGER                 1065
#define IDC_CHANGE_EQUIPED_SHAPE        1065
#define IDC_LOAD_TEXT                   1065
#define IDC_UP2                         1065
#define IDC_TRIGGER_WND                 1066
#define IDC_ADD_SET_ITEM                1066
#define IDC_DOWN2                       1066
#define IDC_REACTION_WND                1067
#define IDC_CHANGE_FIELD_SHAPE2         1067
#define IDC_CHANGE_FIELD_SHAPE          1067
#define IDC_ADD_ITEM_PIECE              1067
#define IDC_QUICK_TRIGGER9              1068
#define IDC_ITEM_KIND                   1068
#define IDC_QUICK_TRIGGER10             1069
#define IDC_QUICK_TRIGGER11             1070
#define IDC_QUICK_TRIGGER12             1071
#define IDC_QUICK_TRIGGER13             1072
#define IDC_NORMAL                      1072
#define IDC_QUICK_TRIGGER14             1073
#define IDC_BOARD                       1073
#define IDC_SET_QUICK_TRIGGER           1074
#define IDC_DOOR                        1074
#define IDC_COPY_TRIGGER                1075
#define IDC_PORTAL                      1075
#define IDC_CREATE_MONSTER              1076
#define IDC_PASTE_TRIGGER               1076
#define IDC_START_AREA                  1077
#define IDC_RADIO2                      1077
#define IDC_MULTIPLE                    1077
#define IDC_PLUS                        1078
#define IDC_NAMED_AREA                  1078
#define IDC_RADIO3                      1079
#define IDC_LOAD                        1086
#define IDC_OPEN                        1088
#define IDC_FILE_NAME                   1088
#define IDC_CLOSE                       1089
#define IDC_PROJECT                     1090
#define IDC_EDIT1                       1091
#define IDC_BEGIN_YEAR                  1091
#define IDC_ACTIVATE_CHANCE             1091
#define IDC_CORRECT_FIRE_RESISTANCE     1091
#define IDC_ITEM_EQUIP_LIMIT_LEVEL      1091
#define IDC_CORRECT_EXP                 1091
#define IDC_TARGET_X                    1091
#define IDC_STAY_NODE_TIME              1091
#define IDC_CHAPTER_NAME                1091
#define IDC_COMMAND_LINE                1091
#define IDC_FILTER                      1091
#define IDC_SEARCH_ITEM                 1091
#define IDC_QUEST_FILTER                1091
#define IDC_EDIT_ARCA_FILTER            1091
#define IDC_EDIT_CUSTOM_FILTER          1091
#define IDC_EDIT_PIECEITEM_FILTER       1091
#define IDC_EDIT_SETITEM_FILTER         1091
#define IDC_NEXT_ETERNAL_ITEM_SERIAL    1091
#define IDC_EDIT_FIND_LIST              1091
#define IDC_EDIT_MONSTER_CONCEPT        1091
#define IDC_INDEX_CHANGE_OBJECT         1091
#define IDC_POS_X                       1091
#define IDC_RESULT                      1091
#define IDC_COMBO1                      1092
#define IDC_EXP                         1092
#define IDC_JOB2_LEVEL                  1092
#define IDC_MAX_GOLD                    1092
#define IDC_TYPE                        1092
#define IDC_SIZE_LIST                   1092
#define IDC_BGM_LIST                    1092
#define IDC_EVENT_CONDITION_LIST        1092
#define IDC_BEGIN_MONTH                 1092
#define IDC_QUEST_TYPE                  1092
#define IDC_DETAIL_KIND                 1092
#define IDC_CHECK_PERIOD                1092
#define IDC_SET_ITEM_GROUP_LIST         1092
#define IDC_SET_ITEM_GROUP              1092
#define IDC_LIMIT_COUNT                 1092
#define IDC_TARGET_Y                    1092
#define IDC_HIGH_QUEST_NAME             1092
#define IDC_SKIN                        1092
#define IDC_PATTERN_EX                  1092
#define IDC_WEAR_LIMIT_COUNT            1092
#define IDC_EVENT_CONDITION_MONSTERLIST 1092
#define IDC_POS_Y                       1092
#define IDC_STATUS                      1092
#define IDC_COMBO2                      1093
#define IDC_EDIT11                      1093
#define IDC_MAP_SIZE                    1093
#define IDC_BEGIN_DAY                   1093
#define IDC_CORRECT_WATER_RESISTANCE    1093
#define IDC_AREA_KIND                   1093
#define IDC_PIECE_ITEM                  1093
#define IDC_ID_CODE                     1093
#define IDC_SOURCE_X                    1093
#define IDC_ACTIVATE_TRIGGER_COUNT      1093
#define IDC_AB_PH_DAMAGE_CHANCE         1093
#define IDC_UPGRADE_BASE_SUCCESS_PERCENT 1093
#define IDC_RADIO1                      1094
#define IDC_CORRECT_WIND_RESISTANCE     1094
#define IDC_LIMIT_ACTIVE_COUNT          1094
#define IDC_TRAP_2_1                    1094
#define IDC_PIECE_DROP_CHANCE           1094
#define IDC_ITEM_PIECE                  1094
#define IDC_SOURCE_Y                    1094
#define IDC_LIMIT_HOUR                  1094
#define IDC_PAGE_IMAGE                  1094
#define IDC_SHOP_LIST_SORT_NAME         1094
#define IDC_AB_PH_DAMAGE_RATE           1094
#define IDC_ETERNAL_ITEM_CURRENT_LEVEL  1094
#define IDC_RADIO4                      1095
#define IDC_VALUE_LIST                  1095
#define IDC_BASE_JOB2                   1095
#define IDC_CORRECT_EARTH_RESISTANCE    1095
#define IDC_TRAP_1_1                    1095
#define IDC_LIMIT_MINUTE                1095
#define IDC_SHOP_LIST_SORT_INDEX        1095
#define IDC_AB_FIRE_DAMAGE_CHANCE       1095
#define IDC_UPGRADE_COSMICPOWER_SUCCESS_PERCENT 1095
#define IDC_ABILITY_LIST                1096
#define IDC_CORRECT_LIGHT_RESISTANCE    1096
#define IDC_TRAP_1_2                    1096
#define IDC_LIMIT_LOW_LEVEL             1096
#define IDC_AB_FIRE_DAMAGE_RATE         1096
#define IDC_UPGRADE_MATERIALS_SUCCESS_PERCENT 1096
#define IDC_EXPLAIN                     1097
#define IDC_CORRECT_DARK_RESISTANCE     1097
#define IDC_LIMIT_HIGH_LEVEL            1097
#define IDC_AB_WATER_DAMAGE_CHANCE      1097
#define IDC_UPGRADE_PENALTY_ITEM_SERIAL 1097
#define IDC_TAB                         1098
#define IDS_CONNECT_AREA                1098
#define IDC_FIELD_TYPE_LIST             1098
#define IDC_AB_WATER_DAMAGE_RATE        1098
#define IDC_ITEM_RIBIRTH_COUNT          1098
#define IDC_QUEST_LIST                  1099
#define IDC_MINIMAP_DISPLAY_LEVEL       1099
#define IDC_AB_WIND_DAMAGE_CHANCE       1099
#define IDC_LIMIT_UPGRADE_RING_OF_INFINITY 1099
#define IDC_QUEST_NAME                  1100
#define IDC_LINK_SECRET_DUNGEON         1100
#define IDC_HIGH_QUEST_LIST             1100
#define IDC_AB_WIND_DAMAGE_RATE         1100
#define IDC_MOVE_FIELD_SERIAL           1100
#define IDC_WHAT_PORTAL                 1101
#define IDC_QUEST_CLIENT_NAME           1101
#define IDC_QUEST_CLIENT_INFO           1101
#define IDC_AB_EARTH_DAMAGE_CHANCE      1101
#define IDC_ITEM                        1102
#define IDC_DIRECT                      1102
#define IDC_QUEST_CLIENT_POS            1102
#define IDC_AB_EARTH_DAMAGE_RATE        1102
#define IDC_FIELD_WEATHER               1102
#define IDC_ITEM_COUNT                  1103
#define IDC_DIRECT2                     1103
#define IDC_QUEST_VALUE_COMMENT         1103
#define IDC_AB_LIGHT_DAMAGE_CHANCE      1103
#define IDC_ITEM_BOX                    1104
#define IDC_GATE_SHAPE                  1104
#define IDC_AB_LIGHT_DAMAGE_RATE        1104
#define IDC_ACTOR_POWER                 1105
#define IDC_COMBO_SEASON                1105
#define IDC_EXCHANGE_POWER1_2           1105
#define IDC_EXTRA_LEVEL                 1105
#define IDC_AB_DARK_DAMAGE_CHANCE       1105
#define IDC_ACTOR_POWER_ROUND           1106
#define IDC_COMBO3                      1106
#define IDC_EXCHANGE_POWER2_1           1106
#define IDC_QUEST_KIND                  1106
#define IDC_DOOR_LINK_SECRET_DUNGEON    1106
#define IDC_AB_DARK_DAMAGE_RATE         1106
#define IDC_COMBO5                      1107
#define IDC_EXCHANGE_POWER2_2           1107
#define IDC_COMBO_SWAP_AREA             1107
#define IDC_COMBO6                      1108
#define IDC_EXCHANGE_POWER3_1           1108
#define IDC_CB_START_YEAR               1108
#define IDC_COMBO7                      1109
#define IDC_EXCHANGE_POWER3_2           1109
#define IDC_CB_END_YEAR                 1109
#define IDC_GATHER                      1110
#define IDC_EDIT5                       1110
#define IDC_COMBO8                      1110
#define IDC_EXCHANGE_POWER4_1           1110
#define IDC_SOLO                        1111
#define IDC_EDIT6                       1111
#define IDC_COMBO9                      1111
#define IDC_EXCHANGE_POWER4_2           1111
#define IDC_JOB1                        1112
#define IDC_EDIT10                      1112
#define IDC_JOB2                        1113
#define IDC_CHANGE_JOB1                 1114
#define IDC_ATTACK_PART                 1114
#define IDC_JOB_LIST                    1115
#define IDC_ITEM_LIST                   1115
#define IDC_EXCHANGE_POWER5_2           1115
#define IDC_EXCHANGE_POWER6_1           1116
#define IDC_EXCHANGE_POWER6_2           1117
#define IDC_POLL_AREA                   1119
#define IDC_POLL_HERO                   1120
#define IDC_POLL                        1121
#define IDC_RANGE                       1122
#define IDC_ADD_ABILITY                 1123
#define IDC_DAMAGE_RANGE                1123
#define IDC_REMOVE_ABILITY              1124
#define IDC_SKILL_LIST                  1126
#define IDC_TRAP_SKILL1                 1126
#define IDC_LEVEL                       1127
#define IDC_TRAP_SKILL2                 1127
#define IDC_ABILITY_LIST1               1128
#define IDC_LEVEL_MAX                   1128
#define IDC_SKILL_LEVEL                 1128
#define IDC_TRAP_TARGET                 1128
#define IDC_HP                          1129
#define IDC_ABILITY_LIST2               1129
#define IDC_LEVEL2                      1129
#define IDC_CP                          1130
#define IDC_SCALE_Y                     1130
#define IDC_LIMIT_LEVEL                 1131
#define IDC_CORRECT_USE_SKILL_CHANCE    1131
#define IDC_JOB2_EXP                    1132
#define IDC_HP_FACTOR                   1132
#define IDC_POWER                       1133
#define IDC_CONSTITUTION                1134
#define IDC_EQUIPMENT_LIST              1134
#define IDC_CORRECT_AP                  1134
#define IDC_INTELIGENCE                 1135
#define IDC_LUCK                        1136
#define IDC_DEXTERITY                   1137
#define IDC_CHARISMA                    1138
#define IDC_WISDOM                      1139
#define IDC_ADD_POWER_LIST              1139
#define IDC_ITEM_SHAPE                  1140
#define IDC_SIGHT                       1140
#define IDC_ADD_ITEM_LIST               1140
#define IDC_ITEM_EQUIPPED_SHAPE         1141
#define IDC_BASIC_POWER_LEVEL_FACTOR    1141
#define IDC_ITEM_EQUIP_SHAPE            1142
#define IDC_MAX_DAMAGE_LEVEL_FACTOR     1142
#define IDC_ITEM_FIELD_SHAPE            1143
#define IDC_DEFENSE_POWER_LEVEL_FACTOR  1143
#define IDC_FIRE_REGISTANCE             1144
#define IDC_WATER_REGISTANCE            1145
#define IDC_WIND_REGISTANCE             1146
#define IDC_LIGHT_REGISTANCE            1147
#define IDC_EARTH_REGISTANCE            1148
#define IDC_DARK_REGISTANCE             1149
#define IDC_CORRECT_STUN                1150
#define IDC_DECLINE_POWER_REGISTANCE    1150
#define IDC_CORRECT_POISON              1151
#define IDC_BAD_STATUS_REGISTANCE       1151
#define IDC_CORRECT_MOVE                1152
#define IDC_DEFENSIVE_POWER             1152
#define IDC_CORRECT_FREEZE              1153
#define IDC_CURSE_REGISTANCE            1153
#define IDC_CORRECT_ACTION              1154
#define IDC_DEFENSIVE_POWER2            1154
#define IDC_CORRECT_HP                  1154
#define IDC_MIN_DAMAGE_LEVEL_FACTOR     1154
#define IDC_BASE_JOB1                   1155
#define IDC_BLIND                       1155
#define IDC_OPTION2                     1155
#define IDC_HP2                         1156
#define IDC_DEFENSIVE_POWER3            1156
#define IDC_CORRECT_CP                  1156
#define IDC_PPS                         1156
#define IDC_PREFIX_1                    1156
#define IDC_CP2                         1157
#define IDC_POISON                      1157
#define IDC_PREFIX_2                    1157
#define IDC_SLEEP                       1158
#define IDC_PREFIX_3                    1158
#define IDC_BASE_ITEM                   1159
#define IDC_COLD                        1159
#define IDC_POWER2                      1160
#define IDC_BASIC_ITEM_LIST             1160
#define IDC_CORRECT_POWER               1160
#define IDC_FREEZE                      1160
#define IDC_CONSTITUTION2               1161
#define IDC_ITEM_DETAIL                 1161
#define IDC_CORRECT_CONSTITUTION        1161
#define IDC_STUN                        1161
#define IDC_INTELIGENCE2                1162
#define IDC_ITEM_CATEGORY               1162
#define IDC_CORRECT_INTELIGENCE         1162
#define IDC_STONE                       1162
#define IDC_PREFIX_1_2                  1162
#define IDC_LUCK2                       1163
#define IDC_ITEM_EFFECT_LIST            1163
#define IDC_CORRECT_LUCK                1163
#define IDC_CONFUSE                     1163
#define IDC_PREFIX_2_2                  1163
#define IDC_SET_ITEM_COUNT              1163
#define IDC_REVERSION_METHOD            1163
#define IDC_DEXTERITY2                  1164
#define IDC_COMMENT                     1164
#define IDC_ITEM_EFFECT_LIST2           1164
#define IDC_CORRECT_DEXTERITY           1164
#define IDC_CHARMING                    1164
#define IDC_PREFIX_3_2                  1164
#define IDC_CHARISMA2                   1165
#define IDC_CORRECT_CHARISMA            1165
#define IDC_ALL_REGISTANCE              1165
#define IDC_UNIQUE_DATA                 1165
#define IDC_SKILL                       1165
#define IDC_WISDOM2                     1166
#define IDC_CORRECT_WISDOM              1166
#define IDC_CRITICAL_SHOT               1166
#define IDC_CORRECT_HIT                 1167
#define IDC_ENABLE_JOB                  1168
#define IDC_STORAGE_GRADE2              1168
#define IDC_EQUIP_GRADE                 1168
#define IDC_BLOCKING                    1168
#define IDC_PRICE                       1169
#define IDC_ACPS                        1169
#define IDC_ALLIGNMENT                  1170
#define IDC_ADD_EFFECT                  1171
#define IDC_CRUSH_SHOT                  1171
#define IDC_PRICE2                      1171
#define IDC_REMOVE_EFFECT               1172
#define IDC_CORRECT_DODGE               1172
#define IDC_EXPIRE_YEAR                 1172
#define IDC_ITEM_EFFECT_KIND            1173
#define IDC_DROP_LEVEL                  1173
#define IDC_CON_FACTOR                  1173
#define IDC_QUANTITY                    1174
#define IDC_EQUIP_USE_LIMIT_CONTENTS    1174
#define IDC_DISCERNMENT_CODE            1174
#define IDC_SKILL_LEVEL_PER_LEVEL       1174
#define IDC_VALIDATE_DAY                1174
#define IDE_QUANTITY                    1175
#define IDC_REMOVE_UNIQUE_DATA          1175
#define IDC_VALIDATE_HOUR               1175
#define IDC_CRITICAL_RESISTANCE         1175
#define IDC_QUANTITY2                   1176
#define IDC_EQUIP_USE_LIMIT_COMPUTE_METHOD 1176
#define IDC_VALIDATE_MINUTE             1176
#define IDC_CRUSH_RESISTANCE            1176
#define IDC_CORRECT_VALUE1_QUALITY      1176
#define IDC_ADD_UNIQUE_DATA             1177
#define IDC_TAME_RESISTANCE             1177
#define IDC_CORRECT_VALUE2_QUALITY      1177
#define IDC_EXPIRE_MONTH                1178
#define IDC_SHAPE                       1178
#define IDC_EXPIRE_DAY                  1179
#define IDC_SKILL_FILTER                1179
#define IDC_EXPIRE_HOUR                 1180
#define IDC_MIN_ENCHANT_SUCCESS_CHANCE  1181
#define IDC_MAX_ENCHANT_SUCCESS_CHANCE  1182
#define IDC_ENCHANT_LIMIT_CODE          1183
#define IDC_PALETTE_LIST                1184
#define IDC_CORRECT_DROP_CHANCE         1185
#define IDC_EXCHANGE_POWER1_1           1186
#define IDC_COPY_BASE_ITEM_DATA         1186
#define IDC_EXCHANGE_POWER5_1           1187
#define IDC_EX_GRADE                    1187
#define IDC_PREMIUM_GRADE               1188
#define IDC_CHECK2                      1189
#define IDC_NO_LIMIT                    1189
#define IDC_NO_SPEECH                   1189
#define IDC_COOL_TIME_SLOT              1189
#define IDC_DISABLE_QUEST               1189
#define IDC_QUICK_REACTION1             1190
#define IDC_COOL_TIME                   1190
#define IDC_QUICK_TRIGGER1              1191
#define IDC_SECOND_JOB                  1191
#define IDC_CHANGE_UNIQUE_DATA          1191
#define IDC_CHECK3                      1192
#define IDC_KNIGHT                      1192
#define IDC_AI                          1192
#define IDC_WARD                        1192
#define IDC_CHECK4                      1193
#define IDC_CHECK5                      1194
#define IDC_CHECK6                      1195
#define IDC_BODY_LIST                   1195
#define IDC_CHECK7                      1196
#define IDC_CHECK8                      1197
#define IDC_CHECK9                      1198
#define IDC_JOB_INFO                    1198
#define IDC_CHECK10                     1199
#define IDC_CHECK11                     1200
#define IDC_VIEW_DATA_TAB               1200
#define IDC_CHECK12                     1201
#define IDC_CHECK13                     1202
#define IDC_CHECK14                     1203
#define IDC_CHECK15                     1204
#define IDC_TAB_BODY_GROUP              1204
#define IDC_CHECK16                     1205
#define IDC_JOB2LIST                    1205
#define IDC_CHECK17                     1206
#define IDC_JOB_GROUP                   1206
#define IDC_CHECK18                     1207
#define IDC_JOB2LIST2                   1207
#define IDC_JOB2_GROUP                  1208
#define IDC_MALE                        1208
#define IDC_JOB1_GROUP                  1209
#define IDC_FEMALE                      1209
#define IDC_CHECK52                     1210
#define IDC_JOB1LIST                    1210
#define IDC_LIMIT_MAGIC_KNIGHT          1210
#define IDC_CHECK53                     1211
#define IDC_LIMIT_MAGIC_WARRIOR         1211
#define IDC_ENABLE_JOB2                 1212
#define IDC_JOB1_BODY_COLOR             1213
#define IDC_JOB2_BODY_COLOR             1214
#define IDC_DROP_ITEM_LIST              1215
#define IDC_DROP_RATE                   1216
#define IDC_MIN_GOLD                    1217
#define IDC_GOLD                        1217
#define IDC_DROP_RATE2                  1217
#define IDC_DEATH_EXP                   1218
#define IDC_DROP_RATE3                  1218
#define IDC_REMOVE_ITEM                 1219
#define IDC_GOLD_DROP_RATE              1220
#define IDC_DROP_RATE4                  1220
#define IDC_DROP_ITEM_COUNT             1220
#define IDC_COPY_CHARACTER_SET          1221
#define IDC_BASIC_GOLD                  1221
#define IDC_DROP_RATE5                  1221
#define IDC_DURABILTY                   1221
#define IDC_FRAME                       1222
#define IDC_DROP_RATE6                  1222
#define IDC_RESISTANCE                  1222
#define IDC_STATIC_NAME                 1223
#define IDC_DROP_RATE7                  1223
#define IDC_DESTROY_ABLE_LEVEL          1223
#define IDC_STATIC_SIZE                 1224
#define IDC_DROP_RATE8                  1224
#define IDC_REGEN_MINUTE                1224
#define IDC_STATIC_TILESET              1225
#define IDC_DROP_RATE9                  1225
#define IDC_SECRET_LEVEL                1225
#define IDC_STATIC_TYPE                 1226
#define IDC_DROP_RATE10                 1226
#define IDC_LOCK_LEVEL                  1226
#define IDC_SAVE_DUNGEON                1227
#define IDC_DROP_RATE11                 1227
#define IDC_DETECT_TRAP_LEVEL           1227
#define IDC_CONTENTS                    1228
#define IDC_DROP_RATE12                 1228
#define IDC_DROP_GOLD                   1228
#define IDC_DROP_RATE13                 1229
#define IDC_TRAP_LEVEL                  1229
#define IDC_TRAP_STRENGTH               1230
#define IDC_TRAP_SKILL1_ACTIVE_CAHNCE   1230
#define IDC_LOAD_DUNGEON                1231
#define IDC_TRAP_INTELLIGENCE           1231
#define IDC_TRAP_SKILL2_ACTIVE_CAHNCE   1231
#define IDC_SET_FOLDER                  1232
#define IDC_UNLOCK_UPKEEP_TIME          1232
#define IDC_REGEN_SECOND                1232
#define IDC_DOOR_TRAP_LEVEL             1233
#define IDC_EDIT                        1236
#define IDC_LOAD_MAP                    1236
#define IDC_NEW                         1237
#define IDS_LOAD_MAP                    1237
#define IDC_OPTION_1_VALUE              1237
#define IDS_MOVE_GROUP                  1238
#define IDC_OPTION_2_VALUE              1238
#define IDC_ADD_HIGH_QUEST              1238
#define IDC_LOAD_MAP_NAME               1239
#define IDC_ITEM_COUNT_TEXT             1239
#define IDC_MODIFY_HIGH_QUEST_NAME      1239
#define IDC_TEXT                        1240
#define IDC_LEVEL_1                     1240
#define IDC_PREFIX_1_VALUE              1240
#define IDC_KIND                        1241
#define IDS_CREATE_MONSTER              1241
#define IDC_LEVEL_2                     1241
#define IDC_PREFIX_2_VALUE              1241
#define IDC_LEVEL_3                     1242
#define IDS_REGEN_TIME                  1242
#define IDC_MONSTER_GRADE               1242
#define IDC_PREFIX_3_VALUE              1242
#define IDC_LEVEL_4                     1243
#define IDC_REGEN_TIME                  1243
#define IDC_ITEM_CODE                   1243
#define IDC_REQUIRE_REBIRTH_COUNT_FOR_TAME 1243
#define IDC_LEVEL_5                     1244
#define IDS_MONSTER                     1244
#define IDC_OPTION_1_COMMENT            1244
#define IDC_LEVEL_6                     1245
#define IDS_REGEN                       1245
#define IDC_OPTION_2_COMMENT            1245
#define IDC_MONSTER_LIST                1246
#define IDC_PREFIX_2_VALUE2             1246
#define IDC_PREFIX_3_VALUE2             1247
#define IDC_OPTION_1_COMMENT2           1248
#define IDC_PREFIX1                     1249
#define IDC_BASIC_JOB_LIST              1250
#define IDC_OPTION1                     1250
#define IDC_PREFIX_1_VALUE2             1251
#define IDR_NPC                         1252
#define IDC_OPTION_1_COMMENT3           1252
#define IDR_MONSTER                     1253
#define IDC_PREFIX1_KIND                1253
#define IDC_CHANGE_DIRECT               1254
#define IDC_OPTION_1_COMMENT4           1254
#define IDC_REGEN_CYCLE_HOUR            1255
#define IDC_REGEN_CYCLE_MINUTE          1256
#define IDC_REGEN_CYCLE_SECOND          1257
#define IDC_GAZE_DIRECT                 1258
#define IDC_WANDER_AREA                 1259
#define IDC_PATROL_ROUTE                1260
#define IDC_WANDER_MINUTE               1261
#define IDC_WANDER_SECOND               1262
#define IDC_BATTLE_INCLINATION          1263
#define IDC_SET_LEADER                  1264
#define IDR_TWO_WAY_LINK                1265
#define IDR_ONE_WAY_LINK                1266
#define IDC_STATIC_LINK                 1267
#define IDC_GENERATE_METHOD             1268
#define IDC_BLOCK_TO_AUTO_REGEN         1269
#define IDC_IS_GUILD_CREST              1270
#define IDC_IS_GUILD_OBJECT             1271
#define IDC_IS_HIDE_NAME                1272
#define IDC_GENERATE_AROUND_METHOD      1273
#define IDC_GENERATE_METHOD_POS_Y       1274
#define IDC_GENERATE_METHOD_POS_X       1275
#define IDC_GENERATE_METHOD_WIDTH       1276
#define IDC_GENERATE_METHOD_HEIGHT      1277
#define IDC_STATIC_KARMA_DETAIL         1279
#define IDC_VALUE1_1                    1286
#define IDC_VALUE1_2                    1287
#define IDC_VALUE2_1                    1288
#define IDC_VALUE2_2                    1289
#define IDC_HELM                        1292
#define IDC_CHECK19                     1293
#define IDC_PRICE_COMPUTE_METHOD        1293
#define IDC_CHECK20                     1294
#define IDC_EQUIP_USE_LIMIT_VALUE       1294
#define IDC_CHECK21                     1295
#define IDC_ITEM_GENERATE_DATA          1295
#define IDC_CHECK22                     1296
#define IDC_ADD_GENERATE_DATA           1296
#define IDC_JOB1_IMAGE                  1297
#define IDC_CHECK23                     1297
#define IDC_REMOVE_GENERATE_DATA        1297
#define IDC_JOB2_IMAGE                  1298
#define IDC_CHECK24                     1298
#define IDC_PREMIUM_LEVEL               1298
#define IDC_KARMA_VIEW                  1299
#define IDC_CHECK25                     1299
#define IDC_KARMA_LIST                  1300
#define IDC_QUEST_OBJECT                1300
#define IDC_CHECK26                     1300
#define IDC_CHECK27                     1301
#define IDC_COMPULSION_EFFECT           1301
#define IDC_CHECK28                     1302
#define IDC_ITEM_EFFECT                 1302
#define IDC_CHECK29                     1303
#define IDC_CHECK48                     1304
#define IDC_CHECK49                     1305
#define IDC_CHECK50                     1306
#define IDC_CHECK51                     1307
#define IDC_CHECK30                     1308
#define IDC_CHECK31                     1309
#define IDC_CHECK32                     1310
#define IDC_CHECK33                     1311
#define IDC_CHECK34                     1312
#define IDC_CHECK35                     1313
#define IDC_CHECK36                     1314
#define IDC_CHECK37                     1315
#define IDC_CHECK38                     1316
#define IDC_CHECK39                     1317
#define IDC_CHECK40                     1318
#define IDC_CHECK41                     1319
#define IDC_CHECK42                     1320
#define IDC_CHECK43                     1321
#define IDC_CHECK44                     1322
#define IDC_CHECK45                     1323
#define IDC_CHECK46                     1324
#define IDC_CHECK47                     1325
#define IDC_JEWEL                       1326
#define IDC_SCYTHE                      1327
#define IDC_ARM_WEAPON                  1328
#define IDC_BOOK                        1329
#define IDC_ARMOR_EFFECT_LIST           1345
#define IDC_ITEM_PREFIX_TYPE            1346
#define IDC_NOUN                        1347
#define IDC_ADJECTIVE                   1348
#define IDC_PREFIX_EXPLAIN              1349
#define IDC_CATEGORY                    1351
#define IDC_LOAD_UNIQUE_SCRIPT          1352
#define IDC_QUEST                       1352
#define IDC_SORT                        1353
#define IDC_COMBO_TYPE                  1354
#define IDC_SHOW_SERIAL                 1354
#define IDC_COMBO_JOB                   1355
#define IDC_ADD_TRIGGER                 1356
#define IDC_DIALOG                      1358
#define IDC_REMOVE_DIALOG               1359
#define IDC_SPEECH_LIST                 1360
#define IDC_COPY_DIALOG                 1360
#define IDC_CONTENTS_WND                1361
#define IDC_BEGIN_CONDITION             1361
#define IDC_REMOVE_AND_PASTE_DIALOG     1361
#define IDC_SPEECH                      1362
#define IDC_PASTE_DIALOG                1362
#define IDC_CONTENTS_WND2               1362
#define IDC_RANDOM_PREFIX               1364
#define IDC_REFIX_PERIOD                1365
#define IDC_SELL_IN_CARROT_SHOP         1365
#define IDC_SPEECH2                     1365
#define IDC_USE_ORIGINAL                1366
#define IDC_SHOP_LIST                   1366
#define IDC_IS_CUSTOM_ITEM              1366
#define IDC_SHOP_INFO                   1367
#define IDC_PREFIX_QUALITY              1367
#define IDC_ITEM_INFO                   1368
#define IDC_GENERATE_QUALITY            1368
#define IDC_DETAIL_ITEM_INFO            1369
#define IDC_UPKEEP_HOUR                 1369
#define IDC_IS_IM_DUN_MONSTER           1370
#define IDC_UPKEEP_MINUTE               1370
#define IDC_SHOP_NAME                   1371
#define IDC_IS_IM_DUN_ARCA              1371
#define IDC_AND_TRIGGER                 1372
#define IDC_SHOP_PRICE_FACTOR           1372
#define IDC_IS_NORMAL_FIELD_MONSTER     1372
#define IDC_OR_TRIGGER                  1373
#define IDC_SHOP_LIMIT_PRICE            1373
#define IDC_IS_NORMAL_FIELD_ARCA        1373
#define IDC_IS_QUEST_REWARD             1374
#define IDC_DROP_CHANCE                 1375
#define IDC_IS_REVERSION                1375
#define IDC_SCALE_X                     1376
#define IDC_CORRECT_FINAL_DAMAGE        1377
#define IDC_CAN_NOT_DROP                1381
#define IDC_CAN_NOT_TRADE               1381
#define IDC_RANDOM                      1382
#define IDC_DURABILITY_TO_USE_COUNT     1382
#define IDC_USE_TO_ITEM                 1383
#define IDC_USE_TO_CHARACTER            1384
#define IDC_CAN_NOT_SELL                1385
#define IDC_USE_TO_CORPSE               1386
#define IDC_ACTIVE_CONDITION            1387
#define IDC_CAN_USE_CORPSE_STATUS       1387
#define IDC_REMOVE_ITEM_BY_CANCEL_QUEST 1388
#define IDC_EQUIPABLE_TO_BELT           1388
#define IDC_IS_PREMIUM_ZONE             1389
#define IDC_CAN_NOT_USEABLE_ITEM        1389
#define IDC_TEST_QUEST                  1389
#define IDC_ENABLE_CANCEL_QUEST         1390
#define IDC_CAN_NOT_DESTROY_ITEM        1390
#define IDC_IS_TEST_AREA                1390
#define IDC_IS_GUILD_BATTLE_ZONE        1390
#define IDC_CAN_NOT_STORE_TO_BANK       1391
#define IDC_IS_GUILD_BATTLE_LOBBY       1391
#define IDC_ENABLE_TAME                 1391
#define IDC_IS_CHANGE_OBJECT            1391
#define IDC_EXCLUSIVE_TO_UNIQUE_ITEM    1392
#define IDC_IS_LOCKED_MAP               1392
#define IDC_IS_ACTIVE                   1392
#define IDC_ZIN_BOSS                    1392
#define IDC_USE_ITEM_AFTER_TRANSFORMATION 1392
#define IDC_EXCLUSIVE_TO_NORMAL_ITEM    1393
#define IDC_IS_EVENT_FIELD              1393
#define IDC_CAN_DESTROY                 1393
#define IDC_IS_APPLY_TO_ENTER_FIELD_PLAYER 1393
#define IDC_USE_AFTER_WEAR              1393
#define IDC_CAN_NOT_DROPPING            1394
#define IDC_IS_OX_QUIZ_VILLAGE          1394
#define IDC_CUSTOM_ITEM                 1394
#define IDC_IS_APPLY_ALL_PARTY_MEMBER   1394
#define IDC_DESTROY_ENCHANT_FAILED_RING 1395
#define IDC_DISABLE_ORB_MEMORY          1395
#define IDC_TEXT_TRAP_INTELLIGENCE      1395
#define IDC_IS_NOT_APPLY_COPY_EFFECT    1395
#define IDC_UPGRADE_PREFIX_LEVEL        1396
#define IDC_TEXT_TRAP_STRENGTH          1396
#define IDC_SECRET_DUNGEON_GATE         1396
#define IDC_IS_NOT_APPLY_REVERSION_EFFECT 1396
#define IDC_IS_BADGE                    1397
#define IDC_TRAP_SKILL_LEVEL            1397
#define IDC_HALF_SIZE                   1397
#define IDC_IS_EFFECT_IN_INVENTORY      1398
#define IDC_TEXT_TRAP_SKILL_LEVEL       1398
#define IDC_WORD_QUIZ_MAP               1398
#define IDC_IGNORE_SAME_ITEM            1399
#define IDC_TRAP_SKILL_LIST             1399
#define IDC_WORD_QUIZ_VILLAGE           1399
#define IDC_COMPUTE_PRICE_METHOD        1400
#define IDC_GUILD_BATTLE_ITEM           1400
#define IDC_TEXT_TRAP_SKILL             1400
#define IDC_TRAP_SKILL2_LIST            1400
#define IDC_BLOCK_TO_WARP               1400
#define IDC_PREFIX_TYPE                 1401
#define IDC_REMAIN_USE_LOG              1401
#define IDC_TEXT_TRAP_DETECT_LEVE       1401
#define IDC_BOSSZONE                    1401
#define IDC_BOSS_ZONE                   1401
#define IDC_1ST                         1402
#define IDC_DX_ITEM                     1402
#define IDC_TRAP_DETECT_LEVE            1402
#define IDC_IS_GUILD_HALL               1402
#define IDC_2ST                         1403
#define IDC_BEGINNER_ITEM               1403
#define IDC_TEXT_DISARM_TRAP_LEVEL      1403
#define IDC_IS_1LEVEL_GUILD_HALL        1403
#define IDC_3ST                         1404
#define IDC_IS_EXTRA_ITEM               1404
#define IDC_DISARM_TRAP_LEVEL           1404
#define IDC_GUILD_POINT_BATTLE          1404
#define IDC_1ST_PREFIX                  1405
#define IDC_TEXT_TRAP_AP                1405
#define IDC_IS_USE_BULLET               1405
#define IDC_GUILD_SIEGE_WAREFARE        1405
#define IDC_VALUE3                      1406
#define IDC_IS_CARPET_EMBLEM            1406
#define IDC_TRAP_AP                     1406
#define IDC_IS_CAN_NOT_CALL_CARPET_FIELD 1406
#define IDC_SCRIPT                      1407
#define IDC_FRAME_TRAP                  1407
#define IDC_BLOCK_TO_USE_CALLING        1407
#define IDC_IS_ETERNAL                  1407
#define IDC_PREFIX_LIST                 1408
#define IDC_IS_DX_PREFIX                1408
#define IDC_IS_MERGE_CARPET_EMBLEM      1408
#define IDC_TEXT_TRAP_REGEN_TIME        1408
#define IDC_INVINCIBLE                  1408
#define IDC_IS_NOT_USE_SKILL_BEFORE_TRANS 1408
#define IDC_WEAPON_EFFECT_LIST          1409
#define IDC_REGEN_TRAP_SECOND           1409
#define IDC_NOT_EXP                     1409
#define IDC_IS_USE_SPECIAL_PRICE        1409
#define IDC_IS_RING_OF_INFINITY         1409
#define IDC_IS_NOT_OPEN_PITCHMAN_SHOP   1409
#define IDC_REGIST_PREFIX_LIST          1410
#define IDC_TEXT_REGEN_TRAP_SECOND      1410
#define IDC_NOT_OWN_ITEM                1410
#define IDC_TEXT_TRAP_DETECT_LEVE2      1410
#define IDC_ID_PUBLIC_ITEM              1410
#define IDC_IS_ULTRA_PREFIX             1410
#define IDC_IS_NIGHT                    1410
#define IDC_NOT_OWN_GOLD                1411
#define IDC_TEXT_TRAP_RANGE             1411
#define IDC_EXPIRED_BY_MOVE_FIELD       1411
#define IDC_TRAP_DETECT_LEVE2           1412
#define IDC_IS_KEY_MONSTER              1412
#define IDC_BUY_ONLY_GUILD_MASTER       1412
#define IDC_TEXT_REGEN_TRAP_SECOND2     1413
#define IDC_USE_ONLY_GUILD_MASTER       1413
#define IDC_CHARMING_IMMUNE             1413
#define IDC_TRAP_RANGE                  1414
#define IDC_EXCEPTION_ITEM              1414
#define IDC_STUN_IMMUNE                 1414
#define IDC_DOOR_REGEN_PERIOD           1415
#define IDC_IS_POTION                   1415
#define IDC_STONE_IMMUNE                1415
#define IDC_REGEN_CHANCE                1416
#define IDC_IS_DRUG                     1416
#define IDC_FREEZE_IMMUNE               1416
#define IDC_UPKEEP_DOOR_TIME            1417
#define IDC_IS_FLOWER                   1417
#define IDC_NOCK_BACK_IMMUNE            1417
#define IDC_TEXT_DOOR_DURABILITY        1418
#define IDC_IS_CANDY                    1418
#define IDC_REVISE_INT_CALC             1418
#define IDC_DOOR_DURABILITY             1419
#define IDC_ULTRA_ITEM                  1419
#define IDC_P_DAMAGE_IMMUNE             1419
#define IDC_TEXT_DOOR_DEFENSE           1420
#define IDC_BLOCK_TO_ENCHANT            1420
#define IDC_M_DAMAGE_IMMUNE             1420
#define IDC_ITEM_NOT_USE_PET            1420
#define IDC_TEXT_DOOR_MAGIC_RESISTANCE  1421
#define IDC_CONFUSE_IMMUNE              1421
#define IDC_TEXT_DOOR_DEFENSE_PERCENT   1421
#define IDC_OCCUR_EAT_EFFECT            1421
#define IDC_TEXT_DESTROY_MIN_LEVEL      1422
#define IDC_USE_TO_MINI_PET             1422
#define IDC_CAN_NOT_TAME                1422
#define IDC_TEXT_DOOR_TRAP_LEVEL        1423
#define IDC_REMEBER_PLACE_0             1423
#define IDC_TEXT_DOOR_REGEN_PERIOD      1424
#define IDC_REMEBER_PLACE_1             1424
#define IDC_TEXT_REGEN_CHANCE           1425
#define IDC_REMEBER_PLACE_2             1425
#define IDC_TEXT_UPKEEP_DOOR_TIME       1426
#define IDC_ADD_GUILD_INFO_REMAIN_GAIN_LOG 1426
#define IDC_TEXT_UPKEEP_DOOR_TIME_MINUTE 1427
#define IDC_IS_NOT_CONSUME              1427
#define IDC_TEXT_DOOR_SECRET_LEVEL      1428
#define IDC_USE_TO_ENEMY                1428
#define IDC_DOOR_SECRET_LEVEL           1429
#define IDC_IS_NOT_GET_USED_SKILL       1429
#define IDC_TEXT_DOOR_LOCK_LEVEL        1430
#define IDC_IS_NOT_USE_TO_GVG           1430
#define IDC_DOOR_LOCK_LEVEL             1431
#define IDC_TEXT_UNLOCK_UPKEEP_TIME     1432
#define IDC_DOOR_DESTROY_ABLE           1433
#define IDC_DOOR_TRAP_SKILL             1434
#define IDC_TEXT_DOOR_TRAP_SKILL        1435
#define IDC_TEXT_DOOR_TRAP_SKILL_LEVEL  1436
#define IDC_DOOR_TRAP_SKILL_LEVEL       1437
#define IDC_TEXT_DOOR_DETECT_TRAP_LEVEL 1438
#define IDC_DOOR_DETECT_TRAP_LEVEL      1439
#define IDC_TEXT_DOOR_DISARM_TRAP_LEVEL 1440
#define IDC_DOOR_DISARM_TRAP_LEVEL      1441
#define IDC_TEXT_DOOR_TRAP_STRENGTH     1442
#define IDC_DOOR_TRAP_STRENGTH          1443
#define IDC_TEXT_DOOR_TRAP_INTELLIGENCE 1444
#define IDC_DOOR_TRAP_INTELLIGENCE      1445
#define IDC_FRAME_DOOR                  1446
#define IDC_MIN_PROPRIETY_LEVEL         1447
#define IDC_BEGIN_NPC_FIELD             1448
#define IDC_TRAP_SKILL2_CHANCE          1448
#define IDC_ARCA_LIST                   1450
#define IDC_UPDATE                      1451
#define IDC_ARCA_FRAME                  1452
#define IDC_TEXT_TRAP_SKILL1            1453
#define IDC_TEXT_TRAP_SKILL2            1454
#define IDC_TRAP_SKILL1_LIST            1455
#define IDC_TEXT_TRAP_SKILL1_CHANCE     1456
#define IDC_TEXT_TRAP_SKILL2_CHANCE     1457
#define IDC_TEXT_TRAP_LEVEL             1458
#define IDC_TEXT_TRAP_DETECT_LEVEL      1459
#define IDC_TRAP_DETECT_LEVEL           1460
#define IDC_TRAP_TRAGET_TEXT            1461
#define IDC_TRAP_TRAGET                 1462
#define IDC_TEXT_DOOR_REGEN_CHANCE      1464
#define IDC_DOOR_REGEN_CHANCE           1465
#define IDC_TEXT_DOOR_DESTROY_MIN_LEVEL 1466
#define IDC_DOOR_DESTROY_MIN_LEVEL      1467
#define IDC_DOOR_TEXT_UNLOCK_UPKEEP_TIME2 1468
#define IDC_DOOR_UNLOCK_UPKEEP_TIME     1469
#define IDC_DOOR_TRAGET                 1470
#define IDC_DOOR_TRAP_SKILL1_TEXT       1471
#define IDC_DOOR_TRAP_SKILL1            1472
#define IDC_DOOR_TRAP_SKILL1_ACTIVE_CHANCE_TEXT 1473
#define IDC_DOOR_TRAP_SKILL1_ACTIVE_CHANCE 1474
#define IDC_DOOR_TRAP_SKILL2_TEXT       1476
#define IDC_DOOR_TRAP_SKILL2            1477
#define IDC_DOOR_TRAP_SKILL2_ACTIVE_CHANCE_TEXT 1478
#define IDC_DOOR_TRAP_SKILL2_ACTIVE_CHANCE 1479
#define IDC_REMOVE_SET_EFFECT           1483
#define IDC_ADD_SET_EFFECT              1484
#define IDC_EFFECT_LIST                 1485
#define IDC_SET_ITEM_LIST               1486
#define IDC_EDIT_SET_EFFECT             1487
#define IDC_IS_SET_ITEM                 1487
#define IDC_ADD_PIECE_ITEM              1489
#define IDC_EDIT_PIECE_ITEM             1490
#define IDC_REMOVE_PIECE_ITEM           1491
#define IDC_PIECE_ITEM_LIST             1492
#define IDC_ITEM_PIECE_LIST             1493
#define IDC_PIECE_LIST                  1494
#define IDC_LOADING                     1494
#define IDC_EDIT_PIECE                  1497
#define IDC_SET_ITEM                    1498
#define IDC_MAKE_ITEM                   1499
#define IDC_PIECE_COUNT                 1500
#define IDC_IS_REGEN_MONSTER            1502
#define IDC_ID_LIST                     1503
#define IDC_FLOOR_LIST                  1504
#define IDC_FLOOR_COUNT                 1505
#define IDC_EDIT_FLOOR                  1506
#define IDC_GUILD_DUNGEON_SERIAL        1508
#define IDC_DOOR_LINK_SECRET_DUNGEON_TEXT 1509
#define IDC_IS_RETURN                   1510
#define IDC_FRAME_CONDITION             1511
#define IDC_STATIC_STATUS_LIST          1512
#define IDC_STATIC_DIALOG               1513
#define IDC_ADD_TO_CHAPTER              1516
#define IDC_MODIFY_CHAPTER_NAME         1517
#define IDC_REMOVE_SELECT_CHAPTER       1518
#define IDC_BOOK_LIST                   1520
#define IDC_CATEGORY_LIST               1521
#define IDC_PAGE_CONTENTS               1522
#define IDC_ITEM_COMMENT                1523
#define IDC_CATEGORY_NAME               1525
#define IDC_ADD_CATEGORY                1526
#define IDC_MODIFY_CATEGORY             1527
#define IDC_REMOVE_CATEGORY             1528
#define IDC_BOOK_NAME                   1529
#define IDC_ADD_BOOK                    1530
#define IDC_MODIFY_BOOK_NAME            1531
#define IDC_REMOVE_BOOK                 1532
#define IDC_CHAPTER_LIST                1533
#define IDC_PAGE_LIST                   1533
#define IDC_IS_DEFAULT_CATEGORY         1534
#define IDC_IS_DEFAULT_PAGE             1535
#define IDC_UP_KARAM                    1535
#define IDC_ADD_PAGE                    1536
#define IDC_DOWN_KARAM                  1536
#define IDC_MODIFY_PAGE                 1537
#define IDC_IS_TEST                     1537
#define IDC_REMOVE_PAGE                 1538
#define IDC_PATTERN_LIST                1538
#define IDC_IS_TOWER_OF_ORDEAL          1538
#define IDC_CATEGORY_VALUE              1539
#define IDC_PATTERN_SCRIPT              1539
#define IDC_IS_GUILD_DUNGEN             1539
#define IDC_PAGE_VALUE                  1540
#define IDC_PASTE_CONTENTS              1540
#define IDC_APPLY_ITEM_COMMENT          1541
#define IDC_MODIFY_CONTENTS             1541
#define IDC_INSERT_PAGE                 1542
#define IDC_CAN_NOT_FEED_TO_PET         1542
#define IDC_IS_BLOCK_TRADE_PAGE         1543
#define IDC_FREE_TELEPORT               1543
#define IDC_IS_BLOCK_TRADE_BOOK         1544
#define IDC_DUEL_POINT_SHOP             1544
#define IDC_REQUEST_SUMMON_CARPET       1544
#define IDC_IS_BLOCK_DESTROY_BOOK       1545
#define IDC_FREE_PAST_PORTAL            1545
#define IDC_NOT_BUY_ITEM                1545
#define IDC_IS_BLOCK_DESTROY_PAGE       1546
#define IDC_MYSTIC_STONE_ADD_GAIN       1546
#define IDC_IS_BLOCK_STORE_BANK_BOOK    1547
#define IDC_TANTILIS_RELIC_ADD_GAIN     1547
#define IDC_IS_BLOCK_STORE_BANK_PAGE    1548
#define IDC_COMBO_TOKKEN                1548
#define IDC_IGNORE_GUILD_HALL_LEVEL_FOR_ENTRY_TANTALIS_EXILE 1548
#define IDC_IS_SET_BOSS_MONSTER         1549
#define IDC_INCREASE_INFINITY_SERIOUS_UPGRADE_CHANCE 1549
#define IDC_IS_SET_BOSS_MAP             1550
#define IDC_TREE1                       1550
#define IDC_HALF_PAST_PORTAL            1550
#define IDC_IS_FIND_WAY                 1551
#define IDC_TREE                        1551
#define IDC_ETERNAL_ITEM_UPGRADE_NOT_PENALTY 1551
#define IDC_CAN_SUMMON_CARPET           1552
#define IDC_STATIC_SEASON               1553
#define IDC_IS_GUILD_DUNGEON_MAP        1553
#define IDC_UPGRADE_MATERIALS_ITEM      1553
#define IDC_LEVEL_PER_GOLD_SHOP         1554
#define IDC_STATIC_SWAP_AREA            1554
#define IDC_USE_SHOP                    1554
#define IDC_SHOP_PRICE_FACTOR2          1555
#define IDC_AB_TRIGGER                  1555
#define IDC_USE_BANK                    1555
#define IDC_USE_TOKKEN_SHOP             1556
#define IDC_USE_PREMIUM_INVENTORY       1556
#define IDC_UNIQUE_DATA_DOWN            1557
#define IDC_UNIQUE_DATA_UP              1558
#define IDC_GB_ITEM_CLASS               1559
#define IDC_GB_ITEM_PROPERTIES          1560
#define IDC_GB_ITEM_TARGET              1561
#define IDC_GB_ITEM_OTHERS              1562
#define IDC_GB_LOG                      1563
#define IDC_GB_PREMIUM_ITEM             1564
#define IDC_LB_CHECK_DATA               1565
#define IDC_STATIC_ITEM_CHECK_DATA      1568
#define IDC_GB_ITEM_CHECK_DATA          1569
#define IDC_AREA_CHECK_NPC              1570
#define IDC_LIMIT_WARRIOR               1571
#define IDC_LIMIT_KNIGHT                1572
#define IDC_LIMIT_WIZARD                1573
#define IDC_LIMIT_WEREWOLF              1574
#define IDC_LIMIT_PRIEST                1575
#define IDC_LIMIT_FALLEN_ANGEL          1576
#define IDC_LIMIT_ROGUE                 1577
#define IDC_LIMIT_FIGHTER               1578
#define IDC_LIMIT_MAGIC_LANCER          1579
#define IDC_LIMIT_MAGIC_ARCHER          1580
#define IDC_LIMIT_BEAST_TAMER           1581
#define IDC_LIMIT_SUMMONER              1582
#define IDC_LIMIT_MAGICAL_GIRL          1583
#define IDC_LIMIT_PRINCESS              1584
#define IDC_LIMIT_NECROMANCER           1585
#define IDC_LIMIT_DEVIL                 1586
#define IDC_SLIDER_NPC_DATA             1587
#define IDC_LIST_NPC                    1588
#define IDC_NPC_INFO                    1589
#define IDC_NPC_SPEECH                  1590
#define IDC_LIMIT_SOUL_TAKER            1591
#define IDC_SLIDER_MONSTER_DATA         1592
#define IDC_LIMIT_OPTICALIST            1592
#define IDC_MONSTER_DEATH               1593
#define IDC_KARMA_MONSTERVIEW           1594
#define IDC_MONSTER_BASEDATA            1595
#define IDC_MONSTE_GENERALDATA          1596
#define IDC_MONSTER_JOB                 1596
#define IDC_FIND_LIST                   1597
#define IDC_COPY_CONTENTS               1598
#define IDC_SAVE_CONTENTS_SPEECH        1599
#define IDC_SAVE_KARMA                  1600
#define IDC_OK                          1601
#define ICD_CANCEL                      1602
#define IDC_CANCEL                      1602
#define IDC_DOWN_KARMA                  1603
#define IDC_UP_KARMA                    1604
#define IDC_SLIDER_R                    1605
#define IDC_SLIDER_G                    1606
#define IDC_SLIDER_B                    1607
#define IDC_SAMPLE_COLOR                1608
#define IDC_SAMPLE_TEXT                 1609
#define IDC_STATIC_INDEX                1610
#define IDC_STATIC_SYEAR                1611
#define IDC_CB_START_MONTH              1612
#define IDC_STATIC_SMONTH               1613
#define IDC_LIMIT_CHAMPION              1613
#define IDC_CB_START_DAY                1614
#define IDC_LIMIT_BEAST_MAN             1614
#define IDC_COMPARE                     1614
#define IDC_STATIC_SDAY                 1615
#define IDC_EXIT                        1615
#define IDC_CB_START_HOUR               1616
#define IDC_STATIC_SHOUR                1617
#define IDC_SELECTED_SECOND_FILE_PATH   1617
#define IDC_CB_START_MINUTE             1618
#define IDC_STATUS_SIMPLE_INFO          1618
#define IDC_STATIC_SMINUTE              1619
#define IDC_STATIC_TIME                 1620
#define IDC_STATIC_EYEAR                1621
#define IDC_CB_END_MONTH                1622
#define IDC_STATIC_EMONTH               1623
#define IDC_CB_END_DAY                  1624
#define IDC_STATIC_EDAY                 1625
#define IDC_CB_END_HOUR                 1626
#define IDC_STATIC_EHOUR                1627
#define IDC_CB_END_MINUTE               1628
#define IDC_STATIC_EMINUTE              1629
#define IDC_STATIC_HUNTING_ICON         1630
#define IDC_STATIC_HUNTING_LEVEL        1631
#define IDC_STATIC_GENERATE_METHOD      1631
#define IDC_TRAP_SKILL1_CHANCE          2012
#define IDC_DOOR_TEXT_UNLOCK_UPKEEP_TIME 2111
#define IDC_DOOR_TRAGET_TEXT            2222
#define IDC_DOOR_TRAP_SKILL1_ACTIVE_CHANCE_TEXT2 2473
#define IDC_DOOR_TRAP_SKILL2_ACTIVE_CHANCE_TEXT2 2478
#define IDC_UPGRADE_LEVEL1              8101
#define IDC_UPGRADE_LEVEL2              8102
#define IDC_UPGRADE_LEVEL3              8103
#define IDC_UPGRADE_LEVEL4              8104
#define IDC_UPGRADE_LEVEL5              8105
#define IDC_UPGRADE_LEVEL6              8106
#define IDC_UPGRADE_JOB1                9111
#define IDC_UPGRADE_JOB2                9112
#define IDC_UPGRADE_JOB3                9113
#define IDC_UPGRADE_JOB4                9114
#define IDC_UPGRADE_JOB5                9115
#define IDC_UPGRADE_JOB6                9116
#define IDM_NEW_MAP                     40001
#define IDM_NEW_PROJECT                 40002
#define IDM_SAVE_PROJECT                40003
#define IDM_LOAD_PROJECT                40004
#define IDM_SET_PROJECT                 40005
#define IDM_LOAD_MAP                    40006
#define IDM_SAVE_MAP                    40008
#define IDM_SAVEMAP_AS                  40009
#define IDM_ADD_MAP                     40011
#define IDM_SAVE_MAPS                   40012
#define IDM_RESET_MAP                   40013
#define IDM_SET_MAP                     40014
#define IDM_EXIT                        40017
#define IDM_GLOBAL_KARMA                40018
#define IDM_SET_KARMA                   40018
#define IDM_SET_SHOP                    40018
#define IDM_KARMA                       40019
#define IDM_KARMA_VALUE                 40021
#define IDM_SET_QUEST                   40022
#define IDM_SET_BASIC_ITEM              40023
#define IDM_JOB                         40024
#define IDM_DUNGEON                     40025
#define IDM_ITEM_PREFIX                 40026
#define IDM_EXPORT_MINIMAP_IMAGE_50     40027
#define IDM_SCALE_100                   40028
#define IDM_SCALE_45                    40030
#define IDM_SCALE_35                    40032
#define IDM_SCALE_50                    40033
#define IDM_SCALE_40                    40034
#define IDM_SCALE_30                    40035
#define IDM_SCALE_20                    40036
#define IDM_SCALE_10                    40037
#define IDM_SCALE_5                     40038
#define IDM_SCALE_25                    40039
#define IDM_SCALE_15                    40040
#define IDM_EDIT_DIALOG                 40041
#define IDM_LINK_ALL_MAP_GATE           40042
#define IDM_COMPARE_MAP                 40043
#define IDM_LINK_ALL_MAP_GATE_AND_SAVE  40044
#define IDM_RESAVE_ALL_FIELD            40045
#define IDM_REBUILD_CRASH_INFO          40046
#define IDM_CUSTOM_ITEM                 40047
#define IDM_SET_PREMIUM_ITEM            40048
#define IDM_FILL_SELECT_TILE            40049
#define IDM_EXPORT_ALL_MAP_TEXT         40050
#define IDM_EXPORT_ALL_TEXT             40050
#define IDM_LOCALIZING                  40051
#define IDM_COMPARE_TEXT                40052
#define IDM_UPDATE_NEW_TEXT             40053
#define IDM_EXPORT_MONSTER_INFO         40054
#define IDM_SYNC_TEXT                   40055
#define IDM_GLOBAL_CUSTOM_ITEM          40056
#define IDM_SET_ARACA                   40057
#define IDM_EXPORT_ITEM_INFO            40058
#define IDM_EXPORT_SHOP_INFO            40059
#define IDM_OPERATE_TEMPLATE_WORK       40060
#define IDM_SETITEM                     40061
#define IDM_SET_PIECEITEM               40062
#define IDM_SET_ID                      40063
#define IDM_CORRECT_TILE                40064
#define IDM_EXPORT_EXP                  40065
#define IDM_LOCALIZING_PART             40066
#define IDM_SET_BOOK                    40067
#define IDM_MAIN_QUEST                  40068
#define IDM_EXPORT_NPC_INFO             40069
#define IDM_CHECK_TEXT                  40070
#define IDM_COMMAND                     40072
#define IDM_EXPORT_SOME_MAP             40073
#define IDM_EXPORT_MINIMAP_IMAGE_25     40074
#define IDM_CHARACTER_PATTERN           40075
#define IDM_GET_LOCK                    40076
#define IDM_RELEASE_LOCK                40077
#define IDM_UPDATE_CURRENT_FILE         40078
#define IDM_COMMIT                      40079
#define IDM_SET_PROJECT_KARMA           40082
#define IDM_EXPORT_MAP_LIST             40083
#define IDM_SET_PROJECT_KARMA_MONSTER_GEN 40084
#define IDM_SET_CANNOT_MOVE_TILE        40085
#define IDM_VIEW_MINIMAP                40086
#define IDM_STATE_AUTO_SAVE             40087
#define IDM_EDIT_UNDO                   40088
#define IDM_EXPORT_KARMA                40089
#define IDM_EDIT_REDO                   40090
#define IDM_EXPORT_CURRENT_FIELD_NPC_INFO 40091
#define IDM_EXPORT_MONSTER              40092
#define IDM_EXPORT_ACTOR                40093
#define IDM_EXPORT_FIELD                40094
#define IDM_EXPORT_AREA                 40095
#define IDM_EXPORT_ALLKARMA             40096
#define IDM_EDIT_NPC                    40097
#define IDM_EDIT_MONSTER                40098
#define IDM_SET_FONTCOLOR               40099
#define IDM_SET_AREA_EDIT               40100
#define IDM_HELP                        40101
#define IDM_EXPORT_ALL_MAP_ITEM_DROP_INFO 40102
#define IDM_MOVE_FIELD                  40103
#define IDM_MINIMAP_AREA                40104
#define IDM_MINIMAP_ACTOR               40105
#define IDM_COMPARE                     40106
#define IDM_SAVE_PROJECT_QUICK          41003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40103
#define _APS_NEXT_CONTROL_VALUE         1614
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
