#ifndef _classITEM_EFFECT_DEFINE_
#define _classITEM_EFFECT_DEFINE_

#include "SFC.H"




#define	dACL_OPTION_SHIELD_FORMULA1(x)					(1 + ( (x) * 0.5 ))
#define	dACL_OPTION_SHIELD_FORMULA2(x)					(20 + (x))
#define	dACL_OPTION_CHARGE_FORMULA1(x)					(8-((x) * 0.1))
#define	dACL_OPTION_CHARGE_FORMULA2(x)					((x) * 3)
#define	dACL_OPTION_INCREASE_EXP_FORMULA(x)				(5 + (x))
#define	dACL_OPTION_ADD_FIRE_DAMAGE(x)					(100 + ((x) * 200))
#define	dACL_OPTION_INCREASE_ALL_STATUS(x)				(10 + (x) * 2)
#define	dACL_OPTION_SOUL_GUARD(x)						(3 + ((x) * 0.3))
#define	dACL_OPTION_TRANSFORMAION_REPTILE_FORMULA1(x)	((x) * 10)
#define	dACL_OPTION_TRANSFORMAION_REPTILE_FORMULA2(x)	(1 + (x))
#define	dACL_OPTION_INCREASE_ATTACK_POWER_FORMULA1(x)	(5 + (x))
#define	dACL_OPTION_INCREASE_ATTACK_POWER_FORMULA2(x)	(10 + (x) * 2)
#define	dACL_OPTION_INCREASE_MAX_HP_FORMULA1(x)			(100 + (x) * 50)





enum
{
eIE_ADD_DEFENSE_POWER						,
eIE_BLOCKING_RATE							,
eIE_BELT_STACK_COUNT						,
eIE_FREE_RARE_OPTION						,






eIE_RECOVER_HP								,
eIE_RECOVER_HP_PERCENTAGE					,
eIE_RECOVER_CP								,
eIE_RECOVER_CP_PERCENTAGE					,
eIE_RECOVER_HP_CP							,
eIE_RECOVER_HP_CP_PERCENTAGE				,
eIE_RESURRECTION							,
eIE_SELF_RESURRECTION						,
eIE_HEAL_STRANGE_STATUS						,
eIE_RECOVER_ALL_STRANGE_STATUS				,
eIE_RECOVER_ALL_DECLINE_STATUS				,
eIE_RECOVER_ALL_CURSE_STATUS				,
eIE_RECOVER_ALL_BADSTATUS					,
eIE_HEAL_POSION								,
eIE_SHORT_WHILE_INCREASE_POWER				,
eIE_SHORT_WHILE_INCREASE_AGILITY			,
eIE_SHORT_WHILE_INCREASE_CONSTITUTION		,
eIE_SHORT_WHILE_INCREASE_WISDOM				,
eIE_SHORT_WHILE_INCREASE_INTELIGENCE		,
eIE_SHORT_WHILE_INCREASE_CHARISMA			,
eIE_SHORT_WHILE_INCREASE_LUCK				,
eIE_SHORT_WHILE_INCREASE_ATTACK_POWER		,
eIE_SHORT_WHILE_INCREASE_DEFENSE_POWER		,
eIE_SHORT_WHILE_INCREASE_HP					,
eIE_SHORT_WHILE_INCREASE_CP					,
eIE_SHORT_WHILE_SET_MAX_DAMAGE				,
eIE_SHORT_WHILE_SET_MAX_CP					,





eIE_OPEN_ARCA								,
eIE_OPEN_DOOR								,
eIE_OPEN_ARCA_AND_DOOR						,
eIE_ONE_WAY_PORTAL							,
eIE_PORTAL									,
eIE_USE_JEWEL								,






eIE_INSTANCE_KILL							,
eIE_MAKE_BERSERKER							,
eIE_MAKE_ARMOR_BREAK						,
eIE_MAKE_WEAPON_BREAK						,
eIE_MAKE_POISONED							,
eIE_MAKE_CONFUSE							,
eIE_MAKE_CHARMING							,
eIE_MAKE_STUN								,
eIE_MAKE_COLD								,
eIE_HIT_FIRE_DAMAGE						,
eIE_HIT_WATER_DAMAGE						,
eIE_HIT_WIND_DAMAGE						,
eIE_HIT_TERRA_DAMAGE						,
eIE_HIT_LIGHT_DAMAGE						,
eIE_HIT_DARK_DAMAGE						,
eIE_ADD_DAMAGE_TO_UNDEAD					,
eIE_ADD_DAMAGE_TO_DEMON						,
eIE_ADD_DAMAGE_TO_HUMAN						,
eIE_ADD_DAMAGE_TO_ANIMAL					,
eIE_ADD_DAMAGE_TO_HOLY_ANIMAL				,





eIE_DECREASE_RELOAD_TIME					,
eIE_INCREASE_TRANSFORMATION_SPEED			,
eIE_INCREASE_RECOVER_SPEED					,
eIE_RETURN_DAMAGE							,
eIE_INFINITY_BULLET							,





eIE_INCREASE_MELEE_JOB_ATTACK_POWER			,
eIE_INCREASE_POWER							,
eIE_INCREASE_WISDON							,
eIE_INCREASE_INTELIGENCE					,
eIE_INCREASE_CONSTITUTION					,
eIE_INCREASE_AGILITY						,
eIE_INCREASE_CHARISMA						,
eIE_INCREASE_LUCK							,
eIE_INCREASE_CRITICAL						,
eIE_INCREASE_CRUSH_SHOT						,
eIE_INCREASE_HIT_RATE						,
eIE_INCREASE_CONCENTRATION					,
eIE_INCREASE_ATTACK_SPEED					,






eIE_RESISTANCE_CURSE_STATUS					,
eIE_RESISTANCE_DECLINE_STATUS				,
eIE_RESISTANCE_STRANGE_STATUS				,
eIE_RESISTANCE_ALL_BAD_STATUS				,
eIE_INCREASE_FIRE_RESITANCE					,
eIE_INCREASE_TERRA_RESITANCE				,
eIE_INCREASE_WIND_RESITANCE					,
eIE_INCREASE_WATER_RESITANCE				,
eIE_INCREASE_LIGHT_RESITANCE				,
eIE_INCREASE_DARK_RESITANCE					,
eIE_INCREASE_FOUR_ELEMENTAL_RESITANCE		,
eIE_INCREASE_MAGIC_RESITANCE				,
eIE_INCREASE_NOCK_BACK_RESISTANCE			,
eIE_INCREASE_CRITICAL_RESISTANCE			,
eIE_INCREASE_CRUSH_SHOT_RESISTANCE			,
eIE_INCREASE_INSTANCE_KILL_RESISTANCE		,





eIE_INCREASE_MAGIC_LANCER_SKILL				,
eIE_INCREASE_MAGIC_ARCHER_SKILL				,
eIE_INCREASE_KNIGHT_SKILL					,
eIE_INCREASE_WARRIOR_SKILL					,
eIE_INCREASE_WIZARD_SKILL					,
eIE_INCREASE_WEREWOLF_SKILL					,
eIE_INCREASE_THIEF_SKILL					,
eIE_INCREASE_FIGHTER_SKILL					,
eIE_INCREASE_BEAST_TAMER_SKILL				,
eIE_INCREASE_SUMMONER_SKILL					,
eIE_INCREASE_PRINCESSE_SKILL				,
eIE_INCREASE_MAGICAL_GIRL_SKILL				,
eIE_INCREASE_PRIEST_SKILL					,
eIE_INCREASE_FALLEN_ANGEL_SKILL				,
eIE_INCREASE_NECROMANCER_SKILL				,
eIE_INCREASE_DEMON_SKILL					,
eIE_INCREASE_FEMALE_SKILL_LEVEL				,
eIE_INCREASE_MALE_SKILL_LEVEL				,
eIE_INCREASE_SKILL_LEVEL					,



eIE_INCREASE_DODGE_CHANCE					,
eIE_MAKE_CHARMING_30						,
eIE_MAKE_COLD_100							,



eIE_GROW_STRENGTH							,
eIE_GROW_AGILITY							,
eIE_GROW_CONSTITUTION						,
eIE_GROW_WISDOM								,
eIE_GROW_INTELLIGENCE						,
eIE_GROW_CHARISMA							,
eIE_GROW_LUCK								,
eIE_GROW_HP									,
eIE_GROW_CP									,
eIE_INCREASE_WEAPON_DAMAGE					,
eIE_INCREASE_ARMOR_DEFENSE					,
eIE_MAGIC_JEWEL								,





eIE_RETURN_DAMAGE_40						,
eIE_FRONTIER_SCROLL							,
eIE_RARE_ITEM_LOTTERY_TICKET				,
eIE_UNIQUE_ITEM_LOTTERY_TICKET				,
eIE_SUPER_ITEM_LOTTERY_TICKET				,

eIE_RESET_SKILL_POINT						,
eIE_RESET_STATE_POINT						,
eIE_CHANGE_ITEM_PREFIX_2003_11_01			,
eIE_CHANGE_ITEM_PREFIX_2003_11_17			,

eIE_ORB_OF_SANTA								,
eIE_SHORT_WHILE_INCREASE_ATTACK_POWER_BY_MINUTE	,
eIE_SHORT_WHILE_INCREASE_DEFENSE_POWER_BY_MINUTE,
eIE_SHORT_WHILE_INCREASE_HP_BY_MINUTE			,
eIE_SHORT_WHILE_INCREASE_CP_BY_MINUTE			,
eIE_SHORT_WHILE_SET_MAX_DAMAGE_BY_MINUTE		,
eIE_SHORT_WHILE_SET_MAX_CP_BY_MINUTE			,
eIE_SHORT_WHILE_INCREASE_POWER_BY_MINUTE		,
eIE_SHORT_WHILE_INCREASE_AGILITY_BY_MINUTE		,
eIE_SHORT_WHILE_INCREASE_CONSTITUTION_BY_MINUTE	,
eIE_SHORT_WHILE_INCREASE_WISDOM_BY_MINUTE		,
eIE_SHORT_WHILE_INCREASE_INTELIGENCE_BY_MINUTE	,
eIE_SHORT_WHILE_INCREASE_CHARISMA_BY_MINUTE		,
eIE_SHORT_WHILE_INCREASE_LUCK_BY_MINUTE			,
eIE_OVER_POWER_ITEM_EQUIP						,
eIE_MEMORY_STONE								,
eIE_TELEPORT_STONE								,
eIE_PERFECT_RESSURECTION						,
eIE_CALL_MAGIC_CARPET							,
eIE_SHORT_WHILE_INCREASE_ATTACK_POWER_BY_MINUTE_10	,
eIE_SHORT_WHILE_INCREASE_DEFENSE_POWER_BY_MINUTE_10	,
eIE_INCREASE_LEVEL								,
eIE_EVENT_2004_01_21							,
eIE_CHANGE_MAGIC_CARPET_SHAPE				,

eIE_JIM_MORYS_ENCHANT						,
eIE_UNSKILLED_REPAIR_BROKEN_ITEM			,
eIE_ENCHANT_ITEM_BY_UNIQUE_INFO				,

eIE_REPAIR_BROKEN_ITEM						,
eIE_CURE_ITEM_EQUIP_CURSE					,
eIE_RELEASE_ATTACH_PREFIX_CURSE				,

eIE_OX_QUIZ_TICKET							,
eIE_INCREASE_SITDOWN_RECOVER_HP_SPEED		,

eIE_CREATE_GUILD							,
eIE_GUILD_LEVEL_UP							,


eIE_GS_EXPAND_PACK							,
eIE_GS_SPECIAL_PACK							,
eIE_GS_LUXURY_PACK							,
eIE_GS_HANGUL_PACK							,
eIE_GS_ENGLISH_PACK							,
eIE_GS_HANMUN_PACK							,
eIE_GS_ITEM_PACK							,
eIE_GS_ANIMAL_PACK							,

eIE_PS_SIGNBOARD1							,
eIE_PS_COLOR_TEXT							,
eIE_PS_BOLD_TEXT							,
eIE_PS_EXPAND_TEXT_BUFFER					,
eIE_PS_TWINKLE								,
eIE_PS_PACK									,
eIE_PS_SIGNBOARD2							,
eIE_PS_SIGNBOARD3							,
eIE_PS_SIGNBOARD4							,
eIE_PS_SIGNBOARD5							,
eIE_PS_LOUD_SPEAKER							,

eIE_NORMAL_ITEM_LOTTERY_TICKET				,

eIE_WEAKNING_TARGET_FIRE_RESISTANCE			,
eIE_WEAKNING_TARGET_WATER_RESISTANCE		,
eIE_WEAKNING_TARGET_WIND_RESISTANCE			,
eIE_WEAKNING_TARGET_EARTH_RESISTANCE		,
eIE_WEAKNING_TARGET_LIGHT_RESISTANCE		,
eIE_WEAKNING_TARGET_DARK_RESISTANCE			,
eIE_WEAKNING_TARGET_MAGIC_RESISTANCE		,
eIE_STRENGTHENING_FIRE_DAMAGE				,
eIE_STRENGTHENING_WATER_DAMAGE				,
eIE_STRENGTHENING_WIND_DAMAGE				,
eIE_STRENGTHENING_EARTH_DAMAGE				,
eIE_STRENGTHENING_LIGHT_DAMAGE				,
eIE_STRENGTHENING_DARK_DAMAGE				,
eIE_STRENGTHENING_MAGIC_DAMAGE				,

eIE_BREEDING_RECORD							,
eIE_LOTTERY_ITEM							,
eIE_CHARGE_EXTRA_ITEM_POWER					,

eIE_REGEN_HP_ON_MAGIC_CARPET				,
eIE_NOT_DOWN_CP_ON_MAGIC_CARPET				,
eIE_INCREASE_MOVE_SPEED_ON_MAGIC_CARPET		,
eIE_FIGHT_MAGIC_CARPET						,

eIE_EXPAND_INVENTORY_BAG					,
eIE_REPAIR_DX_ITEM_KIT						,


eIE_ITEM_PIECE								,
eIE_SECRET_DUNGEON_KEY						,

eIE_REMOVE_PREFIX							,

eIE_JUMP_FIELD_USE_WORLD_MAP				,
eIE_PUT_VERTICAL_BANNER						,
eIE_PUT_HORIZON_BANNER						,

eIE_TREASURE_MAP							,

eIE_SHORT_WHILE_INCREASE_LUCKx100_BY_MINUTE	,
eIE_RESET_GUILD_SKILL_POINT					,
eIE_PORTAL_STONE							,
eIE_COUPLE_RING_SET							,
eIE_COUPLE_RING								,
eIE_MIX_ITEM_BOX							,
eIE_FIRE_WORK								,
eIE_RANDOM_FIRE_WORK						,
eIE_INCREASE_SELECT_POWER					,
eIE_PRESENT_COUPLE_RING						,
eIE_NOT_DEFINE_COUPLE_COUPLE_RING			,

eIE_ADD_CATEGORY							,
eIE_ADD_PAGE								,
eIE_BOOK									,
eIE_PRINCESS_WEAPON							,

eIE_GUILD_HALL_PORTAL						,

eIE_SUMMON_GUILD_GUARDIAN					,

eIE_GUILD_STATUE_PIECE_EXPORTER				,
eIE_GUILD_STATUE_PIECE						,
eIE_TRANS_TO_OPERATOR						,


eIE_INC_LAST_DAMAGE							,
eIE_INC_HUNT_EXP							,
eIE_INC_HUNT_ITEM_DROP_CHANCE				,
eIE_CLEAR_DEATH_PENELTY						,

eIE_INCREASE_MOVE_SPEED						,
eIE_EVENT_BALLOON							,
eIE_SELECT_ITEM_IN_ITEM_PACK				,
eIE_INCREASE_FINAL_DAMAGE					,


eIE_RECALL_MINIPET							,
eIE_EXTEND_MINIPET_TIME						,
eIE_EXTEND_ALL_MINIPET_TIME					,
eIE_SEAL_MINIPET							,
eIE_CHANGE_MINIPET_NAME						,
eIE_MINIPET_POUCH							,

eIE_FLAKE_OF_DOING_ONE						,
eIE_FEATHER_OF_THINKING_ONE					,
eIE_TOY_OF_SIN_AND_RIN						,

eIE_REVERSIBLE_FRAME						,


eIE_CH5_SELECT_UPGRADE_TITLE,
eIE_CH5_RELASE_REVERSION,
eIE_CH5_RESET_GUILD_SKILL_POINT		,
eIE_CH5_BONUS_HP_AMULET,
eIE_CH5_BONUS_CP_AMULET,
eIE_CH5_OVER_POWER_ITEM_EQUIP,

eIE_CH5_REVERSE_SKILL_POINT,
eIE_CH5_REVERSE_STATE_POINT,

eIE_CH5_REMOVE_PREFIX,

eIE_CH5_COPY_ITEM	,
eIE_CH5_UPGRADE_NORMAL_ITEM_PREFIX_POWER	,
eIE_CH5_IMPROVE_NORMAL_ITEM_POWER		,
eIE_CH5_UPGRADE_UNIQUE_ITEM_PREFIX_POWER	,
eIE_CH5_IMPROVE_UNIQUE_ITEM_POWER		,
eIE_CH5_MIX_ITEM_BOX					,
eIE_CH5_SELECT_ALLIGNMENT				,
eIE_TIME_STAMP							,
eIE_ADD_TITLE							,

eIE_HUNTING_EXP_BONUS					,

eIE_SET_BADGE							,
eIE_NAME_STONE							,
eIE_INCREASE_MOVE_SPEED_ON_MAGIC_CARPET_RED	,

eIE_DUEL_BUFF_FIRE		,
eIE_DUEL_BUFF_WATER		,
eIE_DUEL_BUFF_WIND		,
eIE_DUEL_BUFF_EARTH		,
eIE_SET_RUNE			,

eIE_MINIPET_AWAKEN50		,
eIE_MINIPET_AWAKEN100		,

eIE_GS_SIGNAL_PACK			,
eIE_GS_UNIQUE1_PACK			,
eIE_GS_UNIQUE2_PACK			,

eIE_RECOVER_HP2				,
eIE_RECOVER_CP2				,

eIE_CASTING_MAGIC			,

eIE_RESET_STRENGTH_STATE		,
eIE_RESET_AGILITY_STATE			,
eIE_RESET_CONSTITUTION_STATE	,
eIE_RESET_INTELLIGENCE_STATE	,
eIE_RESET_WISDOM_STATE			,
eIE_RESET_CHARISMA_STATE		,
eIE_RESET_LUCK_STATE			,

eIE_USE_WORLD_MAP_TELEPORT		,
eIE_PERFECT_PARTY_REVIVE		,
eIE_INCREASE_SECRET_DUNGEON_PLAY_COUNT	,
eIE_INCREASE_GAIN_MINIPET_EXP	,
eIE_EQUIP_INCREASE_MOVE_SPEED	,

eIE_INSTANCE_RECOVER_HP_PERCENTAGE		,
eIE_INSTANCE_RECOVER_HPx100			,
eIE_INCREASE_GUILD_DUNGEON_PLAY_COUNT,

eIE_CHANGE_PET_NAME,

eIE_SOUND_OF_LEADERS_BELL,

eIE_AB_PH_DAMAGE		,

eIE_REFLECTING_MIXER	,
eIE_CHAIN_OF_RESTRAINT	,
eIE_SEAL_SPHERE_OF_DAWN	,

eIE_HIT_FIRE_DAMAGE_DX,
eIE_HIT_WATER_DAMAGE_DX,	
eIE_HIT_WIND_DAMAGE_DX,
eIE_HIT_TERRA_DAMAGE_DX,
eIE_HIT_LIGHT_DAMAGE_DX,
eIE_HIT_DARK_DAMAGE_DX,

eIE_INCREASE_SOUL_BRINGER_SKILL,
eIE_ATTACH_PREFIX				,
eIE_COPY_PREFIX				,
eIE_CUT_PREFIX				,

eIE_DECREASE_INSTANT_HP_PERCENTAGE		,

eIE_ATTACH_PREFIX_CAN_NOT_TRADE				,
eIE_COPY_PREFIX_CAN_NOT_TRADE				,
eIE_CUT_PREFIX_CAN_NOT_TRADE				,
eIE_EVENT_BALLOON_INC_ITEM_DROP_CHANCE		,
eIE_INCREASE_ALL_STATUS						,
eIE_INCREASE_FIX_SELECT_POWER				,
eIE_TRANSFORMATION_HUNTER				,
eIE_TRANSFORMATION_THIEF				,
eIE_TRANSFORMATION_MAGICIAN				,
eIE_SUMMON_MONSTER						,
eIE_CARVING_LEVEL							,
eIE_INCREASE_CARVING_LEVEL					,
eIE_SET_CARVING_LEVEL					,
eIE_ACL_SHIELD							,
eIE_ACL_CHARGE							,
eIE_ACL_INCREASE_EXP					,
eIE_ACL_ADD_FIRE_DAMAGE				,
eIE_ACL_INCREASE_ALL_STATUS				,
eIE_ACL_SOUL_GUARD						,
eIE_ACL_TRANSFORMATION_REPTILE			,
eIE_ACL_INCREASE_MAX_HP					,
eIE_ACL_INCREASE_ATTACK_POWER			,
eIE_ACL_HELL_PRISON						,
eIE_MINIPET_FEED						,
eIE_RESET_MINIPET_SKILL					,
eIE_SET_MINIPET_TYPE					,
eIE_ADD_MAX_HPx100						,
eIE_ADD_MAX_CPx100						,
eIE_ADD_DEFENSE_PERCENTAGE				,
eIE_ADD_MAX_HP_PERCENTAGE				,
eIE_ADD_MAX_CP_PERCENTAGE				,
eIE_CHANGE_HP							,
eIE_MOVE_FIELD							,
eIE_INCREASE_LEVEL_GETING_RED_STONE		,


};


enum
{
eIP_ADD_STRENGTH						,
eIP_ADD_AGILITY							,
eIP_ADD_CONSTITUTION					,
eIP_ADD_WISDOM							,
eIP_ADD_INTELIGENCE						,
eIP_ADD_CHARISMA						,
eIP_ADD_LUCK							,
eIP_FIXING_STRENGTH						,
eIP_FIXING_AGILITY						,
eIP_FIXING_CONSTITUTION					,
eIP_FIXING_WISDOM						,
eIP_FIXING_INTELLIGENCE					,
eIP_FIXING_CHARISMA						,
eIP_FIXING_LUCK							,
eIP_ADD_STRENGTH_BY_LEVEL				,
eIP_ADD_AGILITY_BY_LEVEL				,
eIP_ADD_CONSTITUTION_BY_LEVEL			,
eIP_ADD_WISDOM_BY_LEVEL					,
eIP_ADD_INTELIGENCE_BY_LEVEL			,
eIP_ADD_CHARISMA_BY_LEVEL				,
eIP_ADD_LUCK_BY_LEVEL					,
eIP_ADD_DAMAGE_PERCENTAGE				,
eIP_ADD_MIN_DAMAGE						,
eIP_ADD_MAX_DAMAGE						,
eIP_ADD_DEFENSE_PERCENTAGE				,
eIP_ADD_DEFENSE							,
eIP_ADD_MAX_HP_PERCENTAGE				,
eIP_ADD_MAX_HP							,
eIP_ADD_MAX_CP_PERCENTAGE				,
eIP_ADD_MAX_CP							,
eIP_LOW_CP								,
eIP_CORRECT_HIT_RATE					,
eIP_CORRECT_DODGE_RATE					,
eIP_SHIELD_BLOCK_RATE					,
eIP_CRITICAL_HIT						,
eIP_CRUSH_SHOT							,
eIP_IGNORE_TARGET_DODGE_ABILITY			,
eIP_IGNORE_ATTACKER_CORRECT_HIT_VALUE	,
eIP_PERFECT_HIT							,
eIP_BLOCKING_SPEED						,
eIP_MOVE_SPEED							,
eIP_ACTION_SPEED						,
eIP_POTION_HEAL_SPEED					,
eIP_ADD_CONCENTRATION					,
eIP_FIRE_DAMAGE							,
eIP_WATER_DAMAGE						,
eIP_WIND_DAMAGE							,
eIP_TERRA_DAMAGE						,
eIP_LIGHT_DAMAGE						,
eIP_DARK_DAMAGE							,
eIP_STEAL_HP							,
eIP_BONUS_CP							,
eIP_FLEE								,
eIP_KNOCK_OUT							,
eIP_INSTANT_KILL						,
eIP_WEAPON_BREAKER						,
eIP_ARMOR_BREAKER						,
eIP_MAKE_COLD							,
eIP_MAKE_FREEZE							,
eIP_MAKE_BLIND							,
eIP_MAKE_STUN							,
eIP_MAKE_STONE							,
eIP_MAKE_CONFUSE						,
eIP_MAKE_SLEEP							,
eIP_MAKE_CHARMING						,
eIP_MAKE_FIRST_TARGET					,
eIP_MAKE_AI_DOWN						,
eIP_MAKE_BERSERK						,
eIP_RESISTANCE_FIRE						,
eIP_RESISTANCE_WATER					,
eIP_RESISTANCE_WIND						,
eIP_RESISTANCE_TERRA					,
eIP_RESISTANCE_LIGHT					,
eIP_RESISTANCE_DARK						,
eIP_RESISTANCE_MAGIC					,
eIP_ABSORB_FIRE							,
eIP_ABSORB_WATER						,
eIP_ABSORB_WIND							,
eIP_ABSORB_TERRA						,
eIP_ABSORB_LIGHT						,
eIP_ABSORB_DARK							,
eIP_ABSORB_MAGIC						,
eIP_RESISTANCE_FREEZE					,
eIP_RESISTANCE_COLD						,
eIP_RESISTANCE_STUN						,
eIP_RESISTANCE_CONFUSE					,
eIP_RESISTANCE_CHARMING					,
eIP_RESISTANCE_STONE					,
eIP_RESISTANCE_INSTANCE_KILL			,
eIP_RESISTANCE_POISON					,
eIP_RESISTANCE_SLEEP					,
eIP_RESISTANCE_STRANGE_STATUS			,
eIP_RESISTANCE_DECLINE_STATUS			,
eIP_RESISTANCE_CURSE_STATUS				,
eIP_RESISTANCE_ALL_BAD_STATUS			,
eIP_RESISTANCE_KNOCK_BACK				,
eIP_RESISTANCE_CRITICAL_SHOT			,
eIP_RESISTANCE_CRUSH_SHOT				,
eIP_RETURN_DAMAGE						,
eIP_DAMAGE_TO_CP						,
eIP_MAKE_FREEZE_ATTACKER				,
eIP_MAKE_COLD_ATTACKER					,
eIP_CHARGE_SKILL						,
eIP_JOB_SKILL_LEVEL						,
eIP_ALL_SKILL_LEVEL						,
eIP_FIRST_AID							,
eIP_CHANGE_WEAPON_SPEED					,
eIP_REGENERATION_HP						,
eIP_RESURRECTION_CHANCE					,
eIP_BLURRED								,
eIP_INVISIBLE							,
eIP_LEVITATE							,
eIP_MAGIC_BULLET						,
eIP_INFINITY_BULLET						,
eIP_NOT_AIMED							,
eIP_INCREASE_RARE_ITEM_DROP_CHANCE		,
eIP_INCREASE_UNIQUE_ITEM_DROP_CHANCE	,
eIP_DECREASE_RELOAD_TIME				,
eIP_AUTO_RELOAD							,

eIP_DISABLE								,
eIP_CAN_NOT_STRIP						,
eIP_CAN_NOT_ADD_PREFIX					,

eIP_UPGRADE_FIRE_DAMAGE_ATTACK			,
eIP_UPGRADE_WATER_DAMAGE_ATTACK			,
eIP_UPGRADE_WIND_DAMAGE_ATTACK			,
eIP_UPGRADE_EARTH_DAMAGE_ATTACK			,
eIP_UPGRADE_LIGHT_DAMAGE_ATTACK			,
eIP_UPGRADE_DARK_DAMAGE_ATTACK			,

eIP_CONTROL_SKILL_LEVEL_BY_DIFFICULTY	,
eIP_INCREASE_SUMMON_BEAST_STATUS		,
eIP_INCREASE_GAIN_EXP_FOR_PET			,

eIP_IS_SHOP_SPECIAL_ITEM				,
eIP_WEAKNING_TARGET_FIRE_RESISTANCE			,
eIP_WEAKNING_TARGET_WATER_RESISTANCE		,
eIP_WEAKNING_TARGET_WIND_RESISTANCE			,
eIP_WEAKNING_TARGET_EARTH_RESISTANCE		,
eIP_WEAKNING_TARGET_LIGHT_RESISTANCE		,
eIP_WEAKNING_TARGET_DARK_RESISTANCE			,
eIP_WEAKNING_TARGET_MAGIC_RESISTANCE		,
eIP_STRENGTHENING_FIRE_DAMAGE				,
eIP_STRENGTHENING_WATER_DAMAGE				,
eIP_STRENGTHENING_WIND_DAMAGE				,
eIP_STRENGTHENING_EARTH_DAMAGE				,
eIP_STRENGTHENING_LIGHT_DAMAGE				,
eIP_STRENGTHENING_DARK_DAMAGE				,
eIP_STRENGTHENING_MAGIC_DAMAGE				,

eIP_DECREASE_STRENGTH,
eIP_DECREASE_AGILITY,
eIP_DECREASE_CONSTITUTION,
eIP_DECREASE_WISDOM,
eIP_DECREASE_INTELIGENCE,
eIP_DECREASE_CHARISMA,
eIP_DECREASE_LUCK,

eIP_DECLINE_MOVE_SPEED,
eIP_DECLINE_ACTION_SPEED,

eIP_ADD_DAMAGE_TO_UNDEAD					,
eIP_ADD_DAMAGE_TO_DEMON						,
eIP_ADD_DAMAGE_TO_HUMAN						,
eIP_ADD_DAMAGE_TO_ANIMAL					,
eIP_ADD_DAMAGE_TO_HOLY_ANIMAL				,
eIP_POTION_HEAL_SPEED2						,

eIP_DECLINE_DEFENSE_PERCENTAGE				,
eIP_DECLINE_DEFENSE							,
eIP_DECLINE_HIT_RATE						,
eIP_DECLINE_DODGE_RATE						,

eIP_FIRE_DAMAGE_DX,
eIP_WATER_DAMAGE_DX,	
eIP_WIND_DAMAGE_DX,	
eIP_TERRA_DAMAGE_DX,	
eIP_LIGHT_DAMAGE_DX,	
eIP_DARK_DAMAGE_DX,
eIP_BUFF_SKILL_CASTING,
eIP_INCREASE_ALL_STATUS,
eIP_ACL_BUFF_SKILL_CASTING,
eIP_INCREASE_HARD_BLOW		,
};

#define	dMAX_ITEM_EFFECT_DATA				512
#define	dMAX_ITEM_PREFIX_TYPE_COUNT			200
#define	dMAX_ITEM_PREFIX_COUNT				1024


#endif