#ifndef _classTITLE_DEFINE_H
#define	_classTITLE_DEFINE_H

#include <winsock2.h>
#include <windows.h>

#define	dTITLE_NAME_LENGTH						32
#define	dMAX_TITLE_EFFECT_COUNT					6
#define	dMAX_TITLE_EFFECT_INFO_VALUE_COUNT		10
#define	dMAX_TITLE_LEVEL						10
#define	dMAX_TITLE_COUNT						256
#define	dMAX_PLAYER_JOB							16
#define	dTITLE_EXPLAIN_LENGTH					254
#define	dTITLE_NOT_BANK_GOLD_BAR_TAX			55



enum
{
	eTN_BANK_CLIENT		=	1,
	eTN_PORTER			=	2,
	eTN_CITIZEN			=	3,
	eTN_DEALER			=	4,
	eTN_BARD			=	5,
	eTN_BERSERK			=	22,
	eTN_CARTOGRAPHER	=	25,
	eTN_CAMPING_MASTER	=	28,
	eTN_DRUGGIST		=	31,
	eTN_RED_STONE_HUNTER=	82,
	eTN_CRUSADER		=	101,
	eTN_DUNGEON_MASTER	=	102,
	eTN_DEVIL_SLAYER	=	103,
	eTN_POACHER			=	104,
	eTN_DRAGON_SLAYER	=	105,
	eTN_FRONTIER		=	183,
	eTN_RED_STONE_AGENT	=	184,

	eTN_BONUS_STATE_POINT=	217,
	eTN_BONUS_SKILL_POINT=	218,
	eTN_BONUS_HP		=	219,
	eTN_BONUS_CP		=	220,

};

enum TITLE_LIST
{
	eTIN_BANK_CUSTOMER			 = 1,
	eTIN_PORTER						,
	eTIN_CITIZEN					,
	eTIN_BROKER						,

	eTIN_NOVICE					 = 6,

	eTIN_ALCHEMY				= 23,
	eTIN_MAPMAKER				= 25,
	eTIN_INSTINCTFORSURVIVAL		,
	eTIN_CITYWALKER					,
	eTIN_CAMPING_MASTER				,
	eTIN_MONSTERSEXER				,
	eTIN_CHARMING					,
	eTIN_PHAMRMACIST				,
	eTIN_ORPHIC						,

	eTIN_CAVETHEFT				= 71,
	eTIN_CHROMATIC_HONORMEMBER		,
	eTIN_HONORMEMBER				,

	eTIN_JEWELY_MASTER			= 81,
	eTIN_REDSTONE_HUNTER			,
	eTIN_REDEYE_MEMBER				,

	eTIN_PIONEER				= 183,

	eTIN_CHIVALRY				= 201,
	eTIN_SWORDSMANSHIP,
	eTIN_WIZARDRY,
	eTIN_LYCANTROPHY,
	eTIN_FANATICISM,
	eTIN_ANGELRANK,
	eTIN_KEYMANAFACTURING,
	eTIN_HANDICRAFTSMAN,
	eTIN_RECPMMAOSSANCE,
	eTIN_TACTICS,
	eTIN_PALEOGRAPHY,
	eTIN_THREMMATOLOGY,
	eTIN_COURTESY,
	eTIN_ASTRONOMY,
	eTIN_SPIRITISM,
	eTIN_DEVIL,
	eTIN_PSYCHIC,
	eTIN_INFIGHTER,
	eTIN_OPTICAL					,

};


enum
{
	eTE_SKILL_MASTER		,
	eTE_PORTER				,
	eTE_BANK_CLIENT			,
	eTE_FRONTIER			,
	eTE_DEALER				,
	eTE_CITIZEN				,
	eTE_PATHFINDER			,
	eTE_BERSERKER			,
	eTE_ALCHEMY				,
	eTE_DISTINGUISHER		,
	eTE_CARTOGRAPHER		,
	eTE_SURVIVAL_INSTINCTS	,
	eTE_CITY_WALKER			,
	eTE_CAMPING_MASTER		,
	eTE_MONSTER_DISCERNER	,
	eTE_COURTESY			,
	eTE_DRUGGIST			,
	eTE_ESOTERIC			,
	eTE_TRAP_EVADE			,
	eTE_LOCK_MASTER			,
	eTE_TREASURE_HUNTER		,
	eTE_ELEMENTAL_MASTER	,
	eTE_ADVENTURER			,
	eTE_INCLINE_POWER		,
	eTE_INCLINE_MAGIC_RESISTANCE	,
	eTE_NATURAL_ENEMY		,
	eTE_HERO				,
	eTE_ANTI_HERO			,
	eTE_BARD				,
	eTE_HUNTING_BONUS		,
};



enum
{
	eCRLM_LEVEL_VALUE		,
	eCRLM_MULTIPLE_VALUE	,
	eCRLM_SQUARE_VALUE		,
};

class	CTitleEffectInfo
{
public:
	WORD			m_wEffect;
	int				m_aiValue[dMAX_TITLE_LEVEL][dMAX_TITLE_EFFECT_INFO_VALUE_COUNT];
};

class	CTitleInfo
{
public:
	WORD				m_wSerial;
	WORD				m_wComputeRequireLevelMethod,m_wRequireLevelValue;
	
	UINT				m_uiEnableJobMask;
	UINT				m_uiDefaultOwnJobMask;

	inline	BOOL		isEnableJob(int _iJob)
	{
		UINT	uiCheckMask	=	1<<_iJob;

		if	(m_uiEnableJobMask	&	uiCheckMask)
			return	TRUE;

		return	FALSE;
	}
	inline	BOOL		isDeafultOwnJob(int _iJob)
	{
		UINT	uiCheckMask	=	1<<_iJob;

		if	(m_uiDefaultOwnJobMask	&	uiCheckMask)
			return	TRUE;

		return	FALSE;
	}

	char				m_strName[dTITLE_NAME_LENGTH];
	CTitleEffectInfo	m_aEffect[dMAX_TITLE_EFFECT_COUNT];
	char				m_strExplain[dTITLE_EXPLAIN_LENGTH];

	WORD				m_bf1IsRemoveAble	:	1;
	WORD				m_bf1ExceptCH5Reward:	1;
};

#endif