<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32' or '$(Platform)'=='x86'">
    <ClCompile>
      <PreprocessorDefinitions>POINTER_64=;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
