//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AdminTool.rc
//
#define IDS_FTPMSG1                     1
#define IDS_FTPMSG2                     2
#define IDC_RESET_COUNTER               2
#define ID_CONNECT                      3
#define IDS_FTPMSG3                     3
#define IDC_CALCULATE                   3
#define IDC_REFRESH                     3
#define IDC_CHANGE_VALUE                3
#define IDC_SAVE_DATA                   3
#define IDS_FTPMSG4                     4
#define IDCANCEL2                       4
#define ID_INFO_UPDATE                  4
#define IDC_RESET_CURRENT_COUNTER       4
#define IDS_FTPMSG5                     5
#define IDC_CAL_REBIRTH_EXP             5
#define IDS_FTPMSG6                     6
#define IDC_STATIC17                    17
#define IDD_ADMINTOOL_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_CONNECT                     129
#define IDB_RED_BALL                    130
#define IDB_GREEN_BALL                  132
#define IDB_INFO                        133
#define IDD_NOTICE_PAGE                 135
#define IDD_DATA_MODIFY                 136
#define IDD_USERSETTING                 137
#define IDD_CHARACTER_DATA              138
#define IDD_WORLD_SCORE                 139
#define IDD_SUM_PAGE                    140
#define IDD_MSG_DIALOG                  142
#define IDI_GRAPH                       145
#define IDD_AGE_COUNT                   146
#define IDD_NEW_NAME                    147
#define IDD_CHARACTER_DATA1             149
#define IDD_ITEM_LIST                   150
#define IDD_EXP_CALC                    153
#define IDD_SEARCH                      154
#define IDB_MENUTITLE                   156
#define IDR_LIST_MENU                   158
#define IDD_TENTATIVE_GUILD             159
#define IDD_EVENT                       160
#define IDD_SERVER_TOOL                 161
#define IDD_GUILD                       162
#define IDD_RENEW_ITEM_EXPIRE_TIME      163
#define IDD_ITEM_PACK_LIST              164
#define IDD_MAKE_ITEM                   165
#define IDD_CURRENT_ITEM_PACK_INFO      166
#define IDD_QUEST_LIST                  167
#define IDD_CARROT_SHOP                 168
#define IDD_CURRENT_SERVER_CARROT_SHOP_SALES_INFO 169
#define IDD_DLG_CHG_GILDMASTER          170
#define IDD_CALC_EXP                    171
#define IDD_INVENTORY_INFO              172
#define IDD_GUILD_INVENTORY_INFO        173
#define IDD_GUILD_PET_AND_GUARDIAN_INFO 174
#define IDD_MINIPET_LIST                175
#define IDD_PVP_TOOL                    176
#define IDD_PET_LIST                    177
#define IDD_POLL                        178
#define IDD_LOTTO_EVENT                 179
#define IDD_EVENT_TIME                  180
#define IDC_TREE1                       1000
#define IDC_SERVER_TREE                 1000
#define IDC_TXT_USER_COUNT              1001
#define IDC_EDIT_ID                     1002
#define IDC_EDIT_PW                     1003
#define IDC_SEND_ALL_MSG                1003
#define IDC_INPUT_MSG                   1004
#define IDC_SEND_MSG                    1005
#define IDC_SEND_NOTICE                 1006
#define IDC_SAVE_NOTICE                 1007
#define IDC_SYNC_NOTICE                 1008
#define IDC_SHEET                       1009
#define IDC_LOGIN_DIE                   1009
#define IDC_APPLY_DATA                  1011
#define IDC_LOGIN_OPEN                  1011
#define IDC_RESET_DATA                  1012
#define IDC_LOOP_NOTICE                 1012
#define IDC_USERID                      1013
#define IDC_NAME1                       1016
#define IDC_NAME2                       1017
#define IDC_NAME3                       1018
#define IDC_NAME4                       1019
#define IDC_EXP1                        1020
#define IDC_LEVPNT1                     1021
#define IDC_JOB1                        1022
#define IDC_SKLPNT1                     1023
#define IDC_EXP2                        1024
#define IDC_LEVPNT2                     1025
#define IDC_SKLPNT2                     1026
#define IDC_EXP3                        1027
#define IDC_LEVPNT3                     1028
#define IDC_SKLPNT3                     1029
#define IDC_EXP4                        1030
#define IDC_LEVPNT4                     1031
#define IDC_SKLPNT4                     1032
#define IDC_GOLD1                       1033
#define IDC_BADNAME                     1034
#define IDC_JOB2                        1035
#define IDC_BADUSER                     1035
#define IDC_GOLD2                       1036
#define IDC_BADDATE                     1036
#define IDC_JOB3                        1037
#define IDC_ADMIN_NAME                  1037
#define IDC_GOLD3                       1038
#define IDC_ADMIN                       1038
#define IDC_JOB4                        1039
#define IDC_ADMIN_COUNT                 1039
#define IDC_DELAVA1                     1040
#define IDC_RECOVER_ID                  1040
#define IDC_DELAVA2                     1041
#define IDC_20030322                    1041
#define IDC_DELUSER                     1041
#define IDC_DELAVA3                     1042
#define IDC_41843                       1042
#define IDC_RECOVER_ID2                 1042
#define IDC_DELAVA4                     1043
#define IDC_MONTHCALENDAR1              1043
#define IDC_CNAME_ID                    1043
#define IDC_GOLD4                       1044
#define IDC_COMBO1                      1044
#define IDC_SCORE_BYTIME                1044
#define IDC_AGE_LIST                    1044
#define IDC_CNAME_NAME                  1044
#define IDC_JOB_LIST                    1044
#define IDC_COMBO_YY0                   1044
#define IDC_FGUILD1                     1044
#define IDC_COMBO_WORLD                 1044
#define IDC_END_DAY                     1044
#define IDC_AVR                         1045
#define IDC_SELECT_LIST                 1045
#define IDC_CNAME_NAME2                 1045
#define IDC_COMBO_MM0                   1045
#define IDC_FGUILD2                     1045
#define IDC_PREFIX2                     1045
#define IDC_TOP                         1046
#define IDC_AVARECOVER_ID               1046
#define IDC_COMBO_HH0                   1046
#define IDC_SGUILD1                     1046
#define IDC_PREFIX3                     1046
#define IDC_RECOVER                     1047
#define IDC_COMBO_DD0                   1047
#define IDC_SGUILD2                     1047
#define IDC_PREFIX2_KIND                1047
#define IDC_RUN_DELUSER                 1048
#define IDC_COMBO_YY1                   1048
#define IDC_ID_CHECK                    1048
#define IDC_FGUILD3                     1048
#define IDC_PREFIX3_KIND                1048
#define IDC_ADDITEM1                    1049
#define IDC_CNAME                       1049
#define IDC_COMBO_MM1                   1049
#define IDC_SGUILD3                     1049
#define IDC_BUTTON1                     1050
#define IDC_CNAME2                      1050
#define IDC_RESET_STATE_POINT           1050
#define IDC_AVA_LIST                    1050
#define IDC_PEIN                        1050
#define IDC_COMBO_HH1                   1050
#define IDC_GET_GUILDLIST               1050
#define IDC_BOOKING_OX_QUIZ_EVENT       1050
#define IDC_LOOP_NOTICE_SELECT_SERVER   1050
#define IDC_ADD_REQUITAL                1050
#define IDC_CREATE                      1050
#define IDC_CANCEL_QUEST                1050
#define IDC_GET_GUILD_INFO              1050
#define IDC_RESERVE_BTN                 1050
#define IDC_NEXT                        1050
#define IDC_ADD                         1050
#define IDC_EXCEL                       1050
#define IDC_ADD_POLL                    1050
#define IDC_ADDITEM2                    1051
#define IDC_BUTTON2                     1051
#define IDC_DEL_BADID                   1051
#define IDC_RESET_SKILL_POINT           1051
#define IDC_COMBO_DD1                   1051
#define IDC_MODIFY1                     1051
#define IDC_OX_QUIZ                     1051
#define IDC_LOOP_NOTICE_ALL_SERVER      1051
#define IDC_UPDATE_LIST                 1051
#define IDC_ASK_PACK_LIST               1051
#define IDC_ASK_GUILD_LIST              1051
#define IDC_MODIFY_BTN                  1051
#define IDC_CANCEL                      1051
#define IDC_REMOVE                      1051
#define IDC_CANCEL_QUEST_COMPLETE_INFO  1051
#define IDC_RECEIVE_POLL_INFO           1051
#define IDC_MODIFY                      1051
#define IDC_VIEW_REALTIME               1051
#define IDC_ADDITEM3                    1052
#define IDC_RECOVER2                    1052
#define IDC_RESET_SERVER_STATE_POINT    1052
#define IDC_MODIFY2                     1052
#define IDC_COMPLETE_OX_QUIZ            1052
#define IDC_CANCEL_LOOP_NOTICE_SELECT_SERVER 1052
#define IDC_REMOVE_PACK                 1052
#define IDC_REMOVE_RENEW                1052
#define IDC_CANCEL_BTN                  1052
#define IDC_FIND                        1052
#define IDC_GET_ALL                     1052
#define IDC_ADD_BY_CODE                 1052
#define IDC_UPDATE_TO_SERVER            1052
#define IDC_ADD2                        1052
#define IDC_REMOVE_EVENT                1052
#define IDC_REVISE_SP                   1052
#define IDC_ADDITEM4                    1053
#define IDC_AVARECOVER_NAME             1053
#define IDC_RESET_SERVER_SKILL_POINT    1053
#define IDC_MODIFY3                     1053
#define IDC_CANCEL_LOOP_NOTICE_ALL_SERVER 1053
#define IDC_BOOKING_OX_QUIZ_EVENT_FOR_TEST 1053
#define IDC_ASK_SELECT_SERVER_PACK_INFO 1053
#define IDC_GETCOMMANDLIST_BTN          1053
#define IDC_MAKE                        1053
#define IDC_REWIND_LIST                 1053
#define IDC_GET_SELECTED_PET_INFO       1053
#define IDC_CHANGE_SELECT_POLL_INFO     1053
#define IDC_AVARECOVER_NEWNAME          1054
#define IDC_SERCH_ITEM                  1054
#define IDC_FGUILD4                     1054
#define IDC_CANCEL_OX_QUIZ_EVENT        1054
#define IDC_RESET_CONTENTS              1054
#define IDC_REMOVE_BY_CODE              1054
#define IDC_UPDATE                      1054
#define IDC_GET_SELECT_POLL_INFO        1054
#define IDC_SYNC_LOADED_PLAYER          1054
#define IDC_OPER_LEVEL                  1055
#define IDC_DATA_CONVERT                1055
#define IDC_SGUILD4                     1055
#define IDC_REVIVE_OX_QUIZ_LOSER_BATTLE 1055
#define IDC_CHANGE_NAME                 1055
#define IDC_GET_ITEM_CODE               1055
#define IDC_FILL_DATE_BY_CURRENT_TIME   1055
#define IDC_GETLIST                     1055
#define IDC_FOR_LEVEL                   1056
#define IDC_CHECK_BADUSER               1056
#define IDC_EXPORT_UNIQUE_ITEM          1056
#define IDC_MODIFY4                     1056
#define IDC_APPLY                       1056
#define IDC_GR_APPLY                    1056
#define IDC_ADD_GOLD                    1056
#define IDC_STATIC_LEVEL                1057
#define IDC_BANK_DATA_CONVERT           1057
#define IDC_UPDATELIST                  1057
#define IDC_FGUILD5                     1057
#define IDC_MODIFY_DATA                 1057
#define IDC_GR_CANCEL                   1057
#define IDC_REMOVE_GOLD                 1057
#define IDC_SET_CATEGORY                1057
#define IDC_GIVE_PRIZE                  1058
#define IDC_SGUILD5                     1058
#define IDC_GIVE_GUILD_TICKET           1058
#define IDC_GET_SCHEDULE                1058
#define IDC_EDIT_ITEM                   1058
#define IDC_RENEW_SELECT_ITEM_PERIOD    1058
#define IDC_CHANGE_GUARDIAN_EXP         1058
#define IDC_BADWHY                      1059
#define IDC_GIVE_BOC                    1059
#define IDC_MODIFY5                     1059
#define IDC_FILL_TIME                   1059
#define IDC_MSG                         1060
#define IDC_FGUILD6                     1060
#define IDC_GR_TEST                     1060
#define IDC_APPOINTMENT_WORD_QUIZ       1060
#define IDC_PROGRESS                    1061
#define IDC_SGUILD6                     1061
#define IDC_SETTING_WQ_QUESTION         1061
#define IDC_GET_ITEM_CODE2              1061
#define IDC_SERVER_LIST                 1062
#define IDC_MODIFY6                     1062
#define IDC_END_WORD_QUIZ               1062
#define IDC_SUM_TEXT                    1063
#define IDC_FGUILD7                     1063
#define IDC_CANCEL_WORD_QUIZ            1063
#define IDC_SGUILD7                     1064
#define IDC_TEST_WORD_QUIZ              1064
#define IDC_USERCOUNTBYDAY              1065
#define IDC_SKILL_LIST                  1065
#define IDC_MODIFY7                     1065
#define IDC_CHANGE_WORD_QUIZ_ROUND      1065
#define IDC_EQUIPMENT_SKILL             1066
#define IDC_SEND_TO_VILLAGE             1066
#define IDC_FGUILD8                     1066
#define IDC_LOTTO_EVENT                 1066
#define IDC_ITEM_LIST                   1067
#define IDC_SGUILD8                     1067
#define IDC_EVENT_TIME                  1067
#define IDC_ID2                         1068
#define IDC_MODIFY8                     1068
#define IDC_ITEM_KIND                   1068
#define IDC_ITEM_LIST2                  1068
#define IDC_GRAPH                       1069
#define IDC_NAME                        1069
#define IDC_FGUILD9                     1069
#define IDC_EXP_TABLE                   1069
#define IDC_AVTAR_INDEX                 1070
#define IDC_SGUILD9                     1070
#define IDC_NEW_NAME                    1071
#define IDC_TITLE_LIST                  1071
#define IDC_SEND_TO_JAIL                1071
#define IDC_MODIFY9                     1071
#define IDC_TYPE                        1072
#define IDC_LEVEL                       1072
#define IDC_FGUILD10                    1072
#define IDC_EXPERIENCE                  1073
#define IDC_SGUILD10                    1073
#define IDC_BADID                       1074
#define IDC_LEVEL_POINT                 1074
#define IDC_MODIFY10                    1074
#define IDC_VICTORY_POINT               1074
#define IDC_HONOR_POINT                 1074
#define IDC_BAD_CHARNAME                1075
#define IDC_GOLD                        1075
#define IDC_COUNT_OF_POINT_BATTLE       1075
#define IDC_DEL_BADNAME                 1076
#define IDC_SKILL_POINT                 1076
#define IDC_KILL_WORLD                  1077
#define IDC_BONUS_SKILL_POINT           1077
#define IDC_SEARCH_ID_INPUT             1078
#define IDC_INVENTORY_SIZE              1078
#define IDC_BANK_GOLD                   1078
#define IDC_SEARCH_ID                   1079
#define IDC_LAST_VILLAGE                1079
#define IDC_NOTICE                      1079
#define IDC_LIST_DELETE                 1080
#define IDC_KILLYOU                     1080
#define IDC_LAST_FIELD                  1080
#define IDC_PLACE_RELATED               1080
#define IDC_SAVE_UPDATE                 1081
#define IDC_FIELD1                      1081
#define IDC_POSITION_X                  1081
#define IDC_MASTER                      1081
#define IDC_FIELD2                      1082
#define IDC_SAVE_UPDATE_ALL             1082
#define IDC_GUILD                       1082
#define IDC_GUILD_SKILL_POINT           1082
#define IDC_FIELD3                      1083
#define IDC_GUILD_RANK                  1083
#define IDC_ORGANIZE_DATE_YEAR          1083
#define IDC_FIELD4                      1084
#define IDC_SAVE_COUNT                  1084
#define IDC_ORGANIZE_DATE_MONTH         1084
#define IDC_ITEMLISTSAVE                1085
#define IDC_PENELTY_TIME                1085
#define IDC_FIELD5                      1085
#define IDC_ORGANIZE_DATE_DAY           1085
#define IDC_POSITION_Y                  1086
#define IDC_FIELD6                      1086
#define IDC_CHANGE_GUILD_MASTER_DATE_YEAR 1086
#define IDC_CHARACTER_LIST              1087
#define IDC_FIELD7                      1087
#define IDC_CHANGE_GUILD_MASTER_DATE_MONTH 1087
#define IDC_SAVE_FILE                   1088
#define IDC_FIELD8                      1088
#define IDC_CHANGE_GUILD_MASTER_DATE_DAY 1088
#define IDC_LOAD_FILE                   1089
#define IDC_FIELD9                      1089
#define IDC_EXP_TAX                     1089
#define IDC_SAVE_TO_DB                  1090
#define IDC_FIELD10                     1090
#define IDC_LAST_BATTLE_GUILD           1090
#define IDC_MASTER_CONNECT_DATE_YEAR    1090
#define IDC_WORLD_LIST2                 1091
#define IDC_SERIAL                      1091
#define IDC_BATTLE_FIELD                1091
#define IDC_LOAD_DB_NAME                1092
#define IDC_GUILD_MARK                  1092
#define IDC_LOAD_NAME                   1093
#define IDC_HALL_LEVEL                  1093
#define IDC_LOAD_ID                     1094
#define IDC_MASTER_CONNECT_DATE_MONTH   1094
#define IDC_CONNECT_AND_LOAD            1095
#define IDC_MASTER_CONNECT_DATE_DAY     1095
#define IDC_SAVE_ALL_TO_DB              1096
#define IDC_LAST_CONNECT_DATE_YEAR      1096
#define IDC_GOLD_LIMIT                  1097
#define IDC_WAY_POINT_INDEX             1097
#define IDC_LAST_CONNECT_DATE_MONTH     1097
#define IDC_CHECK_RICH                  1098
#define IDC_BONUS_SKILL_POINT2          1098
#define IDC_LAST_CONNECT_DATE_DAY       1098
#define IDC_ADD_ITEM                    1099
#define IDC_ROEN_GOOD_WILL              1099
#define IDC_CHECK_SKILL_POINT           1100
#define IDC_GUILD_MASTER_GRACE          1100
#define IDC_REMOVE_ITEM                 1101
#define IDC_VP_POINT                    1101
#define IDC_CHECK_SAME_ITEM             1102
#define IDC_QUEST_LIST                  1102
#define IDC_VP_POINT2                   1102
#define IDC_DEFEAT                      1102
#define IDC_RESET_LEVEL                 1103
#define IDC_COMPLETE_QUEST_LIST         1103
#define IDC_VP_POINT3                   1103
#define IDC_WIN                         1103
#define IDC_SEND_TO_GATE                1104
#define IDC_MAIN_QUEST_VALUE_LIST       1104
#define IDC_CV_COUNT                    1104
#define IDC_CHECK_STATE_POINT           1105
#define IDC_ADD_REMOVE_ITEM             1105
#define IDC_OPERATOR_SHAPE              1105
#define IDC_TRANS_TO_GVG_SERVER_DATE    1105
#define IDC_TODAY_GUILD_BATTLE_COUNT    1105
#define IDC_POSITION_TX                 1106
#define IDC_DRAW                        1106
#define IDC_POSITION_TY                 1107
#define IDC_THIS_WEEK_GUILD_BATTLE_COUNT 1107
#define IDC_EVENT_VALUE                 1108
#define IDC_SCRIPT                      1109
#define IDC_SCRIPTER_LAUNCHER           1110
#define IDC_DBINDEXMAKE                 1111
#define IDC_DEATH_PENELTY_TIME          1111
#define IDC_CALCULATE_EXP               1112
#define IDC_LEVEL11                     1112
#define IDC_LEVEL12                     1113
#define IDC_RESTORE_STRANGE_FAULT       1113
#define IDC_EXP11                       1114
#define IDC_PLAY_TIME_HOUR              1114
#define IDC_EXP12                       1115
#define IDC_PLAY_TIME_MINUTE            1115
#define IDC_EXPAND_INVENTORY_SIZE       1115
#define IDC_LEVEL21                     1116
#define IDC_OWN_TITLE                   1116
#define IDC_LEVEL22                     1117
#define IDC_PLAY_TIME_DAY               1117
#define IDC_EXP21                       1118
#define IDC_WAYPOINT_POS_X              1118
#define IDC_EXP22                       1119
#define IDC_WAYPOINT_POS_Y              1119
#define IDC_LEVEL31                     1120
#define IDC_WAY_POINT_FIELD             1120
#define IDC_LEVEL32                     1121
#define IDC_GET_GUILD_NAME              1121
#define IDC_EXP31                       1122
#define IDC_EXPLORATION_COUNT           1122
#define IDC_EXP32                       1123
#define IDC_ITEM_INFO                   1123
#define IDC_LEVEL41                     1124
#define IDC_RED_STONE_POINT             1124
#define IDC_LEVEL42                     1125
#define IDC_BOOST_DAMAGE                1125
#define IDC_EXP41                       1126
#define IDC_BOOST_DAMAGE_TIME           1126
#define IDC_EXP42                       1127
#define IDC_MINIPET_LIST                1127
#define IDC_RESULT                      1128
#define IDC_INCLINATION                 1128
#define IDC_REBIRTH_COUNT               1128
#define IDC_TOTAL_BC                    1129
#define IDC_REBIRTH_LEVEL               1129
#define IDC_ABOUT_RECOVER               1130
#define IDC_TOTAL_WIN_C                 1130
#define IDC_REBIRTH_EXP                 1130
#define IDC_GUILD_CHECK                 1131
#define IDC_TOTAL_LOSE_C                1131
#define IDC_SEARCH_RESULT               1132
#define IDC_TOTAL_DRAW_C                1132
#define IDC_WEEKLY_BC                   1133
#define IDC_WEEKLY_WIN_C                1134
#define IDC_SEARCH                      1135
#define IDC_WEEKLY_LOSE_C               1135
#define IDC_WORLD_LIST                  1136
#define IDC_CLEAR                       1136
#define IDC_WEEKLY_DRAW_C               1136
#define IDC_DATE_LIST                   1137
#define IDC_YEAR                        1137
#define IDC_DUEL_POINT                  1137
#define IDC_CLEAR_WCG_RANK              1137
#define IDC_TIME_LIST                   1138
#define IDC_MONTH                       1138
#define IDC_TRIAL_GAME_VP               1138
#define IDC_GET_WCG_RANK                1138
#define IDC_WINNING_POINT               1138
#define IDC_DAY                         1139
#define IDC_MODIFY_WCG_SCORE            1139
#define IDC_GUILD_DUNGEON_COUNT         1139
#define IDC_HOUR                        1140
#define IDC_ADD_TEAM                    1140
#define IDC_PET_LIST                    1140
#define IDC_QUESTION                    1141
#define IDC_YEAR2                       1141
#define IDC_SEAL_OF_DAWN_COUNT          1141
#define IDC_OX_QUIZ_SOLUTION            1142
#define IDC_MONTH2                      1142
#define IDC_GOLD_BAR                    1142
#define IDC_OX_QUIZ_COUNT_DOWN          1143
#define IDC_LOOP_NOTICE_BEGIN_YEAR      1143
#define IDC_DAY2                        1143
#define IDC_INCLINATION2                1143
#define IDC_MINUTE                      1144
#define IDC_LOOP_NOTICE_BEGIN_MONTH     1144
#define IDC_BANK_GOLD_BAR               1144
#define IDC_LOOP_NOTICE_BEGIN_DAY       1145
#define IDC_GR_BEGIN_COMMENT            1145
#define IDC_HOUR2                       1145
#define IDC_TRANS_GVG_DATE_TEXT         1145
#define IDC_LOOP_NOTICE_BEGIN_HOUR      1146
#define IDC_GR_END_COMMENT              1146
#define IDC_MINUTE2                     1146
#define IDC_LOOP_NOTICE_BEGIN_MINUTE    1147
#define IDC_WQ_YEAR                     1147
#define IDC_LOOP_NOTICE_END_YEAR        1148
#define IDC_WQ_MONTH                    1148
#define IDC_LOOP_NOTICE_END_MONTH       1149
#define IDC_WQ_DAY                      1149
#define IDC_LOOP_NOTICE_END_DAY         1150
#define IDC_WQ_HOUR                     1150
#define IDC_LOOP_NOTICE_END_HOUR        1151
#define IDC_WQ_QUESTION                 1151
#define IDC_LOOP_NOTICE_END_MINUTE      1152
#define IDC_WQ_SOLUTION                 1152
#define IDC_EDIT11                      1153
#define IDC_WORD_QUIZ_COUNT_DOWN        1153
#define IDC_CODE                        1153
#define IDC_EDIT1                       1154
#define IDC_WQ_MINUTE                   1154
#define IDC_COMBO2                      1155
#define IDC_EDIT_GUILDINDEX             1155
#define IDC_OPTION2                     1155
#define IDC_GR_MONTH1                   1155
#define IDC_BATTLE_GUILD2               1155
#define IDC_PRICE                       1155
#define IDC_NEWGUILDMASTER              1155
#define IDC_EXP                         1155
#define IDC_EDIT2                       1156
#define IDC_PREFIX_1                    1156
#define IDC_GR_DAY1                     1156
#define IDC_BIO                         1156
#define IDC_ADMIN_LOAD                  1157
#define IDC_PREFIX_2                    1157
#define IDC_GR_HOUR1                    1157
#define IDC_ENERGY                      1157
#define IDC_2                           1157
#define IDC_MM1                         1157
#define IDC_ADMIN_PASSCHANGE            1158
#define IDC_PREFIX_3                    1158
#define IDC_GR_MINUTE1                  1158
#define IDC_MINERAL                     1158
#define IDC_3                           1158
#define IDC_DD1                         1158
#define IDC_ITEM_COUNT                  1159
#define IDC_GR_EXP                      1159
#define IDC_4                           1159
#define IDC_HH1                         1159
#define IDC_ADMIN_DELETE                1160
#define IDC_FREQUENCY                   1160
#define IDC_GR_ITEM_DROP_CHANCE         1160
#define IDC_5                           1160
#define IDC_MIN1                        1160
#define IDC_ADMIN_CHANGELEVEL           1161
#define IDC_LIMIT_COUNT                 1161
#define IDC_GR_HOUR3                    1161
#define IDC_6                           1161
#define IDC_CHANGE_FIXCHECK             1162
#define IDC_PREFIX_1_2                  1162
#define IDC_GR_MINUTE3                  1162
#define IDC_7                           1162
#define IDC_CHECK_FIXCHECKTIME          1163
#define IDC_RENEW_DAYS                  1163
#define IDC_PREFIX_2_2                  1163
#define IDC_GR_HOUR5                    1163
#define IDC_8                           1163
#define IDC_KILLUSERS                   1164
#define IDC_RENEW_HOURS                 1164
#define IDC_PREFIX_3_2                  1164
#define IDC_GR_YEAR2                    1164
#define IDC_9                           1164
#define IDC_GETGUILDINFO                1165
#define IDC_CHANGE_DELETE               1165
#define IDC_RENEW_MINUTES               1165
#define IDC_GR_MONTH2                   1165
#define IDC_GET_GUILDINFO_WORLD         1166
#define IDC_GR_DAY2                     1166
#define IDC_BEGIN_TEST_BATTLE           1166
#define IDC_YY2                         1166
#define IDC_EDIT_GUILDNAME              1167
#define IDC_GR_HOUR2                    1167
#define IDC_BATTLE_GUILD1               1167
#define IDC_MM2                         1167
#define IDC_INITGUILD_1                 1168
#define IDC_GR_MINUTE2                  1168
#define IDC_BATTLE_TIME                 1168
#define IDC_DD2                         1168
#define IDC_STATIC1                     1169
#define IDC_GR_HOUR4                    1169
#define IDC_HH2                         1169
#define IDC_STATIC2                     1170
#define IDC_MIN2                        1170
#define IDC_STATIC3                     1171
#define IDC_MONSTER_MIN_LEVEL           1171
#define IDC_STATIC4                     1172
#define IDC_MONSTER_MAX_LEVEL           1172
#define IDC_STATIC5                     1173
#define IDC_GR_MINUTE4                  1173
#define IDC_LEVEL_RANGE                 1173
#define IDC_STATIC6                     1174
#define IDC_DROP_ITEM                   1174
#define IDC_STATIC7                     1175
#define IDC_DROP_CHANCE                 1175
#define IDC_STATIC8                     1176
#define IDC_CRITICAL_CHANCE             1176
#define IDC_STATIC100                   1177
#define IDC_STATIC41                    1177
#define IDC_CRITICAL_COUNT              1177
#define IDC_FIXC_WEEKDAY                1178
#define IDC_STATIC48                    1178
#define IDC_FIXC_HOUR                   1179
#define IDC_STATIC49                    1179
#define IDC_FIXC_MIN                    1180
#define IDC_STATIC50                    1180
#define IDC_STATIC101                   1181
#define IDC_STATIC102                   1182
#define IDC_STATIC105                   1185
#define IDC_EDIT_FIXC_NOTICE            1186
#define IDC_STATIC9                     1187
#define IDC_STATIC10                    1188
#define IDC_STATIC11                    1189
#define IDC_STATIC12                    1190
#define IDC_STATIC13                    1191
#define IDC_STATIC14                    1192
#define IDC_STATIC15                    1193
#define IDC_STATIC16                    1194
#define IDC_STATIC18                    1195
#define IDC_STATIC19                    1196
#define IDC_STATIC20                    1197
#define IDC_STATIC21                    1198
#define IDC_STATIC22                    1199
#define IDC_STATIC23                    1200
#define IDC_STATIC24                    1201
#define IDC_STATIC25                    1202
#define IDC_STATIC26                    1203
#define IDC_STATIC27                    1204
#define IDC_STATIC28                    1205
#define IDC_STATIC29                    1206
#define IDC_STATIC30                    1207
#define IDC_STATIC31                    1208
#define IDC_STATIC32                    1209
#define IDC_STATIC33                    1210
#define IDC_STATIC34                    1211
#define IDC_STATIC35                    1212
#define IDC_STATIC36                    1213
#define IDC_INNER_SERVER                1214
#define IDC_STATIC37                    1214
#define IDC_STATIC38                    1215
#define IDC_STATIC39                    1216
#define IDC_STATIC40                    1217
#define IDC_GUILD_JOIN_YEAR             1218
#define IDC_STATIC51                    1218
#define IDC_GUILD_JOIN_MONTH            1219
#define IDC_STATIC52                    1219
#define IDC_GUILD_JOIN_DAY              1220
#define IDC_STATIC53                    1220
#define IDC_READY_TO_CREATE_GUILD       1221
#define IDC_STATIC54                    1221
#define IDC_GUILD_NAME                  1222
#define IDC_STATIC42                    1222
#define IDC_RESERVATION_INSPECTION      1223
#define IDC_STATIC43                    1223
#define IDC_STATIC_ID                   1224
#define IDC_STATIC44                    1224
#define IDC_RESERVE_COMMAND             1224
#define IDC_STATIC_OLDNAME              1225
#define IDC_STATIC45                    1225
#define IDC_STATIC_NEW_NAME             1226
#define IDC_STATIC46                    1226
#define IDC_STATIC_LINE1                1227
#define IDC_STATIC47                    1227
#define IDC_STATIC200                   1228
#define IDC_STATIC56                    1228
#define IDC_RICHEDIT1                   1229
#define IDC_READY_TO_SELECT_GUILD_MARK  1229
#define IDC_STATIC57                    1229
#define IDC_EXTEND_HOUR                 1230
#define IDC_EXTEND_DAY                  1231
#define IDC_STATIC_DAY                  1232
#define IDC_STATIC_HOUR                 1233
#define IDC_EXTEND_MINUTE               1234
#define IDC_REQUITAL_LIST               1234
#define IDC_STATIC_MINUTE               1235
#define IDC_STATIC_REQUITAL             1235
#define IDC_STATIC55                    1236
#define IDC_OPTION_1_VALUE              1237
#define IDC_STATIC58                    1237
#define IDC_OPTION_2_VALUE              1238
#define IDC_STATIC59                    1238
#define IDC_COUNT                       1239
#define IDC_PREFIX_1_VALUE              1240
#define IDC_PREFIX_2_VALUE              1241
#define IDC_PREFIX_3_VALUE              1242
#define IDC_ITEM_CODE                   1243
#define IDC_OPTION_1_COMMENT            1244
#define IDC_EDIT_GUARDIAN               1244
#define IDC_SELECT_ITEM_DETAIL_INFO     1245
#define IDC_OPTION_2_COMMENT            1245
#define IDC_PREFIX_2_VALUE2             1246
#define IDC_EDIT_PACK_NAME              1247
#define IDC_PREFIX_3_VALUE2             1247
#define IDC_PACK_LIST                   1248
#define IDC_OPTION_1_COMMENT2           1248
#define IDC_PREFIX1                     1249
#define IDC_OPTION1                     1250
#define IDC_PREFIX_1_VALUE2             1251
#define IDC_OPTION_1_COMMENT3           1252
#define IDC_LINK_ITEM                   1252
#define IDC_PREFIX1_KIND                1253
#define IDC_OPTION_1_COMMENT4           1254
#define IDC_GR_YEAR1                    1254
#define IDC_EXPORT                      1256
#define IDC_LIST                        1258
#define IDC_MEMBER_LIST                 1259
#define IDC_GUILD_LIST                  1260
#define IDC_SAVE                        1261
#define IDC_EMER                        1262
#define IDC_IMPORT                      1264
#define IDC_BUTTON3                     1264
#define IDC_CHECK_OPERLEVEL             1265
#define IDC_CHECK_QUEST_050707          1265
#define IDC_PRIZE_WINNING_ITEM          1266
#define IDC_CHECK_QUEST_50708           1266
#define IDC_CREATEACCOUNT               1267
#define IDC_CHECK_QUEST_50709           1267
#define IDC_BLOCK_TO_TRADE              1267
#define IDC_DBNAME                      1268
#define IDC_CHECK_QUEST_50710           1268
#define IDC_DBACCOUNT                   1269
#define IDC_CHECK_QUEST_50711           1269
#define IDC_DBPASSWORD                  1270
#define IDC_CHECK_QUEST_50712           1270
#define IDC_DBNAMEINPUT                 1271
#define IDC_050720                      1271
#define IDC_DBACCOUNTINPUT              1272
#define IDC_50721                       1272
#define IDC_DBPASSWORDINPUT             1273
#define IDC_50722                       1273
#define IDC_MAKEDBC                     1274
#define IDC_50723                       1274
#define IDC_50724                       1275
#define IDC_DBINFOTYPE                  1276
#define IDC_050818                      1276
#define IDC_SET_TESTER                  1277
#define IDC_50819                       1277
#define IDC_DBIP                        1278
#define IDC_COMMAND_LIST                1279
#define IDC_DBIPVALUE                   1279
#define IDC_REGCOMMAND_LIST             1280
#define IDC_RELEASE_DATE                1283
#define IDC_RELEASE_TIME                1284
#define IDC_ENDTIME_DATE                1285
#define IDC_ENDTIME_TIME                1286
#define IDC_ISUSE_ENDTIME               1287
#define IDC_RELEASE_TIME_STATIC         1288
#define IDC_ENDTIME                     1289
#define IDC_COMMAND_TYPE_STATIC         1290
#define IDC_WORK_FORRESERVE             1291
#define IDC_COMMAND_TARGET_STATIC       1292
#define IDC_SERVERLIST_FORRESERVE       1293
#define IDC_ISSEND_ALLSERVER            1293
#define IDC_COMMAND_PARAM_STATIC1       1294
#define IDC_PARAM1_FORRESERVE           1295
#define IDC_COMMAND_PARAM_STATIC2       1296
#define IDC_PARAM2_FORRESERVE           1297
#define IDC_MSG_STATIC                  1298
#define IDC_MSG_FORRESERVE              1299
#define IDC_MAIN_QUEST                  1300
#define IDC_COMMAND_WHO                 1300
#define IDC_ARBEIT                      1301
#define IDC_WHO                         1301
#define IDC_COMMAND_LIST_STATIC         1302
#define IDC_ASK_CARROT_INFO             1302
#define IDC_REGCOMMAND_LIST_STATIC      1303
#define IDC_ASK_SELECT_SERVER_SALES_INFO 1303
#define IDC_CATEGORY                    1304
#define IDC_MODIFY_CARROT_SHOP_DATA     1305
#define IDC_ADD_CARROT_ITEM             1306
#define IDC_REMOVE_CARROT_ITEM          1307
#define IDC_RESET_CARROT_ITEM_CONTENTS  1308
#define IDC_EDIT_CARROT_ITEM            1309
#define IDC_APPLY_CARROT_ITEM           1310
#define IDC_CARROT_ITEM_LIST            1311
#define IDC_CATEGORY_NAME               1312
#define IDC_MOVE_UP_SELECT_CATEGORY     1313
#define IDC_MOVE_DOWN_SELECT_CATEGORY   1314
#define IDC_PREMIUM_ITEM_LIST           1315
#define IDC_MOVE_UP_SELECT_ITEM         1316
#define IDC_MOVE_DOWN_SELECT_ITEM       1317
#define IDC_CHANGE_GUILDMASTER          1317
#define IDC_SAVE_TO_FILE                1318
#define IDC_CGM_EXPLAIN                 1318
#define IDC_GUILD_INVENTORY             1318
#define IDC_LOAD_FROM_FILE              1319
#define IDC_STATIC_GUILDNAME            1319
#define IDC_PET_AND_GUARDIAN            1319
#define IDC_COPY_CATEGORY               1320
#define IDC_STATIC_NEWGUILDMASTER       1320
#define IDC_RESET_ALL_GUILD_TWINKLE_STATUS 1320
#define IDC_PASTE_CATEGORY              1321
#define IDC_GUILDNAME                   1321
#define IDC_SERVERLIST                  1322
#define IDC_APPLY_NOW                   1322
#define IDC_cbServerList                1323
#define IDC_CARROT_SHOP_WORK            1325
#define IDC_RESET_JOIN_GUILD_DATE       1326
#define IDC_INVENTORY                   1329
#define IDC_BANK                        1331
#define IDC_PLAYER_LIST                 1333
#define IDC_STATIC_GOLD_INFO            1334
#define IDC_IS_FOR_ONLY_YAHOO           1335
#define IDC_IS_FOR_ONLY_REDGEM          1336
#define IDC_LIMIT_WORD_QUIZ_PLAYER_COUNT 1336
#define IDC_LIMIT_OX_QUIZ_PLAYER_COUNT  1337
#define IDC_CHKACCOUNT                  1337
#define IDC_SENDDIRECT                  1338
#define IDC_ERASEMT                     1339
#define IDC_CHANGE_PET_EXP              1339
#define IDC_EXP_SET_TO_PET              1340
#define IDC_EXP_SET_TO_GUARDIAN         1341
#define IDC_EDIT_PET                    1342
#define IDC_MAIN_QUEST_VALUE            1343
#define IDC_RESET_OPER                  1344
#define IDC_TWINKLE_MARK                1345
#define IDC_CHANGE_HALL_LEVEL           1346
#define IDC_SELECT_ABLE                 1347
#define IDC_SELECT_ONE_PREFIX           1348
#define IDC_CHANGE_PLACE_REATED         1348
#define IDC_BUTTON_SAVE_GUILD_ETC       1350
#define IDC_SAVE_COUNT_OF_GPB           1351
#define IDC_COMBO_MINIPET_TYPE          1353
#define IDC_RESET                       1355
#define IDC_APPLY_DUEL_RECORD           1356
#define IDC_GET_DUEL_RECORD             1357
#define IDC_LIST_RESULT                 1360
#define IDC_ADD_TEAM_LIST               1362
#define IDC_MEMBER_COUNT                1363
#define IDC_PET_CODE1                   1364
#define IDC_PET_CODE2                   1365
#define IDC_GET_CODE1                   1366
#define IDC_GET_CODE2                   1367
#define IDC_GET_CODE                    1368
#define IDC_REMOVE_PET1                 1368
#define IDC_REMOVE_PET2                 1369
#define IDC_EVENT_LIST_STATIC           1373
#define IDC_EVENT_LIST_EDIT             1374
#define IDC_EVENT_LIST_BUTTON_SERCH     1375
#define IDC_EVENT_LIST_BUTTON_OK        1376
#define CHATTING_EVENT_STATIC           1377
#define IDC_CHATTING_EVENT_EDIT         1378
#define IDC_CHATTING_EVENT_BUTTON_SET   1379
#define IDC_CHATTING_EVENT_BUTTON_RELEASE 1380
#define IDC_WORD_EVENT_CHECK_EXP200     1381
#define IDC_TEXT_SOUND_OF_LEDERS_BELL   1381
#define IDC_WORD_EVENT_CHECK_ITEM200    1382
#define IDC_RESET_SOUND_OF_LEDERS_BELL  1382
#define IDC_WORD_EVENT_CHECK_ATK200     1383
#define IDC_CHANGE_MESSAGE_OF_SOUND_OF_LEDERS_BELL 1383
#define IDC_WORD_EVENT_CHECK_DEF200     1384
#define IDC_SOUND_OF_LEDERS_BELL_FRAME  1384
#define IDC_WORD_EVENT_CHECK_MOVESPD200 1385
#define IDC_CANCEL_SOUND_OF_LEDERS_BELL 1385
#define IDC_WORD_EVENT_CHECK_CPMAX      1386
#define IDC_CHECK_EVENT_INFO            1386
#define IDC_WORD_EVENT_CHECK_DOTGE200   1387
#define IDC_WORD_EVENT_CHECK_ATK300     1389
#define IDC_WORD_EVENT_CHECK_HP200      1390
#define IDC_WORD_EVENT_CHECK_CP200      1391
#define IDC_WORD_EVENT_CHECK_DEF300     1392
#define IDC_WORD_EVENT_HOUR             1393
#define IDC_WORD_EVENT_MINITE           1394
#define IDC_WORD_EVENT_LIST_CHECK       1395
#define IDC_CHATTING_EVENT_STATIC       1396
#define IDC_WORD_EVENT_END_HOUR         1397
#define IDC_WORD_EVENT_END_MINITE       1398
#define IDC_WORD_EVENT_BEGIN_HOUR       1399
#define IDC_WORD_EVENT_BEGIN_MINITE     1400
#define IDC_CHATTING_EVENT_STATIC2      1401
#define IDC_WORD_EVENT_BEGIN_YEAR       1402
#define IDC_WORD_EVENT_BEGIN_MONTH      1403
#define IDC_WORD_EVENT_END_YEAR         1404
#define IDC_WORD_EVENT_END_MONTH        1405
#define IDC_WORD_EVENT_END_DAY          1406
#define IDC_WORD_EVENT_BEGIN_DAY        1407
#define IDC_CHATTING_EVENT_STARTMENT_EDIT 1410
#define IDC_CHATTING_EVENT_ENDMENT_EDIT 1411
#define IDC_CHATTING_EVENT_ACTIVEMENT_EDIT 1413
#define IDC_WORD_QUIZ_NAME              1415
#define IDC_RESTRAINT_FIRE              1420
#define IDC_RESTRAINT_WATER             1421
#define IDC_RESTRAINT_WIND              1422
#define IDC_RESTRAINT_EARTH             1423
#define IDC_RESTRAINT_LIGHT             1424
#define IDC_RESTRAINT_DARK              1425
#define IDC_RESTRAINT_BONUS_STRENGTH    1426
#define IDC_RESTRAINT_BONUS_WISDOM      1427
#define IDC_RESTRAINT_BONUS_AGILITY     1428
#define IDC_RESTRAINT_BONUS_CONSTITUTION 1429
#define IDC_RESTRAINT_BONUS_INTELLIGENCE 1430
#define IDC_RESTRAINT_BONUS_CHARISMA    1431
#define IDC_1                           1434
#define IDC_BEGIN_DAY                   1435
#define IDC_ISSUE                       1436
#define IDC_EVENT_KIND                  1437
#define IDC_EVENT_BUFF                  1438
#define IDC_CONNECT                     1438
#define IDC_YY1                         1439
#define IDC_GET_SERVER_DATA             1440
#define IDC_LOAD_DATA                   1441
#define IDC_CONNECT_ALL                 1442
#define IDC_STATUS                      1443
#define IDC_ITEM_TEST                   1444
#define IDC_ITEM_HOT                    1445
#define IDC_RESET_TRANS_GVG_DATE        1445
#define IDC_ITEM_RECOMMAND              1446
#define IDC_SAVE_TODAY_GUILD_BATTLE_COUNT 1446
#define IDC_TEST_CATE                   1447
#define IDC_SAVE_THIS_WEEK_GUILD_BATTLE_COUNT 1447
#define IDC_HOT_CATE                    1448
#define IDC_RECOMMAND_CATE              1449
#define IDC_REQUITAL_PERIOD_ITEM        11105
#define IDC_BUILD_GUILD_BATTLE_PROLOG_RESULT 11276
#define IDC_ROOKIE_EVENT_090720         11277
#define IDC_ROOKIE_EVENT_RUN_090720     11278
#define IDC_100721                      11279
#define IDC_REWARD_OLD_REBIRTHER        11280
#define ID_SAVELIST                     32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1447
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
